"""Geo-KB 种子数据：约 50 个高频国家的判别性地理档案。

维度说明（都是 GeoGuessr 玩家/OSINT 常用的"线索→国家"对照）：
- driving_side: left / right
- speed_unit: kmh / mph
- languages: 主要语言（英文名，engine 支持中文别名映射）
- scripts: 文字体系（Latin / Cyrillic / Greek / Arabic / Hebrew / Chinese / Hangul / Thai / Devanagari）
- plates: 车牌特征（用于展示与关键词匹配）
- suffixes: 常见街道后缀（对 visible_text 做正则匹配）
- tld / phone / currency / plugs: 参考信息（展示用，暂不参与匹配）

注意：这是"高判别力提示"而非法律事实；个别国家可能并存多种样式，
engine 以加权打分处理，不做硬性断言。
"""

COUNTRY_SEED: list[dict] = [
    # ---- 欧洲 ----
    {"name": "United Kingdom", "driving_side": "left", "speed_unit": "mph",
     "languages": ["English"], "scripts": ["Latin"],
     "plates": "white front / yellow rear",
     "suffixes": ["Street", "Road", "Lane", "Close", "Avenue", "High Street", "Crescent"],
     "tld": ".uk", "phone": "+44", "currency": "GBP", "plugs": "G"},
    {"name": "Ireland", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["English", "Irish"], "scripts": ["Latin"],
     "plates": "white front / white rear",
     "suffixes": ["Street", "Road", "Lane", "Avenue", "Grove", "Park"],
     "tld": ".ie", "phone": "+353", "currency": "EUR", "plugs": "G"},
    {"name": "Germany", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["German"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["Straße", "Strasse", "Weg", "Allee", "Platz", "Ring", "Gasse", "Damm"],
     "tld": ".de", "phone": "+49", "currency": "EUR", "plugs": "F"},
    {"name": "France", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["French"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["Rue", "Avenue", "Boulevard", "Place", "Impasse", "Chemin", "Allée"],
     "tld": ".fr", "phone": "+33", "currency": "EUR", "plugs": "E"},
    {"name": "Spain", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["Calle", "Avenida", "Plaza", "Camino", "Paseo", "Ronda"],
     "tld": ".es", "phone": "+34", "currency": "EUR", "plugs": "F"},
    {"name": "Portugal", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Portuguese"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["Rua", "Avenida", "Praça", "Largo", "Estrada", "Travessa"],
     "tld": ".pt", "phone": "+351", "currency": "EUR", "plugs": "F"},
    {"name": "Italy", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Italian"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["Via", "Corso", "Piazza", "Viale", "Strada", "Largo", "Vicolo"],
     "tld": ".it", "phone": "+39", "currency": "EUR", "plugs": "F/L"},
    {"name": "Netherlands", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Dutch"], "scripts": ["Latin"],
     "plates": "yellow plate with black text",
     "suffixes": ["Straat", "Laan", "Weg", "Plein", "Dorp", "Kade", "Hof"],
     "tld": ".nl", "phone": "+31", "currency": "EUR", "plugs": "F"},
    {"name": "Belgium", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Dutch", "French"], "scripts": ["Latin"],
     "plates": "white plate with red text",
     "suffixes": ["Straat", "Rue", "Weg", "Laan", "Avenue"],
     "tld": ".be", "phone": "+32", "currency": "EUR", "plugs": "E"},
    {"name": "Switzerland", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["German", "French", "Italian"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Strasse", "Weg", "Platz", "Rue", "Chemin"],
     "tld": ".ch", "phone": "+41", "currency": "CHF", "plugs": "J"},
    {"name": "Austria", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["German"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["Straße", "Gasse", "Weg", "Platz", "Allee"],
     "tld": ".at", "phone": "+43", "currency": "EUR", "plugs": "F"},
    {"name": "Poland", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Polish"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["ulica", "ul.", "Aleja", "al.", "Plac", "Ulica"],
     "tld": ".pl", "phone": "+48", "currency": "PLN", "plugs": "E"},
    {"name": "Czechia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Czech"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["ulice", "ul.", "náměstí", "třída", "tř.", "nábřeží"],
     "tld": ".cz", "phone": "+420", "currency": "CZK", "plugs": "E"},
    {"name": "Hungary", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Hungarian"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["utca", "u.", "út", "tér", "körút"],
     "tld": ".hu", "phone": "+36", "currency": "HUF", "plugs": "F"},
    {"name": "Ukraine", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Ukrainian"], "scripts": ["Cyrillic"],
     "plates": "white EU-style plate",
     "suffixes": ["вулиця", "вул.", "проспект", "пров.", "майдан", "шосе"],
     "tld": ".ua", "phone": "+380", "currency": "UAH", "plugs": "C/F"},
    {"name": "Romania", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Romanian"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["Strada", "Str.", "Bulevardul", "Bd.", "Aleea", "Șoseaua"],
     "tld": ".ro", "phone": "+40", "currency": "RON", "plugs": "F"},
    {"name": "Bulgaria", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Bulgarian"], "scripts": ["Cyrillic"],
     "plates": "white EU plate",
     "suffixes": ["улица", "ул.", "булевард", "бул.", "площад"],
     "tld": ".bg", "phone": "+359", "currency": "BGN", "plugs": "F"},
    {"name": "Greece", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Greek"], "scripts": ["Greek"],
     "plates": "white EU plate",
     "suffixes": ["Οδός", "Λεωφόρος", "Πλατεία", "Στ."],
     "tld": ".gr", "phone": "+30", "currency": "EUR", "plugs": "F"},
    {"name": "Turkey", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Turkish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Caddesi", "Cd.", "Sokak", "Sk.", "Meydanı", "Bulvarı"],
     "tld": ".tr", "phone": "+90", "currency": "TRY", "plugs": "F"},
    {"name": "Russia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Russian"], "scripts": ["Cyrillic"],
     "plates": "white plate",
     "suffixes": ["улица", "ул.", "проспект", "пр-т", "переулок", "шоссе"],
     "tld": ".ru", "phone": "+7", "currency": "RUB", "plugs": "C/F"},
    {"name": "Sweden", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Swedish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["gatan", "g.", "vägen", "v.", "allén", "stigen"],
     "tld": ".se", "phone": "+46", "currency": "SEK", "plugs": "F"},
    {"name": "Norway", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Norwegian"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["gata", "vei", "allé", "stien", "gate"],
     "tld": ".no", "phone": "+47", "currency": "NOK", "plugs": "F"},
    {"name": "Denmark", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Danish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["gade", "vej", "allé", "plads"],
     "tld": ".dk", "phone": "+45", "currency": "DKK", "plugs": "K"},
    {"name": "Finland", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Finnish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["katu", "tie", "väylä", "polku"],
     "tld": ".fi", "phone": "+358", "currency": "EUR", "plugs": "F"},
    {"name": "Iceland", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Icelandic"], "scripts": ["Latin"],
     "plates": "white/blue plate",
     "suffixes": ["gata", "vegur", "braut"],
     "tld": ".is", "phone": "+354", "currency": "ISK", "plugs": "F"},
    {"name": "Slovakia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Slovak"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["ulica", "ul.", "námestie", "trieda"],
     "tld": ".sk", "phone": "+421", "currency": "EUR", "plugs": "E"},
    {"name": "Croatia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Croatian"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["ulica", "ul.", "trg", "aleja", "put"],
     "tld": ".hr", "phone": "+385", "currency": "EUR", "plugs": "F"},
    {"name": "Serbia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Serbian"], "scripts": ["Cyrillic", "Latin"],
     "plates": "white plate",
     "suffixes": ["улица", "ул.", "ulica", "булевар", "bulevar"],
     "tld": ".rs", "phone": "+381", "currency": "RSD", "plugs": "F"},

    # ---- 美洲 ----
    {"name": "United States", "driving_side": "right", "speed_unit": "mph",
     "languages": ["English"], "scripts": ["Latin"],
     "plates": "state-issued plate, various",
     "suffixes": ["Street", "Road", "Avenue", "Boulevard", "Blvd", "Highway", "Lane", "Drive", "Way"],
     "tld": ".us", "phone": "+1", "currency": "USD", "plugs": "A/B"},
    {"name": "Canada", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["English", "French"], "scripts": ["Latin"],
     "plates": "provincial plate",
     "suffixes": ["Street", "Road", "Avenue", "Boulevard", "Highway", "Lane", "Drive"],
     "tld": ".ca", "phone": "+1", "currency": "CAD", "plugs": "A/B"},
    {"name": "Mexico", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white/yellow plate",
     "suffixes": ["Calle", "Avenida", "Av.", "Boulevard", "Blvd", "Privada"],
     "tld": ".mx", "phone": "+52", "currency": "MXN", "plugs": "A/B"},
    {"name": "Brazil", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Portuguese"], "scripts": ["Latin"],
     "plates": "white Mercosur plate",
     "suffixes": ["Rua", "Avenida", "Av.", "Praça", "Travessa", "Alameda"],
     "tld": ".br", "phone": "+55", "currency": "BRL", "plugs": "N"},
    {"name": "Argentina", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white/black plate",
     "suffixes": ["Calle", "Avenida", "Av.", "Pasaje", "Boulevard"],
     "tld": ".ar", "phone": "+54", "currency": "ARS", "plugs": "C/I"},

    # ---- 亚太 ----
    {"name": "Australia", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["English"], "scripts": ["Latin"],
     "plates": "state plate, white/yellow",
     "suffixes": ["Street", "Road", "Avenue", "Boulevard", "Highway", "Lane", "Drive"],
     "tld": ".au", "phone": "+61", "currency": "AUD", "plugs": "I"},
    {"name": "New Zealand", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["English"], "scripts": ["Latin"],
     "plates": "black on white plate",
     "suffixes": ["Street", "Road", "Avenue", "Lane", "Drive"],
     "tld": ".nz", "phone": "+64", "currency": "NZD", "plugs": "I"},
    {"name": "Japan", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["Japanese"], "scripts": ["Japanese"],
     "plates": "white private / yellow kei plate",
     "suffixes": ["通り", "dori", "丁目", "chome", "市", "区"],
     "tld": ".jp", "phone": "+81", "currency": "JPY", "plugs": "A/B"},
    {"name": "South Korea", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Korean"], "scripts": ["Hangul"],
     "plates": "white plate",
     "suffixes": ["로", "ro", "길", "gil", "대로", "daero", "동", "dong"],
     "tld": ".kr", "phone": "+82", "currency": "KRW", "plugs": "F"},
    {"name": "China", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Chinese"], "scripts": ["Chinese"],
     "plates": "blue plate (small cars)",
     "suffixes": ["路", "lu", "街", "jie", "大道", "dadao", "巷", "xiang"],
     "tld": ".cn", "phone": "+86", "currency": "CNY", "plugs": "A/C/I"},
    {"name": "Taiwan", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Chinese"], "scripts": ["Chinese"],
     "plates": "white/red plate",
     "suffixes": ["路", "lu", "街", "jie", "大道", "dadao", "巷", "xiang"],
     "tld": ".tw", "phone": "+886", "currency": "TWD", "plugs": "A/B"},
    {"name": "India", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["Hindi", "English"], "scripts": ["Latin", "Devanagari"],
     "plates": "white private / yellow commercial",
     "suffixes": ["Road", "Marg", "Nagar", "Chowk", "Gali"],
     "tld": ".in", "phone": "+91", "currency": "INR", "plugs": "C/D/M"},
    {"name": "Thailand", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Thai"], "scripts": ["Thai"],
     "plates": "white plate",
     "suffixes": ["ถนน", "thanon", "ซอย", "soi", "แยก"],
     "tld": ".th", "phone": "+66", "currency": "THB", "plugs": "A/B/C"},
    {"name": "Vietnam", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Vietnamese"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["đường", "phố", "hẻm", "ngõ", "đại lộ"],
     "tld": ".vn", "phone": "+84", "currency": "VND", "plugs": "A/C"},
    {"name": "Indonesia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Indonesian"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Jalan", "Jl.", "Gang", "Gg.", "Raya"],
     "tld": ".id", "phone": "+62", "currency": "IDR", "plugs": "C/F"},
    {"name": "Philippines", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Filipino", "English"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Street", "Avenue", "Road", "Barangay", "Brgy."],
     "tld": ".ph", "phone": "+63", "currency": "PHP", "plugs": "A/B/C"},

    # ---- 非洲 / 中东 ----
    {"name": "South Africa", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["English", "Afrikaans"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Street", "Road", "Avenue", "Lane", "Drive"],
     "tld": ".za", "phone": "+27", "currency": "ZAR", "plugs": "M/N"},
    {"name": "Morocco", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Arabic", "French"], "scripts": ["Arabic", "Latin"],
     "plates": "white plate",
     "suffixes": ["Rue", "Avenue", "شارع", "شاريع", "طريق"],
     "tld": ".ma", "phone": "+212", "currency": "MAD", "plugs": "C/E"},
    {"name": "Egypt", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Arabic"], "scripts": ["Arabic"],
     "plates": "white/black plate",
     "suffixes": ["شارع", "شاريع", "ميدان", "طريق"],
     "tld": ".eg", "phone": "+20", "currency": "EGP", "plugs": "C/F"},
    {"name": "United Arab Emirates", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Arabic", "English"], "scripts": ["Arabic", "Latin"],
     "plates": "white plate",
     "suffixes": ["Street", "Road", "شارع", "طريق"],
     "tld": ".ae", "phone": "+971", "currency": "AED", "plugs": "G"},
    {"name": "Israel", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Hebrew", "Arabic"], "scripts": ["Hebrew", "Arabic"],
     "plates": "yellow plate",
     "suffixes": ["רחוב", "Rechov", "דרך", "Derech", "שדרות"],
     "tld": ".il", "phone": "+972", "currency": "ILS", "plugs": "C/H"},
    {"name": "Saudi Arabia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Arabic"], "scripts": ["Arabic"],
     "plates": "white plate",
     "suffixes": ["شارع", "طريق", "ميدان"],
     "tld": ".sa", "phone": "+966", "currency": "SAR", "plugs": "G"},

    # ---- 第二批扩充（方案 3）----
    {"name": "Belarus", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Belarusian", "Russian"], "scripts": ["Cyrillic"],
     "plates": "white plate",
     "suffixes": ["вуліца", "вул.", "праспект", "вулица", "плошча"],
     "tld": ".by", "phone": "+375", "currency": "BYN", "plugs": "C/F"},
    {"name": "Latvia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Latvian"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["iela", "prospekts", "bulvāris", "laukums"],
     "tld": ".lv", "phone": "+371", "currency": "EUR", "plugs": "F"},
    {"name": "Lithuania", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Lithuanian"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["gatvė", "prospektas", "alėja", "aikštė"],
     "tld": ".lt", "phone": "+370", "currency": "EUR", "plugs": "F"},
    {"name": "Estonia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Estonian"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["tänav", "tee", "puiestee", "väljak"],
     "tld": ".ee", "phone": "+372", "currency": "EUR", "plugs": "F"},
    {"name": "Slovenia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Slovenian"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["ulica", "cesta", "trg", "aleja"],
     "tld": ".si", "phone": "+386", "currency": "EUR", "plugs": "F"},
    {"name": "Luxembourg", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Luxembourgish", "French", "German"], "scripts": ["Latin"],
     "plates": "white front / yellow rear plate",
     "suffixes": ["rue", "Straße", "Strooss", "avenue", "Weg"],
     "tld": ".lu", "phone": "+352", "currency": "EUR", "plugs": "F"},
    {"name": "Malta", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["Maltese", "English"], "scripts": ["Latin"],
     "plates": "white EU plate",
     "suffixes": ["Triq", "Vjal", "Pjazza", "Sqaq"],
     "tld": ".mt", "phone": "+356", "currency": "EUR", "plugs": "G"},
    {"name": "Cyprus", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["Greek", "Turkish", "English"], "scripts": ["Latin", "Greek"],
     "plates": "white EU plate",
     "suffixes": ["Οδός", "Λεωφόρος", "Street", "Sokak"],
     "tld": ".cy", "phone": "+357", "currency": "EUR", "plugs": "G"},
    {"name": "Moldova", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Romanian"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Strada", "Bulevardul", "Aleea"],
     "tld": ".md", "phone": "+373", "currency": "MDL", "plugs": "C/F"},
    {"name": "Chile", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Calle", "Avenida", "Pasaje", "Camino"],
     "tld": ".cl", "phone": "+56", "currency": "CLP", "plugs": "L"},
    {"name": "Peru", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Calle", "Avenida", "Jr.", "Jirón"],
     "tld": ".pe", "phone": "+51", "currency": "PEN", "plugs": "A/C"},
    {"name": "Colombia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white/yellow plate",
     "suffixes": ["Calle", "Carrera", "Avenida", "Transversal"],
     "tld": ".co", "phone": "+57", "currency": "COP", "plugs": "A/B"},
    {"name": "Uruguay", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Calle", "Avenida", "Pasaje"],
     "tld": ".uy", "phone": "+598", "currency": "UYU", "plugs": "C/F/I"},
    {"name": "Paraguay", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish", "Guarani"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Calle", "Avenida", "Ruta"],
     "tld": ".py", "phone": "+595", "currency": "PYG", "plugs": "C"},
    {"name": "Ecuador", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Calle", "Avenida", "Pasaje"],
     "tld": ".ec", "phone": "+593", "currency": "USD", "plugs": "A/B"},
    {"name": "Panama", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Calle", "Avenida", "Vía"],
     "tld": ".pa", "phone": "+507", "currency": "USD", "plugs": "A/B"},
    {"name": "Costa Rica", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Calle", "Avenida", "Camino"],
     "tld": ".cr", "phone": "+506", "currency": "CRC", "plugs": "A/B"},
    {"name": "Dominican Republic", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Spanish"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Calle", "Avenida", "Autopista"],
     "tld": ".do", "phone": "+1809", "currency": "DOP", "plugs": "A/B"},
    {"name": "Kenya", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["Swahili", "English"], "scripts": ["Latin"],
     "plates": "white/yellow plate",
     "suffixes": ["Street", "Road", "Avenue", "Lane"],
     "tld": ".ke", "phone": "+254", "currency": "KES", "plugs": "G"},
    {"name": "Nigeria", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["English", "Hausa"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Street", "Road", "Avenue", "Close"],
     "tld": ".ng", "phone": "+234", "currency": "NGN", "plugs": "G"},
    {"name": "Ghana", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["English"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Street", "Road", "Avenue", "Lane"],
     "tld": ".gh", "phone": "+233", "currency": "GHS", "plugs": "G"},
    {"name": "Tanzania", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["Swahili", "English"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["Street", "Road", "Avenue"],
     "tld": ".tz", "phone": "+255", "currency": "TZS", "plugs": "G"},
    {"name": "Ethiopia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Amharic"], "scripts": ["Ethiopic"],
     "plates": "white plate",
     "suffixes": ["መንገድ", "Menged", "ጎዳና", "Gedena"],
     "tld": ".et", "phone": "+251", "currency": "ETB", "plugs": "C/F"},
    {"name": "Algeria", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Arabic", "French"], "scripts": ["Arabic", "Latin"],
     "plates": "white plate",
     "suffixes": ["Rue", "Avenue", "شارع", "طريق"],
     "tld": ".dz", "phone": "+213", "currency": "DZD", "plugs": "C"},
    {"name": "Tunisia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Arabic", "French"], "scripts": ["Arabic", "Latin"],
     "plates": "white plate",
     "suffixes": ["Rue", "Avenue", "شارع", "نهج"],
     "tld": ".tn", "phone": "+216", "currency": "TND", "plugs": "C/E"},
    {"name": "Jordan", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Arabic"], "scripts": ["Arabic"],
     "plates": "white plate",
     "suffixes": ["شارع", "طريق", "ميدان"],
     "tld": ".jo", "phone": "+962", "currency": "JOD", "plugs": "C/D/G"},
    {"name": "Lebanon", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Arabic", "French"], "scripts": ["Arabic", "Latin"],
     "plates": "white plate",
     "suffixes": ["Rue", "شارع", "Avenue", "طريق"],
     "tld": ".lb", "phone": "+961", "currency": "LBP", "plugs": "C/E"},
    {"name": "Iran", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Persian"], "scripts": ["Arabic"],
     "plates": "white plate",
     "suffixes": ["خیابان", "Khiyaban", "میدان", "Meydan", "بلوار"],
     "tld": ".ir", "phone": "+98", "currency": "IRR", "plugs": "C/F"},
    {"name": "Pakistan", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["Urdu", "English"], "scripts": ["Latin", "Arabic"],
     "plates": "white/yellow plate",
     "suffixes": ["Street", "Road", "شاہراہ", "Shahrah"],
     "tld": ".pk", "phone": "+92", "currency": "PKR", "plugs": "C/D"},
    {"name": "Bangladesh", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["Bengali"], "scripts": ["Bengali"],
     "plates": "white plate",
     "suffixes": ["সড়ক", "Road", "রোড"],
     "tld": ".bd", "phone": "+880", "currency": "BDT", "plugs": "A/C/D/G"},
    {"name": "Sri Lanka", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["Sinhala", "Tamil", "English"], "scripts": ["Sinhala"],
     "plates": "white plate",
     "suffixes": ["පාර", "Para", "Street", "Road", "வீதி"],
     "tld": ".lk", "phone": "+94", "currency": "LKR", "plugs": "G"},
    {"name": "Myanmar", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Burmese"], "scripts": ["Burmese"],
     "plates": "white plate",
     "suffixes": ["လမ်း", "Lane", "Road"],
     "tld": ".mm", "phone": "+95", "currency": "MMK", "plugs": "C/D/F"},
    {"name": "Cambodia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Khmer"], "scripts": ["Khmer"],
     "plates": "white plate",
     "suffixes": ["ផ្លូវ", "Phlauv", "មហាវិថី"],
     "tld": ".kh", "phone": "+855", "currency": "KHR", "plugs": "A/C"},
    {"name": "Laos", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Lao"], "scripts": ["Lao"],
     "plates": "white plate",
     "suffixes": ["ຖະໜົນ", "Thanon", "ລາດ"],
     "tld": ".la", "phone": "+856", "currency": "LAK", "plugs": "A/B/C"},
    {"name": "Mongolia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Mongolian"], "scripts": ["Cyrillic"],
     "plates": "white plate",
     "suffixes": ["гудамж", "Gudamj", "зам", "Zam", "талбай"],
     "tld": ".mn", "phone": "+976", "currency": "MNT", "plugs": "C/E"},
    {"name": "Kazakhstan", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Kazakh", "Russian"], "scripts": ["Cyrillic"],
     "plates": "white plate",
     "suffixes": ["көше", "Koshe", "даңғыл", "Dangyl", "улица"],
     "tld": ".kz", "phone": "+7", "currency": "KZT", "plugs": "C/F"},
    {"name": "Azerbaijan", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Azerbaijani"], "scripts": ["Latin"],
     "plates": "white plate",
     "suffixes": ["küçə", "prospekt", "meydan"],
     "tld": ".az", "phone": "+994", "currency": "AZN", "plugs": "C/F"},
    {"name": "Georgia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Georgian"], "scripts": ["Georgian"],
     "plates": "white plate",
     "suffixes": ["ქუჩა", "Kucha", "გამზირი", "Gamziri", "მოედანი"],
     "tld": ".ge", "phone": "+995", "currency": "GEL", "plugs": "C/F"},
    {"name": "Armenia", "driving_side": "right", "speed_unit": "kmh",
     "languages": ["Armenian"], "scripts": ["Armenian"],
     "plates": "white plate",
     "suffixes": ["փողոց", "Poghots", "պողոտա", "Poghota"],
     "tld": ".am", "phone": "+374", "currency": "AMD", "plugs": "C/F"},
    {"name": "Malaysia", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["Malay", "English"], "scripts": ["Latin"],
     "plates": "white/yellow plate",
     "suffixes": ["Jalan", "Jl.", "Lorong", "Lebuh", "Persiaran"],
     "tld": ".my", "phone": "+60", "currency": "MYR", "plugs": "G"},
    {"name": "Singapore", "driving_side": "left", "speed_unit": "kmh",
     "languages": ["English", "Chinese", "Malay"], "scripts": ["Latin", "Chinese"],
     "plates": "white plate",
     "suffixes": ["Street", "Road", "Avenue", "Way", "Drive"],
     "tld": ".sg", "phone": "+65", "currency": "SGD", "plugs": "G"},
    # ---- 扩充至 180 国（与 geo_dims.py 对齐；基础维度，自然/人文细节见 geo_dims）----
    {"name": "Afghanistan", "driving_side": "right", "speed_unit": "kmh", "languages": ["Pashto", "Dari"], "scripts": ["Arabic"], "plates": "black/white", "suffixes": ["Jada", "Kocha"], "tld": ".af", "phone": "+93", "currency": "AFN", "plugs": "C/F"},
    {"name": "Albania", "driving_side": "right", "speed_unit": "kmh", "languages": ["Albanian"], "scripts": ["Latin"], "plates": "white, red stripe", "suffixes": ["Rruga"], "tld": ".al", "phone": "+355", "currency": "ALL", "plugs": "C/F"},
    {"name": "Angola", "driving_side": "right", "speed_unit": "kmh", "languages": ["Portuguese"], "scripts": ["Latin"], "plates": "white/red", "suffixes": ["Rua", "Avenida"], "tld": ".ao", "phone": "+244", "currency": "AOA", "plugs": "C/F"},
    {"name": "Bahamas", "driving_side": "left", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white", "suffixes": ["Street", "Road"], "tld": ".bs", "phone": "+1-242", "currency": "BSD", "plugs": "A/B"},
    {"name": "Bahrain", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic"], "scripts": ["Arabic"], "plates": "white/blue", "suffixes": ["Road", "Avenue"], "tld": ".bh", "phone": "+973", "currency": "BHD", "plugs": "G"},
    {"name": "Belize", "driving_side": "right", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Street", "Road"], "tld": ".bz", "phone": "+501", "currency": "BZD", "plugs": "A/B/G"},
    {"name": "Benin", "driving_side": "right", "speed_unit": "kmh", "languages": ["French"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Rue", "Avenue"], "tld": ".bj", "phone": "+229", "currency": "XOF", "plugs": "C/E"},
    {"name": "Bhutan", "driving_side": "left", "speed_unit": "kmh", "languages": ["Dzongkha"], "scripts": ["Tibetan"], "plates": "white/blue", "suffixes": ["Lam"], "tld": ".bt", "phone": "+975", "currency": "BTN", "plugs": "D/F/G"},
    {"name": "Bolivia", "driving_side": "right", "speed_unit": "kmh", "languages": ["Spanish"], "scripts": ["Latin"], "plates": "white", "suffixes": ["Calle", "Avenida"], "tld": ".bo", "phone": "+591", "currency": "BOB", "plugs": "A/C"},
    {"name": "Bosnia and Herzegovina", "driving_side": "right", "speed_unit": "kmh", "languages": ["Bosnian", "Croatian", "Serbian"], "scripts": ["Latin", "Cyrillic"], "plates": "white, blue strip", "suffixes": ["Ulica", "Put"], "tld": ".ba", "phone": "+387", "currency": "BAM", "plugs": "C/F"},
    {"name": "Botswana", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "Tswana"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".bw", "phone": "+267", "currency": "BWP", "plugs": "D/G"},
    {"name": "Brunei", "driving_side": "left", "speed_unit": "kmh", "languages": ["Malay"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Jalan"], "tld": ".bn", "phone": "+673", "currency": "BND", "plugs": "G"},
    {"name": "Burkina Faso", "driving_side": "right", "speed_unit": "kmh", "languages": ["French"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Rue", "Avenue"], "tld": ".bf", "phone": "+226", "currency": "XOF", "plugs": "C/E"},
    {"name": "Burundi", "driving_side": "right", "speed_unit": "kmh", "languages": ["Kirundi", "French"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Avenue", "Rue"], "tld": ".bi", "phone": "+257", "currency": "BIF", "plugs": "C/E"},
    {"name": "Cameroon", "driving_side": "right", "speed_unit": "kmh", "languages": ["French", "English"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Rue", "Avenue"], "tld": ".cm", "phone": "+237", "currency": "XAF", "plugs": "C/E"},
    {"name": "Central African Republic", "driving_side": "right", "speed_unit": "kmh", "languages": ["French", "Sango"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Rue", "Avenue"], "tld": ".cf", "phone": "+236", "currency": "XAF", "plugs": "C/E"},
    {"name": "Chad", "driving_side": "right", "speed_unit": "kmh", "languages": ["French", "Arabic"], "scripts": ["Latin", "Arabic"], "plates": "white/black", "suffixes": ["Rue", "Avenue"], "tld": ".td", "phone": "+235", "currency": "XAF", "plugs": "C/E"},
    {"name": "Congo", "driving_side": "right", "speed_unit": "kmh", "languages": ["French"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Rue", "Avenue"], "tld": ".cg", "phone": "+242", "currency": "XAF", "plugs": "C/E"},
    {"name": "Cuba", "driving_side": "right", "speed_unit": "kmh", "languages": ["Spanish"], "scripts": ["Latin"], "plates": "white/yellow", "suffixes": ["Calle", "Avenida"], "tld": ".cu", "phone": "+53", "currency": "CUP", "plugs": "A/B/C"},
    {"name": "Democratic Republic of the Congo", "driving_side": "right", "speed_unit": "kmh", "languages": ["French"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Rue", "Avenue"], "tld": ".cd", "phone": "+243", "currency": "CDF", "plugs": "C/E"},
    {"name": "Djibouti", "driving_side": "right", "speed_unit": "kmh", "languages": ["French", "Arabic"], "scripts": ["Latin", "Arabic"], "plates": "white/blue", "suffixes": ["Rue", "Avenue"], "tld": ".dj", "phone": "+253", "currency": "DJF", "plugs": "C/E"},
    {"name": "East Timor", "driving_side": "left", "speed_unit": "kmh", "languages": ["Portuguese", "Tetum"], "scripts": ["Latin"], "plates": "white/yellow", "suffixes": ["Rua", "Avenida"], "tld": ".tl", "phone": "+670", "currency": "USD", "plugs": "C/F"},
    {"name": "El Salvador", "driving_side": "right", "speed_unit": "kmh", "languages": ["Spanish"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Calle", "Avenida"], "tld": ".sv", "phone": "+503", "currency": "USD", "plugs": "A/B"},
    {"name": "Eritrea", "driving_side": "right", "speed_unit": "kmh", "languages": ["Tigrinya", "Arabic"], "scripts": ["Ge'ez", "Arabic"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".er", "phone": "+291", "currency": "ERN", "plugs": "C/F"},
    {"name": "Eswatini", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "Swazi"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".sz", "phone": "+268", "currency": "SZL", "plugs": "M"},
    {"name": "Falkland Islands", "driving_side": "left", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white/green", "suffixes": ["Road", "Street"], "tld": ".fk", "phone": "+500", "currency": "FKP", "plugs": "G"},
    {"name": "Federated States of Micronesia", "driving_side": "right", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Street", "Road"], "tld": ".fm", "phone": "+691", "currency": "USD", "plugs": "A/B"},
    {"name": "Fiji", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "Fijian"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".fj", "phone": "+679", "currency": "FJD", "plugs": "I"},
    {"name": "Gabon", "driving_side": "right", "speed_unit": "kmh", "languages": ["French"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Rue", "Avenue"], "tld": ".ga", "phone": "+241", "currency": "XAF", "plugs": "C"},
    {"name": "Greenland", "driving_side": "right", "speed_unit": "kmh", "languages": ["Greenlandic", "Danish"], "scripts": ["Latin"], "plates": "white/red", "suffixes": ["Vejen", "Gade"], "tld": ".gl", "phone": "+299", "currency": "DKK", "plugs": "C/E/K"},
    {"name": "Guatemala", "driving_side": "right", "speed_unit": "kmh", "languages": ["Spanish"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Calle", "Avenida"], "tld": ".gt", "phone": "+502", "currency": "GTQ", "plugs": "A/B"},
    {"name": "Guinea", "driving_side": "right", "speed_unit": "kmh", "languages": ["French"], "scripts": ["Latin"], "plates": "white/red", "suffixes": ["Rue", "Avenue"], "tld": ".gn", "phone": "+224", "currency": "GNF", "plugs": "C/F"},
    {"name": "Guyana", "driving_side": "left", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Street", "Road"], "tld": ".gy", "phone": "+592", "currency": "GYD", "plugs": "A/B/D/G"},
    {"name": "Haiti", "driving_side": "right", "speed_unit": "kmh", "languages": ["French", "Haitian Creole"], "scripts": ["Latin"], "plates": "white/red", "suffixes": ["Rue", "Avenue"], "tld": ".ht", "phone": "+509", "currency": "HTG", "plugs": "A/B"},
    {"name": "Honduras", "driving_side": "right", "speed_unit": "kmh", "languages": ["Spanish"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Calle", "Avenida"], "tld": ".hn", "phone": "+504", "currency": "HNL", "plugs": "A/B"},
    {"name": "Hong Kong", "driving_side": "left", "speed_unit": "kmh", "languages": ["Chinese", "English"], "scripts": ["Chinese", "Latin"], "plates": "white/red", "suffixes": ["Road", "Street", "路"], "tld": ".hk", "phone": "+852", "currency": "HKD", "plugs": "G"},
    {"name": "Iraq", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic", "Kurdish"], "scripts": ["Arabic"], "plates": "white/red", "suffixes": ["Street", "شارع"], "tld": ".iq", "phone": "+964", "currency": "IQD", "plugs": "C/D"},
    {"name": "Ivory Coast", "driving_side": "right", "speed_unit": "kmh", "languages": ["French"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Rue", "Avenue"], "tld": ".ci", "phone": "+225", "currency": "XOF", "plugs": "C/E"},
    {"name": "Jamaica", "driving_side": "left", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".jm", "phone": "+1-876", "currency": "JMD", "plugs": "A/B"},
    {"name": "Kiribati", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "Gilbertese"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".ki", "phone": "+686", "currency": "AUD", "plugs": "I"},
    {"name": "Kuwait", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic"], "scripts": ["Arabic"], "plates": "white/black", "suffixes": ["Street", "Road"], "tld": ".kw", "phone": "+965", "currency": "KWD", "plugs": "G"},
    {"name": "Kyrgyzstan", "driving_side": "right", "speed_unit": "kmh", "languages": ["Kyrgyz", "Russian"], "scripts": ["Cyrillic"], "plates": "white/black", "suffixes": ["улица", "проспект"], "tld": ".kg", "phone": "+996", "currency": "KGS", "plugs": "C/F"},
    {"name": "Lesotho", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "Sotho"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".ls", "phone": "+266", "currency": "LSL", "plugs": "M"},
    {"name": "Liberia", "driving_side": "right", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Street", "Road"], "tld": ".lr", "phone": "+231", "currency": "LRD", "plugs": "A/B"},
    {"name": "Libya", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic"], "scripts": ["Arabic"], "plates": "white/black", "suffixes": ["شارع"], "tld": ".ly", "phone": "+218", "currency": "LYD", "plugs": "C/D/F"},
    {"name": "Macau", "driving_side": "left", "speed_unit": "kmh", "languages": ["Chinese", "Portuguese"], "scripts": ["Chinese", "Latin"], "plates": "white/black", "suffixes": ["Rua", "路"], "tld": ".mo", "phone": "+853", "currency": "MOP", "plugs": "G"},
    {"name": "Madagascar", "driving_side": "right", "speed_unit": "kmh", "languages": ["Malagasy", "French"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Rue", "Lalana"], "tld": ".mg", "phone": "+261", "currency": "MGA", "plugs": "C/E"},
    {"name": "Malawi", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "Chichewa"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".mw", "phone": "+265", "currency": "MWK", "plugs": "G"},
    {"name": "Mali", "driving_side": "right", "speed_unit": "kmh", "languages": ["French", "Bambara"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Rue", "Avenue"], "tld": ".ml", "phone": "+223", "currency": "XOF", "plugs": "C/E"},
    {"name": "Marshall Islands", "driving_side": "right", "speed_unit": "kmh", "languages": ["English", "Marshallese"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".mh", "phone": "+692", "currency": "USD", "plugs": "A/B"},
    {"name": "Mauritania", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic", "French"], "scripts": ["Arabic", "Latin"], "plates": "white/black", "suffixes": ["Rue", "شارع"], "tld": ".mr", "phone": "+222", "currency": "MRU", "plugs": "C/E"},
    {"name": "Mauritius", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "French", "Creole"], "scripts": ["Latin"], "plates": "white/red", "suffixes": ["Road", "Rue"], "tld": ".mu", "phone": "+230", "currency": "MUR", "plugs": "C/G"},
    {"name": "Montenegro", "driving_side": "right", "speed_unit": "kmh", "languages": ["Montenegrin"], "scripts": ["Latin", "Cyrillic"], "plates": "white, red strip", "suffixes": ["Ulica", "Put"], "tld": ".me", "phone": "+382", "currency": "EUR", "plugs": "C/F"},
    {"name": "Mozambique", "driving_side": "left", "speed_unit": "kmh", "languages": ["Portuguese"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Rua", "Avenida"], "tld": ".mz", "phone": "+258", "currency": "MZN", "plugs": "C/F/M"},
    {"name": "Namibia", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "Afrikaans"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".na", "phone": "+264", "currency": "NAD", "plugs": "D/M"},
    {"name": "Nauru", "driving_side": "left", "speed_unit": "kmh", "languages": ["Nauruan", "English"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".nr", "phone": "+674", "currency": "AUD", "plugs": "I"},
    {"name": "Nepal", "driving_side": "left", "speed_unit": "kmh", "languages": ["Nepali"], "scripts": ["Devanagari"], "plates": "white/red", "suffixes": ["Marg", "Road", "Chowk"], "tld": ".np", "phone": "+977", "currency": "NPR", "plugs": "C/D"},
    {"name": "New Caledonia", "driving_side": "right", "speed_unit": "kmh", "languages": ["French"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Rue", "Avenue"], "tld": ".nc", "phone": "+687", "currency": "XPF", "plugs": "C/F"},
    {"name": "Nicaragua", "driving_side": "right", "speed_unit": "kmh", "languages": ["Spanish"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Calle", "Avenida"], "tld": ".ni", "phone": "+505", "currency": "NIO", "plugs": "A/B"},
    {"name": "Niger", "driving_side": "right", "speed_unit": "kmh", "languages": ["French"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Rue", "Avenue"], "tld": ".ne", "phone": "+227", "currency": "XOF", "plugs": "C/E"},
    {"name": "North Korea", "driving_side": "right", "speed_unit": "kmh", "languages": ["Korean"], "scripts": ["Hangul"], "plates": "white/blue", "suffixes": ["로", "길"], "tld": ".kp", "phone": "+850", "currency": "KPW", "plugs": "C/F"},
    {"name": "North Macedonia", "driving_side": "right", "speed_unit": "kmh", "languages": ["Macedonian", "Albanian"], "scripts": ["Cyrillic", "Latin"], "plates": "white, red strip", "suffixes": ["Ulica", "Bulevar"], "tld": ".mk", "phone": "+389", "currency": "MKD", "plugs": "C/F"},
    {"name": "Oman", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic"], "scripts": ["Arabic"], "plates": "white/blue", "suffixes": ["Street", "Road"], "tld": ".om", "phone": "+968", "currency": "OMR", "plugs": "G"},
    {"name": "Palau", "driving_side": "right", "speed_unit": "kmh", "languages": ["English", "Palauan"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".pw", "phone": "+680", "currency": "USD", "plugs": "A/B"},
    {"name": "Palestine", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic"], "scripts": ["Arabic"], "plates": "white/black", "suffixes": ["شارع"], "tld": ".ps", "phone": "+970", "currency": "ILS", "plugs": "C/H"},
    {"name": "Papua New Guinea", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "Tok Pisin"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".pg", "phone": "+675", "currency": "PGK", "plugs": "I"},
    {"name": "Qatar", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic"], "scripts": ["Arabic"], "plates": "white/blue", "suffixes": ["Street", "Road"], "tld": ".qa", "phone": "+974", "currency": "QAR", "plugs": "G"},
    {"name": "Rwanda", "driving_side": "right", "speed_unit": "kmh", "languages": ["Kinyarwanda", "French", "English"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".rw", "phone": "+250", "currency": "RWF", "plugs": "C/J"},
    {"name": "Samoa", "driving_side": "left", "speed_unit": "kmh", "languages": ["Samoan", "English"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".ws", "phone": "+685", "currency": "WST", "plugs": "I"},
    {"name": "Senegal", "driving_side": "right", "speed_unit": "kmh", "languages": ["French", "Wolof"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Rue", "Avenue"], "tld": ".sn", "phone": "+221", "currency": "XOF", "plugs": "C/E"},
    {"name": "Sierra Leone", "driving_side": "right", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Street", "Road"], "tld": ".sl", "phone": "+232", "currency": "SLL", "plugs": "D/G"},
    {"name": "Solomon Islands", "driving_side": "left", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".sb", "phone": "+677", "currency": "SBD", "plugs": "I"},
    {"name": "Somalia", "driving_side": "right", "speed_unit": "kmh", "languages": ["Somali", "Arabic"], "scripts": ["Latin", "Arabic"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".so", "phone": "+252", "currency": "SOS", "plugs": "C/E"},
    {"name": "South Sudan", "driving_side": "right", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".ss", "phone": "+211", "currency": "SSP", "plugs": "C/D"},
    {"name": "Sudan", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic", "English"], "scripts": ["Arabic", "Latin"], "plates": "white/blue", "suffixes": ["شارع"], "tld": ".sd", "phone": "+249", "currency": "SDG", "plugs": "C/D"},
    {"name": "Suriname", "driving_side": "left", "speed_unit": "kmh", "languages": ["Dutch"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Straat", "Weg"], "tld": ".sr", "phone": "+597", "currency": "SRD", "plugs": "C/F"},
    {"name": "Syria", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic"], "scripts": ["Arabic"], "plates": "white/red", "suffixes": ["شارع"], "tld": ".sy", "phone": "+963", "currency": "SYP", "plugs": "C/E"},
    {"name": "Tajikistan", "driving_side": "right", "speed_unit": "kmh", "languages": ["Tajik", "Russian"], "scripts": ["Cyrillic"], "plates": "white/black", "suffixes": ["улица", "проспект"], "tld": ".tj", "phone": "+992", "currency": "TJS", "plugs": "C/F"},
    {"name": "Togo", "driving_side": "right", "speed_unit": "kmh", "languages": ["French"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Rue", "Avenue"], "tld": ".tg", "phone": "+228", "currency": "XOF", "plugs": "C/E"},
    {"name": "Tonga", "driving_side": "left", "speed_unit": "kmh", "languages": ["Tongan", "English"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".to", "phone": "+676", "currency": "TOP", "plugs": "I"},
    {"name": "Turkmenistan", "driving_side": "right", "speed_unit": "kmh", "languages": ["Turkmen", "Russian"], "scripts": ["Latin", "Cyrillic"], "plates": "white/black", "suffixes": ["улица", "проспект"], "tld": ".tm", "phone": "+993", "currency": "TMT", "plugs": "C/F"},
    {"name": "Tuvalu", "driving_side": "left", "speed_unit": "kmh", "languages": ["Tuvaluan", "English"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".tv", "phone": "+688", "currency": "AUD", "plugs": "I"},
    {"name": "Uganda", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "Swahili"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".ug", "phone": "+256", "currency": "UGX", "plugs": "G"},
    {"name": "Uzbekistan", "driving_side": "right", "speed_unit": "kmh", "languages": ["Uzbek", "Russian"], "scripts": ["Latin", "Cyrillic"], "plates": "white/black", "suffixes": ["улица", "проспект"], "tld": ".uz", "phone": "+998", "currency": "UZS", "plugs": "C/F"},
    {"name": "Vanuatu", "driving_side": "right", "speed_unit": "kmh", "languages": ["Bislama", "English", "French"], "scripts": ["Latin"], "plates": "white/black", "suffixes": ["Road", "Street"], "tld": ".vu", "phone": "+678", "currency": "VUV", "plugs": "I"},
    {"name": "Venezuela", "driving_side": "right", "speed_unit": "kmh", "languages": ["Spanish"], "scripts": ["Latin"], "plates": "white/yellow", "suffixes": ["Calle", "Avenida"], "tld": ".ve", "phone": "+58", "currency": "VES", "plugs": "A/B"},
    {"name": "Yemen", "driving_side": "right", "speed_unit": "kmh", "languages": ["Arabic"], "scripts": ["Arabic"], "plates": "white/blue", "suffixes": ["شارع"], "tld": ".ye", "phone": "+967", "currency": "YER", "plugs": "A/D/G"},
    {"name": "Zambia", "driving_side": "left", "speed_unit": "kmh", "languages": ["English"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".zm", "phone": "+260", "currency": "ZMW", "plugs": "C/D/G"},
    {"name": "Zimbabwe", "driving_side": "left", "speed_unit": "kmh", "languages": ["English", "Shona"], "scripts": ["Latin"], "plates": "white/blue", "suffixes": ["Road", "Street"], "tld": ".zw", "phone": "+263", "currency": "ZWL", "plugs": "D/G"},
]

# ---- 国家名别名（LLM 可能输出中文/英文/简称 → 规范化到种子库英文名）----
COUNTRY_ALIASES = {
    "中国": "China", "中华人民共和国": "China",
    "美国": "United States", "美利坚合众国": "United States", "USA": "United States",
    "加拿大": "Canada",
    "英国": "United Kingdom", "大不列颠": "United Kingdom", "UK": "United Kingdom",
    "爱尔兰": "Ireland",
    "德国": "Germany",
    "法国": "France",
    "西班牙": "Spain",
    "葡萄牙": "Portugal",
    "意大利": "Italy",
    "荷兰": "Netherlands", "尼德兰": "Netherlands",
    "比利时": "Belgium",
    "瑞士": "Switzerland",
    "奥地利": "Austria",
    "波兰": "Poland",
    "捷克": "Czechia", "捷克共和国": "Czechia", "Czech Republic": "Czechia",
    "匈牙利": "Hungary",
    "乌克兰": "Ukraine",
    "罗马尼亚": "Romania",
    "保加利亚": "Bulgaria",
    "希腊": "Greece",
    "土耳其": "Turkey",
    "俄罗斯": "Russia", "俄国": "Russia",
    "瑞典": "Sweden",
    "挪威": "Norway",
    "丹麦": "Denmark",
    "芬兰": "Finland",
    "冰岛": "Iceland",
    "斯洛伐克": "Slovakia",
    "克罗地亚": "Croatia",
    "塞尔维亚": "Serbia",
    "墨西哥": "Mexico",
    "巴西": "Brazil",
    "阿根廷": "Argentina",
    "澳大利亚": "Australia",
    "新西兰": "New Zealand",
    "日本": "Japan",
    "韩国": "South Korea", "大韩民国": "South Korea",
    "台湾": "Taiwan",
    "印度": "India",
    "泰国": "Thailand",
    "越南": "Vietnam",
    "印度尼西亚": "Indonesia", "印尼": "Indonesia",
    "菲律宾": "Philippines",
    "南非": "South Africa",
    "摩洛哥": "Morocco",
    "埃及": "Egypt",
    "阿联酋": "United Arab Emirates", "阿拉伯联合酋长国": "United Arab Emirates",
    "以色列": "Israel",
    "沙特阿拉伯": "Saudi Arabia",
    "白俄罗斯": "Belarus",
    "拉脱维亚": "Latvia",
    "立陶宛": "Lithuania",
    "爱沙尼亚": "Estonia",
    "斯洛文尼亚": "Slovenia",
    "马来西亚": "Malaysia",
    "新加坡": "Singapore",
}

# ---- 城市名别名（LLM 中文输出 → 内置城市表英文名）----
CITY_ALIASES = {
    "北京": "Beijing", "上海": "Shanghai",
    "东京": "Tokyo", "大阪": "Osaka",
    "首尔": "Seoul",
    "巴黎": "Paris",
    "伦敦": "London",
    "柏林": "Berlin",
    "马德里": "Madrid",
    "巴塞罗那": "Barcelona",
    "里斯本": "Lisbon",
    "波尔图": "Porto",
    "罗马": "Rome",
    "米兰": "Milan",
    "阿姆斯特丹": "Amsterdam",
    "布鲁塞尔": "Brussels",
    "维也纳": "Vienna",
    "苏黎世": "Zurich",
    "华沙": "Warsaw",
    "布拉格": "Prague",
    "布达佩斯": "Budapest",
    "基辅": "Kyiv",
    "莫斯科": "Moscow",
    "圣彼得堡": "Saint Petersburg",
    "斯德哥尔摩": "Stockholm",
    "奥斯陆": "Oslo",
    "哥本哈根": "Copenhagen",
    "赫尔辛基": "Helsinki",
    "雅典": "Athens",
    "伊斯坦布尔": "Istanbul",
    "安卡拉": "Ankara",
    "布加勒斯特": "Bucharest",
    "索非亚": "Sofia",
    "贝尔格莱德": "Belgrade",
    "萨格勒布": "Zagreb",
    "布拉迪斯拉发": "Bratislava",
    "雷克雅未克": "Reykjavik",
    "纽约": "New York",
    "洛杉矶": "Los Angeles",
    "旧金山": "San Francisco",
    "芝加哥": "Chicago",
    "多伦多": "Toronto",
    "温哥华": "Vancouver",
    "墨西哥城": "Mexico City",
    "里约热内卢": "Rio de Janeiro",
    "圣保罗": "São Paulo",
    "布宜诺斯艾利斯": "Buenos Aires",
    "悉尼": "Sydney",
    "墨尔本": "Melbourne",
    "奥克兰": "Auckland",
    "马拉加": "Málaga",
    "塞维利亚": "Seville", "塞维拉": "Seville",
    "格拉纳达": "Granada",
    "都柏林": "Dublin",
    "爱丁堡": "Edinburgh",
    "曼彻斯特": "Manchester",
    "曼谷": "Bangkok",
    "河内": "Hanoi",
    "胡志明市": "Ho Chi Minh City",
    "雅加达": "Jakarta",
    "马尼拉": "Manila",
    "开罗": "Cairo",
    "迪拜": "Dubai",
    "特拉维夫": "Tel Aviv",
    "耶路撒冷": "Jerusalem",
    "约翰内斯堡": "Johannesburg",
    "开普敦": "Cape Town",
    "卡萨布兰卡": "Casablanca",
}

# ---- 国家中文名 + 国家中心示意坐标（首都坐标）----
# 用途：①前端中文展示 ②国家级结论的"国家中心示意点"（用户要求任何级别都给坐标）
COUNTRY_META: dict[str, dict] = {
    "United Kingdom": {"zh": "英国", "lat": 51.5074, "lon": -0.1278},
    "Ireland": {"zh": "爱尔兰", "lat": 53.3498, "lon": -6.2603},
    "Germany": {"zh": "德国", "lat": 52.52, "lon": 13.405},
    "France": {"zh": "法国", "lat": 48.8566, "lon": 2.3522},
    "Spain": {"zh": "西班牙", "lat": 40.4168, "lon": -3.7038},
    "Portugal": {"zh": "葡萄牙", "lat": 38.7223, "lon": -9.1393},
    "Italy": {"zh": "意大利", "lat": 41.9028, "lon": 12.4964},
    "Netherlands": {"zh": "荷兰", "lat": 52.3676, "lon": 4.9041},
    "Belgium": {"zh": "比利时", "lat": 50.8503, "lon": 4.3517},
    "Switzerland": {"zh": "瑞士", "lat": 46.948, "lon": 7.4474},
    "Austria": {"zh": "奥地利", "lat": 48.2082, "lon": 16.3738},
    "Poland": {"zh": "波兰", "lat": 52.2297, "lon": 21.0122},
    "Czechia": {"zh": "捷克", "lat": 50.0755, "lon": 14.4378},
    "Hungary": {"zh": "匈牙利", "lat": 47.4979, "lon": 19.0402},
    "Ukraine": {"zh": "乌克兰", "lat": 50.4501, "lon": 30.5234},
    "Romania": {"zh": "罗马尼亚", "lat": 44.4268, "lon": 26.1025},
    "Bulgaria": {"zh": "保加利亚", "lat": 42.6977, "lon": 23.3219},
    "Greece": {"zh": "希腊", "lat": 37.9838, "lon": 23.7275},
    "Turkey": {"zh": "土耳其", "lat": 39.9334, "lon": 32.8597},
    "Russia": {"zh": "俄罗斯", "lat": 55.7558, "lon": 37.6173},
    "Sweden": {"zh": "瑞典", "lat": 59.3293, "lon": 18.0686},
    "Norway": {"zh": "挪威", "lat": 59.9139, "lon": 10.7522},
    "Denmark": {"zh": "丹麦", "lat": 55.6761, "lon": 12.5683},
    "Finland": {"zh": "芬兰", "lat": 60.1699, "lon": 24.9384},
    "Iceland": {"zh": "冰岛", "lat": 64.1466, "lon": -21.9426},
    "Slovakia": {"zh": "斯洛伐克", "lat": 48.1486, "lon": 17.1077},
    "Croatia": {"zh": "克罗地亚", "lat": 45.815, "lon": 15.9819},
    "Serbia": {"zh": "塞尔维亚", "lat": 44.7866, "lon": 20.4489},
    "United States": {"zh": "美国", "lat": 38.9072, "lon": -77.0369},
    "Canada": {"zh": "加拿大", "lat": 45.4215, "lon": -75.6972},
    "Mexico": {"zh": "墨西哥", "lat": 19.4326, "lon": -99.1332},
    "Brazil": {"zh": "巴西", "lat": -15.7939, "lon": -47.8828},
    "Argentina": {"zh": "阿根廷", "lat": -34.6037, "lon": -58.3816},
    "Australia": {"zh": "澳大利亚", "lat": -35.2809, "lon": 149.13},
    "New Zealand": {"zh": "新西兰", "lat": -41.2866, "lon": 174.7756},
    "Japan": {"zh": "日本", "lat": 35.6762, "lon": 139.6503},
    "South Korea": {"zh": "韩国", "lat": 37.5665, "lon": 126.978},
    "China": {"zh": "中国", "lat": 39.9042, "lon": 116.4074},
    "Taiwan": {"zh": "台湾", "lat": 25.033, "lon": 121.5654},
    "India": {"zh": "印度", "lat": 28.6139, "lon": 77.209},
    "Thailand": {"zh": "泰国", "lat": 13.7563, "lon": 100.5018},
    "Vietnam": {"zh": "越南", "lat": 21.0278, "lon": 105.8342},
    "Indonesia": {"zh": "印度尼西亚", "lat": -6.2088, "lon": 106.8456},
    "Philippines": {"zh": "菲律宾", "lat": 14.5995, "lon": 120.9842},
    "South Africa": {"zh": "南非", "lat": -25.7479, "lon": 28.2293},
    "Morocco": {"zh": "摩洛哥", "lat": 34.0209, "lon": -6.8416},
    "Egypt": {"zh": "埃及", "lat": 30.0444, "lon": 31.2357},
    "United Arab Emirates": {"zh": "阿联酋", "lat": 24.4539, "lon": 54.3773},
    "Israel": {"zh": "以色列", "lat": 31.7683, "lon": 35.2137},
    "Saudi Arabia": {"zh": "沙特阿拉伯", "lat": 24.7136, "lon": 46.6753},
    "Belarus": {"zh": "白俄罗斯", "lat": 53.9006, "lon": 27.559},
    "Latvia": {"zh": "拉脱维亚", "lat": 56.9496, "lon": 24.1052},
    "Lithuania": {"zh": "立陶宛", "lat": 54.6872, "lon": 25.2797},
    "Estonia": {"zh": "爱沙尼亚", "lat": 59.437, "lon": 24.7536},
    "Slovenia": {"zh": "斯洛文尼亚", "lat": 46.0569, "lon": 14.5058},
    "Luxembourg": {"zh": "卢森堡", "lat": 49.6116, "lon": 6.1319},
    "Malta": {"zh": "马耳他", "lat": 35.8989, "lon": 14.5146},
    "Cyprus": {"zh": "塞浦路斯", "lat": 35.1856, "lon": 33.3823},
    "Moldova": {"zh": "摩尔多瓦", "lat": 47.0105, "lon": 28.8638},
    "Chile": {"zh": "智利", "lat": -33.4489, "lon": -70.6693},
    "Peru": {"zh": "秘鲁", "lat": -12.0464, "lon": -77.0428},
    "Colombia": {"zh": "哥伦比亚", "lat": 4.711, "lon": -74.0721},
    "Uruguay": {"zh": "乌拉圭", "lat": -34.9011, "lon": -56.1645},
    "Paraguay": {"zh": "巴拉圭", "lat": -25.2637, "lon": -57.5759},
    "Ecuador": {"zh": "厄瓜多尔", "lat": -0.1807, "lon": -78.4678},
    "Panama": {"zh": "巴拿马", "lat": 8.9824, "lon": -79.5199},
    "Costa Rica": {"zh": "哥斯达黎加", "lat": 9.9281, "lon": -84.0907},
    "Dominican Republic": {"zh": "多米尼加", "lat": 18.4861, "lon": -69.9312},
    "Kenya": {"zh": "肯尼亚", "lat": -1.2921, "lon": 36.8219},
    "Nigeria": {"zh": "尼日利亚", "lat": 9.0765, "lon": 7.3986},
    "Ghana": {"zh": "加纳", "lat": 5.6037, "lon": -0.187},
    "Tanzania": {"zh": "坦桑尼亚", "lat": -6.163, "lon": 35.7516},
    "Ethiopia": {"zh": "埃塞俄比亚", "lat": 9.03, "lon": 38.74},
    "Algeria": {"zh": "阿尔及利亚", "lat": 36.7538, "lon": 3.0588},
    "Tunisia": {"zh": "突尼斯", "lat": 36.8065, "lon": 10.1815},
    "Jordan": {"zh": "约旦", "lat": 31.9539, "lon": 35.9106},
    "Lebanon": {"zh": "黎巴嫩", "lat": 33.8938, "lon": 35.5018},
    "Iran": {"zh": "伊朗", "lat": 35.6892, "lon": 51.389},
    "Pakistan": {"zh": "巴基斯坦", "lat": 33.6844, "lon": 73.0479},
    "Bangladesh": {"zh": "孟加拉国", "lat": 23.8103, "lon": 90.4125},
    "Sri Lanka": {"zh": "斯里兰卡", "lat": 6.9271, "lon": 79.8612},
    "Myanmar": {"zh": "缅甸", "lat": 19.7633, "lon": 96.0785},
    "Cambodia": {"zh": "柬埔寨", "lat": 11.5564, "lon": 104.9282},
    "Laos": {"zh": "老挝", "lat": 17.9757, "lon": 102.6331},
    "Mongolia": {"zh": "蒙古", "lat": 47.8864, "lon": 106.9057},
    "Kazakhstan": {"zh": "哈萨克斯坦", "lat": 51.1605, "lon": 71.4704},
    "Azerbaijan": {"zh": "阿塞拜疆", "lat": 40.4093, "lon": 49.8671},
    "Georgia": {"zh": "格鲁吉亚", "lat": 41.7151, "lon": 44.8271},
    "Armenia": {"zh": "亚美尼亚", "lat": 40.1792, "lon": 44.4991},
    "Malaysia": {"zh": "马来西亚", "lat": 3.139, "lon": 101.6869},
    "Singapore": {"zh": "新加坡", "lat": 1.3521, "lon": 103.8198},
}


def country_zh(name: str) -> str:
    """国家名 → 中文名（先规范化别名，找不到返回原名）。"""
    meta = COUNTRY_META.get(COUNTRY_ALIASES.get(name, name))
    return meta["zh"] if meta else name


def country_centroid(name: str) -> tuple[float, float] | None:
    """国家名 → 国家中心示意坐标（首都坐标），找不到返回 None。"""
    meta = COUNTRY_META.get(COUNTRY_ALIASES.get(name, name))
    if not meta:
        return None
    return meta["lat"], meta["lon"]


def country_geometric_center(name: str) -> tuple[float, float] | None:
    """国家名 → 几何中心（质心，由 Natural Earth 边界计算）。

    优先用 centroids.py（真实边界质心）；缺失时回退首都坐标。
    """
    canonical = COUNTRY_ALIASES.get(name, name)
    try:
        from .centroids import COUNTRY_GEOM_CENTERS
        center = COUNTRY_GEOM_CENTERS.get(canonical)
        if center is not None:
            return center
    except ImportError:
        pass
    return country_centroid(name)


# ---- 各国首都中文名（国家级兜底候选点显示用）----
CAPITAL_ZH: dict[str, str] = {
    "United Kingdom": "伦敦", "Ireland": "都柏林", "Germany": "柏林", "France": "巴黎",
    "Spain": "马德里", "Portugal": "里斯本", "Italy": "罗马", "Netherlands": "阿姆斯特丹",
    "Belgium": "布鲁塞尔", "Switzerland": "伯尔尼", "Austria": "维也纳", "Poland": "华沙",
    "Czechia": "布拉格", "Hungary": "布达佩斯", "Ukraine": "基辅", "Romania": "布加勒斯特",
    "Bulgaria": "索非亚", "Greece": "雅典", "Turkey": "安卡拉", "Russia": "莫斯科",
    "Sweden": "斯德哥尔摩", "Norway": "奥斯陆", "Denmark": "哥本哈根", "Finland": "赫尔辛基",
    "Iceland": "雷克雅未克", "Slovakia": "布拉迪斯拉发", "Croatia": "萨格勒布",
    "Serbia": "贝尔格莱德", "United States": "华盛顿", "Canada": "渥太华",
    "Mexico": "墨西哥城", "Brazil": "巴西利亚", "Argentina": "布宜诺斯艾利斯",
    "Australia": "堪培拉", "New Zealand": "惠灵顿", "Japan": "东京", "South Korea": "首尔",
    "China": "北京", "Taiwan": "台北", "India": "新德里", "Thailand": "曼谷",
    "Vietnam": "河内", "Indonesia": "雅加达", "Philippines": "马尼拉",
    "South Africa": "比勒陀利亚", "Morocco": "拉巴特", "Egypt": "开罗",
    "United Arab Emirates": "阿布扎比", "Israel": "耶路撒冷", "Saudi Arabia": "利雅得",
    "Belarus": "明斯克", "Latvia": "里加", "Lithuania": "维尔纽斯", "Estonia": "塔林",
    "Slovenia": "卢布尔雅那", "Luxembourg": "卢森堡市", "Malta": "瓦莱塔",
    "Cyprus": "尼科西亚", "Moldova": "基希讷乌", "Chile": "圣地亚哥", "Peru": "利马",
    "Colombia": "波哥大", "Uruguay": "蒙得维的亚", "Paraguay": "亚松森", "Ecuador": "基多",
    "Panama": "巴拿马城", "Costa Rica": "圣何塞", "Dominican Republic": "圣多明各",
    "Kenya": "内罗毕", "Nigeria": "阿布贾", "Ghana": "阿克拉", "Tanzania": "多多马",
    "Ethiopia": "亚的斯亚贝巴", "Algeria": "阿尔及尔", "Tunisia": "突尼斯市",
    "Jordan": "安曼", "Lebanon": "贝鲁特", "Iran": "德黑兰", "Pakistan": "伊斯兰堡",
    "Bangladesh": "达卡", "Sri Lanka": "科伦坡", "Myanmar": "内比都", "Cambodia": "金边",
    "Laos": "万象", "Mongolia": "乌兰巴托", "Kazakhstan": "阿斯塔纳",
    "Azerbaijan": "巴库", "Georgia": "第比利斯", "Armenia": "埃里温",
    "Malaysia": "吉隆坡", "Singapore": "新加坡",
}


def country_capital_zh(name: str) -> str:
    """国家名 → 首都中文名（找不到返回空串）。"""
    return CAPITAL_ZH.get(COUNTRY_ALIASES.get(name, name), "")


# ---- 范围过滤：中国大陆判定（除中国大陆模式用）----
# 近似矩形（含台港澳排除）。注意：矩形必然与邻国（泰国北部/老挝/缅甸/越南/巴基斯坦）
# 有重叠，因此只能作为"无国家名候选"的最后兜底；带国家名的候选一律按国家名过滤
# （见 orchestrator._filter_mainland），绝不用此矩形判定有国家名的候选。
_CN_MAINLAND_BBOX = (73.5, 18.0, 135.1, 53.6)   # lat 下限取海南岛最南端（约 18.15）
_CN_EXCLUDE = [
    # (lon_min, lat_min, lon_max, lat_max, 名称)
    (119.9, 21.8, 122.1, 25.4, "台湾"),     # 台湾岛
    (113.80, 22.10, 114.45, 22.60, "香港"),
    (113.50, 22.05, 113.65, 22.25, "澳门"),
]


def is_mainland_china(lat: float, lon: float) -> bool:
    """坐标是否位于中国大陆（不含台湾/香港/澳门）。"""
    if not (_CN_MAINLAND_BBOX[0] <= lon <= _CN_MAINLAND_BBOX[2]
            and _CN_MAINLAND_BBOX[1] <= lat <= _CN_MAINLAND_BBOX[3]):
        return False
    for x1, y1, x2, y2, _name in _CN_EXCLUDE:
        if x1 <= lon <= x2 and y1 <= lat <= y2:
            return False
    return True


# ---- 语言别名（LLM 可能输出中文/英文/简称）----
LANG_ALIASES = {
    "中文": "Chinese", "汉语": "Chinese", "普通话": "Chinese",
    "英语": "English", "英文": "English", "英语文字": "English",
    "西班牙语": "Spanish", "西班牙文": "Spanish",
    "葡萄牙语": "Portuguese", "葡语": "Portuguese",
    "法语": "French", "法文": "French",
    "德语": "German", "德文": "German",
    "意大利语": "Italian",
    "荷兰语": "Dutch",
    "波兰语": "Polish",
    "乌克兰语": "Ukrainian", "乌克兰文": "Ukrainian",
    "俄语": "Russian", "俄文": "Russian", "西里尔": "Cyrillic",
    "希腊语": "Greek",
    "阿拉伯语": "Arabic", "阿拉伯文": "Arabic",
    "希伯来语": "Hebrew",
    "日语": "Japanese", "日文": "Japanese",
    "韩语": "Korean", "朝鲜语": "Korean", "韩文": "Korean",
    "泰语": "Thai",
    "越南语": "Vietnamese",
    "土耳其语": "Turkish",
    "匈牙利语": "Hungarian",
    "捷克语": "Czech",
    "瑞典语": "Swedish",
    "丹麦语": "Danish",
    "芬兰语": "Finnish",
    "挪威语": "Norwegian",
    "冰岛语": "Icelandic",
    "印地语": "Hindi",
    "印尼语": "Indonesian",
    "菲律宾语": "Filipino",
    "克罗地亚语": "Croatian",
    "塞尔维亚语": "Serbian",
    "罗马尼亚语": "Romanian",
    "保加利亚语": "Bulgarian",
    "斯洛伐克语": "Slovak",
    "马来语": "Malay",
    "波斯语": "Persian",
    "乌尔都语": "Urdu",
    "希伯来文": "Hebrew",
    "拉丁字母": "Latin", "拉丁文": "Latin",
    "西里尔字母": "Cyrillic",
    "汉字": "Chinese", "中日韩": "Chinese",
    "天城文": "Devanagari",
    "泰文": "Thai",
    "阿拉伯字母": "Arabic",
}

# ---- 路牌关键词 → 国家（高判别力提示）----
SIGN_KEYWORDS: dict[str, list[str]] = {
    "yellow diamond": ["United States", "Canada", "Mexico", "Japan", "Australia",
                       "New Zealand", "South Africa", "Malaysia", "Thailand"],
    "yellow diamond warning": ["United States", "Canada", "Mexico", "Japan", "Australia",
                               "New Zealand", "South Africa"],
    "green motorway": ["Germany", "France", "Italy", "Austria", "Switzerland", "Czechia",
                       "Denmark", "Sweden", "Norway", "Finland", "Poland", "Romania",
                       "Bulgaria", "Greece", "Hungary", "Slovakia", "Croatia"],
    "blue motorway": ["Spain", "Netherlands", "Belgium", "United Kingdom", "Ireland",
                      "Portugal", "Turkey"],
    "blue direction sign": ["Spain", "Netherlands", "Belgium", "United Kingdom", "Ireland",
                            "Portugal", "Turkey", "United States", "Canada"],
    "yellow road sign": ["United States", "Canada", "Japan", "Mexico", "Australia",
                         "New Zealand", "South Africa"],
    "red and white bollard": ["Portugal", "Spain", "Poland", "Romania", "Brazil", "Greece"],
    "red white bollard": ["Portugal", "Spain", "Poland", "Romania", "Brazil"],
    "european union plate": ["Germany", "France", "Spain", "Italy", "Netherlands", "Belgium",
                             "Poland", "Czechia", "Hungary", "Romania", "Bulgaria", "Greece",
                             "Austria", "Slovakia", "Croatia", "Portugal", "Sweden", "Denmark",
                             "Finland"],
    "eu plate": ["Germany", "France", "Spain", "Italy", "Netherlands", "Belgium", "Poland",
                 "Czechia", "Hungary", "Romania", "Bulgaria", "Greece", "Austria", "Slovakia",
                 "Croatia", "Portugal", "Sweden", "Denmark", "Finland"],
}

# ---- 邮筒颜色 → 国家（经典 GeoGuessr 线索）----
MAILBOX_KEYWORDS: dict[str, list[str]] = {
    "red mailbox": ["United Kingdom", "Spain", "Portugal", "Brazil", "Vietnam", "Australia"],
    "red post box": ["United Kingdom", "Spain", "Portugal", "Brazil", "Vietnam"],
    "green mailbox": ["Ireland", "India"],
    "yellow mailbox": ["Germany", "France", "Hungary"],
    "blue mailbox": ["United States", "Canada"],
}

# ---- 路桩/路障颜色 → 国家（方案 3 新增维度）----
BOLLARD_KEYWORDS: dict[str, list[str]] = {
    "red and white bollard": ["Portugal", "Spain", "Poland", "Romania", "Brazil", "Greece"],
    "red white striped bollard": ["Portugal", "Spain", "Poland", "Romania", "Brazil"],
    "black and white chevron bollard": ["United Kingdom", "Ireland", "Japan", "New Zealand"],
    "black white striped bollard": ["United Kingdom", "Ireland", "Japan", "New Zealand"],
    "yellow bollard": ["United Kingdom", "Ireland", "France", "Netherlands"],
    "white bollard": ["Germany", "Switzerland", "Austria", "France", "Italy", "United States"],
    "black bollard": ["France", "Spain", "United States", "Canada"],
}

# ---- 消防栓颜色 → 国家（方案 3 新增维度）----
HYDRANT_KEYWORDS: dict[str, list[str]] = {
    "red fire hydrant": ["United States", "Canada", "Australia", "New Zealand", "France"],
    "yellow fire hydrant": ["Germany", "France", "Netherlands"],
    "green fire hydrant": ["Ireland", "United Kingdom"],
}

# ---- 电线杆样式 → 国家（经典 GeoGuessr 元线索）----
POLE_KEYWORDS: dict[str, list[str]] = {
    "wooden utility pole": ["United States", "Canada", "Australia", "New Zealand",
                            "Japan", "South Korea", "Thailand"],
    "wooden power pole": ["United States", "Canada", "Australia", "New Zealand", "Japan"],
    "tall wooden crossarm pole": ["United States", "Canada", "Japan", "South Korea"],
    "concrete power pole": ["Germany", "France", "Italy", "Spain", "Netherlands",
                            "Belgium", "Poland", "Czechia", "Hungary", "Turkey", "Brazil"],
    "galvanized steel pole": ["Netherlands", "Denmark", "Sweden", "Norway", "Finland"],
}

# ---- 道路标线 → 国家（方案 3 新增维度）----
ROADMARK_KEYWORDS: dict[str, list[str]] = {
    "yellow center line": ["United States", "Canada", "Mexico", "Japan"],
    "yellow double line": ["United States", "Canada", "Japan", "South Korea"],
    "white center line": ["Germany", "France", "Italy", "Spain", "United Kingdom",
                          "Ireland", "Netherlands", "Poland", "Czechia", "Hungary", "Ukraine"],
    "red tarmac road": ["United States", "Canada", "Australia"],
    "red curbs": ["United Kingdom", "Ireland", "Japan", "Australia"],
}

# ---- 车牌/路牌补充关键词 ----
PLATE_KEYWORDS: dict[str, list[str]] = {
    "yellow rear plate": ["United Kingdom", "Luxembourg"],
    "yellow plate": ["Netherlands", "United Kingdom", "Luxembourg", "Japan"],
    "white plate red text": ["Belgium"],
    "black plate": ["France", "Japan", "United Kingdom"],
    "mph speed limit": ["United Kingdom", "United States"],
    "kmh speed limit": ["Germany", "France", "Spain", "Italy", "Portugal", "Poland",
                        "Czechia", "Hungary", "Ukraine", "Russia", "Netherlands",
                        "Belgium", "Austria", "Switzerland", "Sweden", "Norway", "Denmark",
                        "Finland", "Turkey", "Greece", "Brazil", "Argentina", "Japan",
                        "South Korea", "China", "Australia", "New Zealand", "Canada",
                        "Mexico", "India", "Thailand", "Vietnam", "Indonesia"],
}

# ---- 驾驶侧线索词（LLM 可能用不同说法）----
DRIVING_LEFT_WORDS = ["left", "left-hand", "left hand", "左侧", "左舵", "靠左"]
DRIVING_RIGHT_WORDS = ["right", "right-hand", "right hand", "右侧", "右舵", "靠右"]
