"""国家地理-人文维度库（独立于 89 国基础库 countries.py）。

覆盖 150+ 国家，每国包含：
- 自然维度：hemisphere（阴影方向推断半球：N=北半球阴影朝北 / S=南半球朝南 / T=热带阴影近垂直）、
  climate（气候带）、vegetation（典型植被）、terrain（地形地貌）、soil（土壤颜色）
- 人文细节：bollard（路桩）、pole（电线杆）、roadmark（道路标线）等进阶线索

引擎（engine.py）把场景线索（植被/地形/土壤/阴影/路桩/电线杆/标线）与此库交叉筛选。
关键词为中文为主（LLM 输出多用中文描述），关键概念附英文。
"""
from __future__ import annotations

# 格式：{国家规范名: {维度: [关键词]}}
GEO_DIMS: dict[str, dict[str, list[str]]] = {
    # ================= 欧洲 =================
    "Norway": {"hemisphere": ["N"], "climate": ["亚寒带", "温带海洋"], "vegetation": ["针叶林", "桦木", "苔原"],
               "terrain": ["峡湾", "山地"], "soil": ["灰化土", "棕壤"], "bollard": ["白色圆杆", "反光红白"], "pole": ["木质电线杆"]},
    "Sweden": {"hemisphere": ["N"], "climate": ["亚寒带", "温带海洋"], "vegetation": ["针叶林", "桦木"],
               "terrain": ["森林丘陵", "湖泊"], "soil": ["灰化土"], "roadmark": ["黄色虚线"]},
    "Finland": {"hemisphere": ["N"], "climate": ["亚寒带"], "vegetation": ["针叶林", "桦木", "沼泽"],
                "terrain": ["湖区平原", "森林"], "soil": ["灰化土"], "pole": ["木质电线杆"]},
    "Denmark": {"hemisphere": ["N"], "climate": ["温带海洋"], "vegetation": ["落叶林", "农田"],
                "terrain": ["低平原"], "soil": ["棕壤"], "bollard": ["白色圆杆", "反光"]},
    "Iceland": {"hemisphere": ["N"], "climate": ["寒带海洋"], "vegetation": ["苔原", "矮灌丛"],
                "terrain": ["火山", "冰川", "黑沙滩"], "soil": ["火山黑土"]},
    "Ireland": {"hemisphere": ["N"], "climate": ["温带海洋"], "vegetation": ["草地", "绿野"],
                "terrain": ["低丘", "海岸"], "soil": ["棕壤"], "bollard": ["黑白条纹"]},
    "United Kingdom": {"hemisphere": ["N"], "climate": ["温带海洋"], "vegetation": ["落叶林", "草地", "石楠灌丛"],
                       "terrain": ["低丘", "海岸"], "soil": ["棕壤"], "bollard": ["红白条纹"], "pole": ["木质电线杆"], "roadmark": ["白色标线"]},
    "France": {"hemisphere": ["N"], "climate": ["温带海洋", "地中海"], "vegetation": ["落叶林", "梧桐", "松林"],
               "terrain": ["平原", "丘陵"], "soil": ["棕壤", "红土(南部)"], "bollard": ["白色圆杆", "红色反光"]},
    "Germany": {"hemisphere": ["N"], "climate": ["温带海洋", "温带大陆"], "vegetation": ["落叶林", "针叶林", "农田"],
                "terrain": ["平原", "山地"], "soil": ["棕壤", "黑土(北部)"], "bollard": ["黄色圆杆", "红白条纹"], "pole": ["混凝土电线杆"], "roadmark": ["白色标线"]},
    "Austria": {"hemisphere": ["N"], "climate": ["温带大陆", "高山"], "vegetation": ["针叶林", "落叶林", "高山草甸"],
                "terrain": ["阿尔卑斯山地", "丘陵"], "soil": ["棕壤"], "bollard": ["白色圆杆"]},
    "Switzerland": {"hemisphere": ["N"], "climate": ["温带大陆", "高山"], "vegetation": ["针叶林", "高山草甸"],
                    "terrain": ["阿尔卑斯山地"], "soil": ["棕壤"], "bollard": ["白色圆杆", "反光"]},
    "Netherlands": {"hemisphere": ["N"], "climate": ["温带海洋"], "vegetation": ["草地", "郁金香田", "农田"],
                    "terrain": ["低地平原", "圩田"], "soil": ["泥炭土", "黏土"], "bollard": ["白色圆杆", "红白"]},
    "Belgium": {"hemisphere": ["N"], "climate": ["温带海洋"], "vegetation": ["落叶林", "农田"],
                "terrain": ["低平原"], "soil": ["棕壤"], "bollard": ["白色圆杆"]},
    "Luxembourg": {"hemisphere": ["N"], "climate": ["温带海洋"], "vegetation": ["落叶林"],
                   "terrain": ["丘陵"], "soil": ["棕壤"]},
    "Poland": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["针叶林", "混交林", "农田"],
               "terrain": ["平原"], "soil": ["灰化土", "黑土"], "pole": ["木质电线杆"], "roadmark": ["白色标线"]},
    "Czechia": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["落叶林", "混交林"],
                       "terrain": ["波西米亚丘陵"], "soil": ["棕壤"], "bollard": ["白色圆杆"]},
    "Slovakia": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["落叶林", "混交林"],
                 "terrain": ["喀尔巴阡山地"], "soil": ["棕壤"]},
    "Hungary": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["草原", "农田"],
                "terrain": ["潘诺尼亚平原"], "soil": ["黑土"]},
    "Romania": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["混交林", "草原"],
                "terrain": ["喀尔巴阡山地", "平原"], "soil": ["黑土", "棕壤"]},
    "Bulgaria": {"hemisphere": ["N"], "climate": ["温带大陆", "地中海影响"], "vegetation": ["混交林", "农田"],
                 "terrain": ["巴尔干山地"], "soil": ["棕壤", "红色黏土"], "roadmark": ["橙色屋顶砖"]},
    "Serbia": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["混交林", "农田"],
               "terrain": ["丘陵", "平原"], "soil": ["黑土", "棕壤"]},
    "Croatia": {"hemisphere": ["N"], "climate": ["地中海", "温带大陆"], "vegetation": ["地中海灌丛", "松林"],
                "terrain": ["亚得里亚海岸", "山地"], "soil": ["红土", "石灰岩"]},
    "Slovenia": {"hemisphere": ["N"], "climate": ["地中海影响", "高山"], "vegetation": ["落叶林", "高山草甸"],
                 "terrain": ["尤利安山地"], "soil": ["棕壤"]},
    "Greece": {"hemisphere": ["N"], "climate": ["地中海"], "vegetation": ["橄榄树", "地中海灌丛", "柏树"],
               "terrain": ["多山", "岛屿", "海岸"], "soil": ["红土", "石灰岩"], "bollard": ["白色圆杆"]},
    "Italy": {"hemisphere": ["N"], "climate": ["地中海", "温带"], "vegetation": ["橄榄树", "柏树", "地中海灌丛"],
              "terrain": ["亚平宁山地", "海岸", "平原"], "soil": ["红土", "棕壤"], "bollard": ["白色圆杆", "红白条纹"], "pole": ["混凝土电线杆"]},
    "Spain": {"hemisphere": ["N"], "climate": ["地中海", "大陆"], "vegetation": ["橄榄树", "柑橘", "地中海灌丛"],
              "terrain": ["梅塞塔高原", "海岸", "山地"], "soil": ["红土", "黄褐土"], "bollard": ["白色圆杆"]},
    "Portugal": {"hemisphere": ["N"], "climate": ["地中海", "海洋"], "vegetation": ["橄榄树", "栓皮栎", "柑橘"],
                 "terrain": ["丘陵", "海岸"], "soil": ["红土"], "bollard": ["白色圆杆"]},
    "Ukraine": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["草原", "农田", "混交林"],
                "terrain": ["东欧平原"], "soil": ["黑土"], "pole": ["混凝土电线杆"]},
    "Belarus": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["针叶林", "沼泽"],
                "terrain": ["平原"], "soil": ["灰化土"]},
    "Lithuania": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["混交林", "农田"],
                  "terrain": ["低平原"], "soil": ["灰化土"]},
    "Latvia": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["针叶林", "混交林"],
               "terrain": ["低平原"], "soil": ["灰化土"]},
    "Estonia": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["针叶林", "沼泽"],
                "terrain": ["低平原"], "soil": ["灰化土"]},
    "Moldova": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["农田", "草原"],
                "terrain": ["丘陵"], "soil": ["黑土"]},
    "Russia": {"hemisphere": ["N"], "climate": ["亚寒带", "温带大陆"], "vegetation": ["针叶林", "苔原", "桦木"],
               "terrain": ["西伯利亚平原", "山地"], "soil": ["灰化土", "黑土"], "pole": ["木质电线杆"]},
    "Bosnia and Herzegovina": {"hemisphere": ["N"], "climate": ["大陆", "地中海影响"],
                               "vegetation": ["混交林"], "terrain": ["迪纳拉山地"], "soil": ["棕壤"]},
    "North Macedonia": {"hemisphere": ["N"], "climate": ["大陆"], "vegetation": ["混交林", "草原"],
                        "terrain": ["山地"], "soil": ["棕壤"]},
    "Montenegro": {"hemisphere": ["N"], "climate": ["地中海", "大陆"], "vegetation": ["地中海灌丛"],
                   "terrain": ["亚得里亚海岸", "山地"], "soil": ["石灰岩", "红土"]},
    "Albania": {"hemisphere": ["N"], "climate": ["地中海"], "vegetation": ["地中海灌丛", "橄榄"],
                "terrain": ["山地", "海岸"], "soil": ["石灰岩"]},
    "Malta": {"hemisphere": ["N"], "climate": ["地中海"], "vegetation": ["低矮灌丛", "仙人掌"],
              "terrain": ["石灰岩岛屿"], "soil": ["石灰岩"]},
    "Cyprus": {"hemisphere": ["N"], "climate": ["地中海"], "vegetation": ["橄榄", "柑橘", "地中海灌丛"],
               "terrain": ["特罗多斯山地", "海岸"], "soil": ["红土"]},
    "Georgia": {"hemisphere": ["N"], "climate": ["亚热带湿润", "高山"], "vegetation": ["阔叶林", "高山草甸"],
                "terrain": ["高加索山地", "黑海沿岸"], "soil": ["红土", "棕壤"]},
    "Armenia": {"hemisphere": ["N"], "climate": ["大陆性高原"], "vegetation": ["草原", "半荒漠"],
                "terrain": ["高加索山地", "高原"], "soil": ["褐土"]},
    "Azerbaijan": {"hemisphere": ["N"], "climate": ["半干旱大陆"], "vegetation": ["半荒漠", "草原"],
                   "terrain": ["里海低地", "高加索山地"], "soil": ["褐土", "盐碱土"]},
    # ================= 亚洲 =================
    "Turkey": {"hemisphere": ["N"], "climate": ["地中海", "大陆"], "vegetation": ["橄榄", "松林", "草原"],
               "terrain": ["安纳托利亚高原", "海岸"], "soil": ["红土", "褐土"]},
    "Mongolia": {"hemisphere": ["N"], "climate": ["大陆性草原", "荒漠"], "vegetation": ["草原", "戈壁灌丛"],
                 "terrain": ["蒙古高原", "戈壁"], "soil": ["栗钙土", "砂土"]},
    "Kazakhstan": {"hemisphere": ["N"], "climate": ["大陆性草原"], "vegetation": ["草原", "半荒漠"],
                   "terrain": ["中亚平原"], "soil": ["栗钙土", "黑土"]},
    "Uzbekistan": {"hemisphere": ["N"], "climate": ["大陆性荒漠"], "vegetation": ["荒漠灌丛", "绿洲农田"],
                   "terrain": ["图兰低地", "沙漠"], "soil": ["灰钙土", "盐碱土"]},
    "Turkmenistan": {"hemisphere": ["N"], "climate": ["大陆性荒漠"], "vegetation": ["荒漠灌丛"],
                     "terrain": ["卡拉库姆沙漠"], "soil": ["灰钙土"]},
    "Kyrgyzstan": {"hemisphere": ["N"], "climate": ["高山大陆"], "vegetation": ["高山草甸", "针叶林"],
                   "terrain": ["天山山地"], "soil": ["棕壤"]},
    "Tajikistan": {"hemisphere": ["N"], "climate": ["高山大陆"], "vegetation": ["高山草原", "荒漠"],
                   "terrain": ["帕米尔山地"], "soil": ["灰钙土"]},
    "Afghanistan": {"hemisphere": ["N"], "climate": ["干旱大陆"], "vegetation": ["荒漠", "山地草原"],
                    "terrain": ["兴都库什山地", "高原"], "soil": ["灰钙土", "砂土"]},
    "Pakistan": {"hemisphere": ["N"], "climate": ["干旱", "亚热带"], "vegetation": ["荒漠", "农田"],
                 "terrain": ["印度河平原", "山地"], "soil": ["冲积土", "砂土"]},
    "India": {"hemisphere": ["N"], "climate": ["热带", "亚热带"], "vegetation": ["热带季雨林", "农田", "榕树"],
              "terrain": ["德干高原", "恒河平原", "山地"], "soil": ["红土", "黑土", "冲积土"]},
    "Bangladesh": {"hemisphere": ["N"], "climate": ["热带季风"], "vegetation": ["稻田", "热带季雨林"],
                   "terrain": ["恒河三角洲低地"], "soil": ["冲积土"]},
    "Sri Lanka": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "稻田"],
                  "terrain": ["岛屿山地", "海岸"], "soil": ["红土", "砖红壤"]},
    "Nepal": {"hemisphere": ["N"], "climate": ["高山", "亚热带"], "vegetation": ["针叶林", "高山草甸", "亚热带林"],
              "terrain": ["喜马拉雅山地"], "soil": ["棕壤"]},
    "Bhutan": {"hemisphere": ["N"], "climate": ["高山", "亚热带"], "vegetation": ["针叶林", "亚热带林"],
               "terrain": ["喜马拉雅山地"], "soil": ["棕壤"]},
    "Myanmar": {"hemisphere": ["N"], "climate": ["热带季风"], "vegetation": ["热带季雨林", "稻田"],
                "terrain": ["伊洛瓦底平原", "山地"], "soil": ["红土", "冲积土"]},
    "Laos": {"hemisphere": ["N"], "climate": ["热带季风"], "vegetation": ["热带季雨林", "竹林"],
             "terrain": ["山地高原"], "soil": ["红土"]},
    "Cambodia": {"hemisphere": ["N"], "climate": ["热带季风"], "vegetation": ["热带季雨林", "稻田"],
                 "terrain": ["湄公河平原", "低山"], "soil": ["红土", "冲积土"]},
    "Thailand": {"hemisphere": ["N"], "climate": ["热带季风"], "vegetation": ["热带季雨林", "稻田", "棕榈"],
                 "terrain": ["湄南河平原", "北部山地"], "soil": ["红土", "冲积土"]},
    "Malaysia": {"hemisphere": ["N"], "climate": ["热带雨林"], "vegetation": ["热带雨林", "油棕", "橡胶树"],
                 "terrain": ["半岛山地", "海岸"], "soil": ["红土", "砖红壤"]},
    "Singapore": {"hemisphere": ["N"], "climate": ["热带雨林"], "vegetation": ["热带雨林", "棕榈"],
                  "terrain": ["低地岛屿"], "soil": ["红土"]},
    "Brunei": {"hemisphere": ["N"], "climate": ["热带雨林"], "vegetation": ["热带雨林", "红树林"],
               "terrain": ["沿海平原"], "soil": ["红土"]},
    "Philippines": {"hemisphere": ["N"], "climate": ["热带季风"], "vegetation": ["热带雨林", "稻田", "椰林"],
                    "terrain": ["群岛山地"], "soil": ["火山土", "红土"]},
    "Indonesia": {"hemisphere": ["S", "T"], "climate": ["热带雨林", "热带季风"], "vegetation": ["热带雨林", "椰林", "稻田"],
                  "terrain": ["群岛火山山地"], "soil": ["火山土", "红土"], "bollard": ["混凝土方块"]},
    "East Timor": {"hemisphere": ["S"], "climate": ["热带"], "vegetation": ["热带草原", "椰林"],
                   "terrain": ["山地岛屿"], "soil": ["红土"]},
    "Vietnam": {"hemisphere": ["N"], "climate": ["热带季风", "亚热带"], "vegetation": ["稻田", "热带季雨林", "红树林"],
                "terrain": ["红河平原", "山地"], "soil": ["红土", "冲积土"]},
    "Saudi Arabia": {"hemisphere": ["N"], "climate": ["热带荒漠"], "vegetation": ["荒漠灌丛", "绿洲棕榈"],
                     "terrain": ["沙漠", "高原"], "soil": ["砂土", "红色砂土"]},
    "Yemen": {"hemisphere": ["N"], "climate": ["热带荒漠", "山地"], "vegetation": ["荒漠", "山地灌丛"],
              "terrain": ["山地高原", "沙漠"], "soil": ["砂土", "褐土"]},
    "Oman": {"hemisphere": ["N"], "climate": ["热带荒漠"], "vegetation": ["荒漠", "绿洲"],
             "terrain": ["沙漠", "山地", "海岸"], "soil": ["砂土"]},
    "United Arab Emirates": {"hemisphere": ["N"], "climate": ["热带荒漠"], "vegetation": ["荒漠", "绿洲棕榈"],
                             "terrain": ["沙漠", "海岸"], "soil": ["砂土"]},
    "Qatar": {"hemisphere": ["N"], "climate": ["热带荒漠"], "vegetation": ["荒漠"],
              "terrain": ["沙漠半岛"], "soil": ["砂土"]},
    "Bahrain": {"hemisphere": ["N"], "climate": ["热带荒漠"], "vegetation": ["荒漠"],
                "terrain": ["沙漠岛屿"], "soil": ["砂土"]},
    "Kuwait": {"hemisphere": ["N"], "climate": ["热带荒漠"], "vegetation": ["荒漠"],
               "terrain": ["沙漠平原"], "soil": ["砂土"]},
    "Iraq": {"hemisphere": ["N"], "climate": ["干旱大陆"], "vegetation": ["荒漠", "绿洲"],
             "terrain": ["美索不达米亚平原", "沙漠"], "soil": ["冲积土", "盐碱土"]},
    "Iran": {"hemisphere": ["N"], "climate": ["干旱大陆"], "vegetation": ["荒漠", "山地灌丛"],
             "terrain": ["伊朗高原", "扎格罗斯山地"], "soil": ["灰钙土", "褐土"]},
    "Syria": {"hemisphere": ["N"], "climate": ["地中海", "干旱"], "vegetation": ["地中海灌丛", "荒漠"],
              "terrain": ["沿海平原", "高原"], "soil": ["褐土", "砂土"]},
    "Lebanon": {"hemisphere": ["N"], "climate": ["地中海"], "vegetation": ["橄榄", "雪松", "地中海灌丛"],
                "terrain": ["山地", "海岸"], "soil": ["红土", "石灰岩"]},
    "Jordan": {"hemisphere": ["N"], "climate": ["干旱"], "vegetation": ["荒漠", "地中海灌丛(北部)"],
               "terrain": ["高原", "死海低地"], "soil": ["砂土", "褐土"]},
    "Israel": {"hemisphere": ["N"], "climate": ["地中海", "干旱"], "vegetation": ["橄榄", "柑橘", "荒漠"],
               "terrain": ["海岸平原", "内盖夫沙漠"], "soil": ["红土", "砂土"]},
    "Palestine": {"hemisphere": ["N"], "climate": ["地中海"], "vegetation": ["橄榄", "柑橘"],
                  "terrain": ["山地", "海岸"], "soil": ["红土", "石灰岩"]},
    "Japan": {"hemisphere": ["N"], "climate": ["温带", "亚热带"], "vegetation": ["针叶林", "落叶林", "竹林"],
              "terrain": ["多山", "岛屿"], "soil": ["火山土", "棕壤"], "pole": ["木质电线杆", "混凝土"], "roadmark": ["白色标线"]},
    "South Korea": {"hemisphere": ["N"], "climate": ["温带"], "vegetation": ["落叶林", "针叶林"],
                    "terrain": ["多山"], "soil": ["棕壤", "红壤"], "pole": ["混凝土电线杆"]},
    "North Korea": {"hemisphere": ["N"], "climate": ["温带大陆"], "vegetation": ["落叶林", "针叶林"],
                    "terrain": ["多山"], "soil": ["棕壤"]},
    "China": {"hemisphere": ["N"], "climate": ["温带", "亚热带", "高原"], "vegetation": ["温带落叶林", "亚热带常绿林", "草原", "荒漠"],
              "terrain": ["高原", "平原", "山地", "盆地"], "soil": ["黄土", "红壤", "黑土"], "pole": ["混凝土电线杆"]},
    "Taiwan": {"hemisphere": ["N"], "climate": ["亚热带"], "vegetation": ["亚热带常绿林", "竹林"],
               "terrain": ["山地", "平原"], "soil": ["红壤"]},
    "Hong Kong": {"hemisphere": ["N"], "climate": ["亚热带"], "vegetation": ["亚热带常绿林"],
                  "terrain": ["山地海岸"], "soil": ["红壤"]},
    "Macau": {"hemisphere": ["N"], "climate": ["亚热带"], "vegetation": ["亚热带常绿林"],
              "terrain": ["半岛低地"], "soil": ["红壤"]},
    # ================= 非洲 =================
    "Egypt": {"hemisphere": ["N"], "climate": ["热带荒漠"], "vegetation": ["荒漠", "尼罗河绿洲"],
              "terrain": ["沙漠", "尼罗河谷地"], "soil": ["砂土", "冲积土"]},
    "Libya": {"hemisphere": ["N"], "climate": ["热带荒漠"], "vegetation": ["荒漠"],
              "terrain": ["撒哈拉沙漠"], "soil": ["砂土"]},
    "Algeria": {"hemisphere": ["N"], "climate": ["地中海(北)", "荒漠"], "vegetation": ["地中海灌丛", "荒漠"],
                "terrain": ["阿特拉斯山地", "撒哈拉"], "soil": ["砂土", "红土"]},
    "Tunisia": {"hemisphere": ["N"], "climate": ["地中海"], "vegetation": ["橄榄", "地中海灌丛"],
                "terrain": ["丘陵海岸", "撒哈拉边缘"], "soil": ["红土", "砂土"]},
    "Morocco": {"hemisphere": ["N"], "climate": ["地中海", "荒漠"], "vegetation": ["橄榄", "阿特拉斯雪松", "荒漠灌丛"],
                "terrain": ["阿特拉斯山地", "海岸"], "soil": ["红土", "砂土"]},
    "Mauritania": {"hemisphere": ["N"], "climate": ["荒漠"], "vegetation": ["荒漠"],
                   "terrain": ["撒哈拉", "萨赫勒"], "soil": ["砂土"]},
    "Mali": {"hemisphere": ["N"], "climate": ["荒漠", "萨赫勒"], "vegetation": ["荒漠", "稀树草原"],
             "terrain": ["萨赫勒平原"], "soil": ["砂土", "红土"]},
    "Niger": {"hemisphere": ["N"], "climate": ["荒漠", "萨赫勒"], "vegetation": ["荒漠", "稀树草原"],
              "terrain": ["撒哈拉", "高原"], "soil": ["砂土"]},
    "Chad": {"hemisphere": ["N"], "climate": ["荒漠", "萨赫勒"], "vegetation": ["荒漠", "稀树草原"],
             "terrain": ["乍得盆地"], "soil": ["砂土", "黑钙土"]},
    "Sudan": {"hemisphere": ["N"], "climate": ["荒漠", "萨赫勒", "热带"], "vegetation": ["荒漠", "稀树草原"],
              "terrain": ["尼罗河谷", "平原"], "soil": ["砂土", "红土"]},
    "South Sudan": {"hemisphere": ["N"], "climate": ["热带", "萨赫勒"], "vegetation": ["稀树草原", "热带草原"],
                    "terrain": ["平原"], "soil": ["红土"]},
    "Ethiopia": {"hemisphere": ["N"], "climate": ["热带高原"], "vegetation": ["山地草原", "稀树草原"],
                 "terrain": ["埃塞俄比亚高原"], "soil": ["红土", "火山土"]},
    "Eritrea": {"hemisphere": ["N"], "climate": ["干旱热带"], "vegetation": ["荒漠", "山地灌丛"],
                "terrain": ["红海海岸", "高原"], "soil": ["砂土", "褐土"]},
    "Djibouti": {"hemisphere": ["N"], "climate": ["荒漠"], "vegetation": ["荒漠灌丛"],
                 "terrain": ["火山低地"], "soil": ["砂土"]},
    "Somalia": {"hemisphere": ["N"], "climate": ["干旱热带"], "vegetation": ["荒漠", "稀树草原"],
                "terrain": ["低高原", "海岸"], "soil": ["砂土", "红土"]},
    "Kenya": {"hemisphere": ["S", "N"], "climate": ["热带"], "vegetation": ["稀树草原", "金合欢"],
              "terrain": ["东非高原", "大裂谷"], "soil": ["红土", "火山土"]},
    "Tanzania": {"hemisphere": ["S"], "climate": ["热带"], "vegetation": ["稀树草原", "热带雨林(局部)"],
                 "terrain": ["东非高原", "乞力马扎罗"], "soil": ["红土"]},
    "Uganda": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["稀树草原", "热带雨林"],
               "terrain": ["高原", "湖区"], "soil": ["红土"]},
    "Rwanda": {"hemisphere": ["S"], "climate": ["热带高原"], "vegetation": ["绿丘", "香蕉园"],
               "terrain": ["千丘之国"], "soil": ["红土"]},
    "Burundi": {"hemisphere": ["S"], "climate": ["热带高原"], "vegetation": ["绿丘", "香蕉园"],
                "terrain": ["高原"], "soil": ["红土"]},
    "Democratic Republic of the Congo": {"hemisphere": ["S", "N"], "climate": ["热带雨林"],
                                         "vegetation": ["热带雨林", "刚果盆地"], "terrain": ["刚果盆地低地"],
                                         "soil": ["红土", "砖红壤"]},
    "Congo": {"hemisphere": ["S"], "climate": ["热带雨林"], "vegetation": ["热带雨林"],
              "terrain": ["刚果盆地"], "soil": ["红土"]},
    "Gabon": {"hemisphere": ["S"], "climate": ["热带雨林"], "vegetation": ["热带雨林"],
              "terrain": ["沿海平原"], "soil": ["红土"]},
    "Cameroon": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "稀树草原"],
                 "terrain": ["山地", "平原"], "soil": ["红土", "火山土"]},
    "Nigeria": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["稀树草原", "热带雨林", "农田"],
                "terrain": ["平原", "乔斯高原"], "soil": ["红土"]},
    "Ghana": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["稀树草原", "热带雨林", "可可园"],
              "terrain": ["沿海平原", "高原"], "soil": ["红土"]},
    "Ivory Coast": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "稀树草原"],
                    "terrain": ["沿海平原"], "soil": ["红土"]},
    "Senegal": {"hemisphere": ["N"], "climate": ["萨赫勒", "热带"], "vegetation": ["稀树草原", "猴面包树"],
                "terrain": ["平原"], "soil": ["砂土", "红土"]},
    "Burkina Faso": {"hemisphere": ["N"], "climate": ["萨赫勒"], "vegetation": ["稀树草原"],
                     "terrain": ["高原"], "soil": ["红土", "砂土"]},
    "Benin": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["稀树草原", "红树林"],
              "terrain": ["沿海平原"], "soil": ["红土"]},
    "Togo": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["稀树草原"],
             "terrain": ["高原"], "soil": ["红土"]},
    "Guinea": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "稀树草原"],
               "terrain": ["富塔贾隆高原"], "soil": ["红土"]},
    "Sierra Leone": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "红树林"],
                     "terrain": ["沿海平原"], "soil": ["红土"]},
    "Liberia": {"hemisphere": ["N"], "climate": ["热带雨林"], "vegetation": ["热带雨林"],
                "terrain": ["沿海平原"], "soil": ["红土"]},
    "Central African Republic": {"hemisphere": ["N"], "climate": ["热带"],
                                 "vegetation": ["热带雨林", "稀树草原"], "terrain": ["高原"],
                                 "soil": ["红土"]},
    "Angola": {"hemisphere": ["S"], "climate": ["热带", "高原"], "vegetation": ["稀树草原", "森林草原"],
               "terrain": ["高原"], "soil": ["红土"]},
    "Zambia": {"hemisphere": ["S"], "climate": ["热带高原"], "vegetation": ["稀树草原", "miombo林"],
               "terrain": ["高原"], "soil": ["红土"]},
    "Zimbabwe": {"hemisphere": ["S"], "climate": ["热带高原"], "vegetation": ["稀树草原"],
                 "terrain": ["高原"], "soil": ["红土"]},
    "Mozambique": {"hemisphere": ["S"], "climate": ["热带"], "vegetation": ["稀树草原", "红树林"],
                   "terrain": ["沿海低地"], "soil": ["红土"]},
    "Malawi": {"hemisphere": ["S"], "climate": ["热带"], "vegetation": ["稀树草原"],
               "terrain": ["马拉维湖裂谷"], "soil": ["红土"]},
    "Namibia": {"hemisphere": ["S"], "climate": ["荒漠", "半干旱"], "vegetation": ["纳米布沙漠", "稀树草原"],
                "terrain": ["沙漠海岸", "高原"], "soil": ["砂土", "红色砂土"]},
    "Botswana": {"hemisphere": ["S"], "climate": ["半干旱"], "vegetation": ["稀树草原", "卡拉哈里灌丛"],
                 "terrain": ["卡拉哈里盆地"], "soil": ["砂土", "红土"]},
    "South Africa": {"hemisphere": ["S"], "climate": ["地中海(西南)", "亚热带", "半干旱"],
                     "vegetation": ["稀树草原", "金合欢", "地中海灌丛"], "terrain": ["高原", "德拉肯斯山地"],
                     "soil": ["红土", "黄壤"]},
    "Lesotho": {"hemisphere": ["S"], "climate": ["高山"], "vegetation": ["高山草原"],
                "terrain": ["德拉肯斯山地"], "soil": ["红土"]},
    "Eswatini": {"hemisphere": ["S"], "climate": ["亚热带"], "vegetation": ["稀树草原"],
                 "terrain": ["丘陵"], "soil": ["红土"]},
    "Madagascar": {"hemisphere": ["S"], "climate": ["热带"], "vegetation": ["猴面包树", "热带旱林", "雨林"],
                   "terrain": ["高原", "海岸"], "soil": ["红土", "砖红壤"]},
    "Mauritius": {"hemisphere": ["S"], "climate": ["热带海洋"], "vegetation": ["甘蔗田", "热带林"],
                  "terrain": ["火山岛屿"], "soil": ["火山土"]},
    "Tunisia": {"hemisphere": ["N"], "climate": ["地中海"], "vegetation": ["橄榄", "地中海灌丛"],
                "terrain": ["丘陵海岸"], "soil": ["红土"]},
    # ================= 北美洲 =================
    "United States": {"hemisphere": ["N"], "climate": ["温带", "亚热带", "荒漠", "大陆"],
                      "vegetation": ["落叶林", "针叶林", "荒漠灌丛", "草原"], "terrain": ["平原", "山地", "沙漠", "海岸"],
                      "soil": ["棕壤", "黑土", "红土"], "bollard": ["黄色/白色方形"], "pole": ["木质电线杆", "混凝土"], "roadmark": ["黄线中心线"]},
    "Canada": {"hemisphere": ["N"], "climate": ["亚寒带", "温带"], "vegetation": ["针叶林", "落叶林", "苔原"],
               "terrain": ["平原", "落基山地", "湖群"], "soil": ["灰化土"], "pole": ["木质电线杆"]},
    "Mexico": {"hemisphere": ["N"], "climate": ["热带", "干旱", "高山"], "vegetation": ["仙人掌", "荒漠灌丛", "热带林"],
               "terrain": ["高原", "山地", "沙漠"], "soil": ["红土", "灰钙土"]},
    "Guatemala": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "咖啡园"],
                  "terrain": ["火山高地"], "soil": ["火山土"]},
    "Honduras": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "稀树草原"],
                 "terrain": ["山地"], "soil": ["红土"]},
    "El Salvador": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带林"],
                    "terrain": ["火山山地"], "soil": ["火山土"]},
    "Nicaragua": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "稀树草原"],
                  "terrain": ["湖区", "山地"], "soil": ["火山土"]},
    "Costa Rica": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "咖啡园"],
                   "terrain": ["火山山地"], "soil": ["火山土"]},
    "Panama": {"hemisphere": ["N"], "climate": ["热带雨林"], "vegetation": ["热带雨林"],
               "terrain": ["地峡山地"], "soil": ["红土"]},
    "Cuba": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["棕榈", "甘蔗田"],
             "terrain": ["平原", "山地"], "soil": ["红土"]},
    "Dominican Republic": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["棕榈", "热带林"],
                           "terrain": ["山地海岸"], "soil": ["红土"]},
    "Haiti": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带林"],
              "terrain": ["山地"], "soil": ["红土"]},
    "Jamaica": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["棕榈", "热带林"],
                "terrain": ["山地岛屿"], "soil": ["红土"]},
    "Belize": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "红树林"],
               "terrain": ["沿海低地"], "soil": ["红土"]},
    "Bahamas": {"hemisphere": ["N"], "climate": ["热带海洋"], "vegetation": ["棕榈", "低灌丛"],
                "terrain": ["珊瑚岛礁"], "soil": ["砂土"]},
    # ================= 南美洲 =================
    "Brazil": {"hemisphere": ["S", "T"], "climate": ["热带", "亚热带"], "vegetation": ["热带雨林", "稀树草原", "大西洋雨林"],
               "terrain": ["亚马逊盆地", "巴西高原"], "soil": ["红土", "砖红壤"]},
    "Argentina": {"hemisphere": ["S"], "climate": ["温带", "半干旱", "巴塔哥尼亚"], "vegetation": ["潘帕斯草原", "荒漠灌丛"],
                  "terrain": ["潘帕斯平原", "安第斯山地", "巴塔哥尼亚高原"], "soil": ["黑土", "棕壤"]},
    "Chile": {"hemisphere": ["S"], "climate": ["荒漠", "地中海", "温带"], "vegetation": ["阿塔卡马荒漠", "地中海灌丛", "针叶林"],
              "terrain": ["安第斯山地", "海岸山脉", "沙漠"], "soil": ["砂土", "红土"]},
    "Peru": {"hemisphere": ["S"], "climate": ["干旱海岸", "热带", "高山"], "vegetation": ["荒漠", "热带雨林", "高山草原"],
             "terrain": ["安第斯山地", "亚马逊低地", "海岸沙漠"], "soil": ["砂土", "红土"]},
    "Colombia": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林", "高山草原", "咖啡园"],
                 "terrain": ["安第斯山地", "亚马逊低地"], "soil": ["红土", "火山土"]},
    "Venezuela": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带草原", "热带雨林"],
                  "terrain": ["平原", "圭亚那高地"], "soil": ["红土"]},
    "Ecuador": {"hemisphere": ["S"], "climate": ["热带", "高山"], "vegetation": ["热带雨林", "高山草原"],
                "terrain": ["安第斯山地", "亚马逊低地"], "soil": ["火山土", "红土"]},
    "Bolivia": {"hemisphere": ["S"], "climate": ["高原", "热带"], "vegetation": ["高原草原", "热带林"],
                "terrain": ["安第斯高原"], "soil": ["褐土", "红土"]},
    "Paraguay": {"hemisphere": ["S"], "climate": ["亚热带"], "vegetation": ["草原", "森林"],
                 "terrain": ["平原"], "soil": ["红土"]},
    "Uruguay": {"hemisphere": ["S"], "climate": ["温带"], "vegetation": ["草原"],
                "terrain": ["低丘平原"], "soil": ["黑土"]},
    "Guyana": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林"],
               "terrain": ["沿海低地"], "soil": ["红土"]},
    "Suriname": {"hemisphere": ["N"], "climate": ["热带"], "vegetation": ["热带雨林"],
                 "terrain": ["沿海低地"], "soil": ["红土"]},
    # ================= 大洋洲 =================
    "Australia": {"hemisphere": ["S"], "climate": ["荒漠", "热带", "温带", "地中海(西南)"],
                  "vegetation": ["桉树林", "荒漠灌丛", "草原", "热带草原"], "terrain": ["内陆沙漠", "沿海平原", "大分水岭"],
                  "soil": ["红土", "砂土"]},
    "New Zealand": {"hemisphere": ["S"], "climate": ["温带海洋"], "vegetation": ["针叶林", "草地", "蕨类"],
                    "terrain": ["南阿尔卑斯山地", "丘陵"], "soil": ["棕壤"]},
    "Papua New Guinea": {"hemisphere": ["S"], "climate": ["热带雨林"], "vegetation": ["热带雨林"],
                         "terrain": ["山地", "低地"], "soil": ["红土"]},
    "Fiji": {"hemisphere": ["S"], "climate": ["热带海洋"], "vegetation": ["椰林", "热带林"],
             "terrain": ["火山岛屿"], "soil": ["火山土"]},
    "Solomon Islands": {"hemisphere": ["S"], "climate": ["热带海洋"], "vegetation": ["热带雨林"],
                        "terrain": ["火山岛"], "soil": ["红土"]},
    "Vanuatu": {"hemisphere": ["S"], "climate": ["热带海洋"], "vegetation": ["热带林"],
                "terrain": ["火山岛"], "soil": ["火山土"]},
    "Samoa": {"hemisphere": ["S"], "climate": ["热带海洋"], "vegetation": ["椰林", "热带林"],
              "terrain": ["火山岛"], "soil": ["火山土"]},
    "Tonga": {"hemisphere": ["S"], "climate": ["热带海洋"], "vegetation": ["椰林"],
              "terrain": ["珊瑚岛"], "soil": ["砂土"]},
    "Federated States of Micronesia": {"hemisphere": ["N"], "climate": ["热带海洋"],
                                       "vegetation": ["椰林", "红树林"], "terrain": ["环礁"],
                                       "soil": ["砂土"]},
    "Marshall Islands": {"hemisphere": ["N"], "climate": ["热带海洋"], "vegetation": ["椰林"],
                         "terrain": ["环礁"], "soil": ["砂土"]},
    "Palau": {"hemisphere": ["N"], "climate": ["热带海洋"], "vegetation": ["热带林"],
              "terrain": ["石灰岩岛"], "soil": ["砂土"]},
    "Kiribati": {"hemisphere": ["S"], "climate": ["热带海洋"], "vegetation": ["椰林"],
                 "terrain": ["环礁"], "soil": ["砂土"]},
    "Nauru": {"hemisphere": ["S"], "climate": ["热带海洋"], "vegetation": ["椰林"],
              "terrain": ["珊瑚岛"], "soil": ["砂土"]},
    "Tuvalu": {"hemisphere": ["S"], "climate": ["热带海洋"], "vegetation": ["椰林"],
               "terrain": ["环礁"], "soil": ["砂土"]},
    # 补充：美洲其他国家/中东边缘
    "Falkland Islands": {"hemisphere": ["S"], "climate": ["寒带海洋"], "vegetation": ["苔原", "草丛"],
                         "terrain": ["丘陵群岛"], "soil": ["泥炭土"]},
    "New Caledonia": {"hemisphere": ["S"], "climate": ["热带海洋"], "vegetation": ["热带草原", "雨林"],
                      "terrain": ["山地岛"], "soil": ["红土"]},
    "Greenland": {"hemisphere": ["N"], "climate": ["极地"], "vegetation": ["苔原"],
                  "terrain": ["冰原", "峡湾"], "soil": ["冻土"]},
}

# 国家数
def count() -> int:
    return len(GEO_DIMS)
