"""世界城市特征档案（LLM 批量生成，人口 Top300 非中国城市）。
由 scripts/gen_city_profiles.py 生成 → scripts/json_to_py.py 转换，勿手改。
"""
from __future__ import annotations

WORLD_CITY_PROFILES: list[dict] = [
    {
        "en": 'Tokyo', "zh": '东京', "country": 'Japan',
        "lat": 35.68696, "lon": 139.74946,
        "keywords": [
            "东京塔",
            "浅草寺",
            "东京晴空塔",
            "自动售货机",
            "新宿繁华商业街",
            "章鱼小丸子",
            "涩谷十字路口",
        ],
    },
    {
        "en": 'New York', "zh": '纽约', "country": 'United States',
        "lat": 40.72156, "lon": -73.99572,
        "keywords": [
            "帝国大厦",
            "自由女神像",
            "时代广场",
            "黄色出租车",
            "纽约风格披萨",
            "曼哈顿网格状街道",
            "百老汇剧院",
        ],
    },
    {
        "en": 'Mexico City', "zh": '墨西哥城', "country": 'Mexico',
        "lat": 19.44439, "lon": -99.13293,
        "keywords": [
            "墨西哥国家宫",
            "查普尔特佩克城堡",
            "西班牙殖民风格石拱门建筑",
            "阿兹特克太阳金字塔",
            "玉米饼摊位",
            "高原气候下的仙人掌植被",
            "西班牙语路牌",
        ],
    },
    {
        "en": 'Mumbai', "zh": '孟买', "country": 'India',
        "lat": 19.06841, "lon": 72.87584,
        "keywords": [
            "Gateway of India",
            "维多利亚女王大厦",
            "阿拉伯海沿岸街道",
            "密集的电线杆",
            "vada pav",
            "棕榈树环绕的热带街道",
            "印地语文字招牌",
        ],
    },
    {
        "en": 'São Paulo', "zh": '圣保罗', "country": 'Brazil',
        "lat": -23.55673, "lon": -46.62697,
        "keywords": [
            "伊比拉普埃拉公园",
            "圣保罗大教堂",
            "Paulista Avenue摩天大楼",
            "巴西SP车牌",
            "街头烤肉摊",
            "宽幅林荫大道",
            "亚热带城市绿植",
            "葡萄牙语路牌",
        ],
    },
    {
        "en": 'Delhi', "zh": '德里', "country": 'India',
        "lat": 28.67194, "lon": 77.22806,
        "keywords": [
            "红堡",
            "印度门",
            "德里老城区狭窄街道",
            "殖民时期议会大厦周边建筑",
            "贾玛清真寺巨大圆顶",
            "德里城墙遗迹",
        ],
    },
    {
        "en": 'Kolkata', "zh": '加尔各答', "country": 'India',
        "lat": 22.56958, "lon": 88.36913,
        "keywords": [
            "豪拉大桥",
            "胡格利河",
            "塔塔纪念堂",
            "圣保罗大教堂",
            "加尔各答烤鱼摊",
            "殖民时期石板路",
            "孟加拉语招牌",
            "黄包车",
        ],
    },
    {
        "en": 'Dhaka', "zh": '达卡', "country": 'Bangladesh',
        "lat": 23.72501, "lon": 90.40663,
        "keywords": [
            "竹编屋顶木结构民居群",
            "帕德玛河沿岸木船",
            "狭窄电线交错街道",
            "街头小吃摊（Chotpoti）",
            "密集棚户区建筑",
            "人力三轮车（Rickshaw）与摩托车混行",
            "传统木结构市场摊位",
        ],
    },
    {
        "en": 'Buenos Aires', "zh": '布宜诺斯艾利斯', "country": 'Argentina',
        "lat": -34.61071, "lon": -58.43251,
        "keywords": [
            "科隆剧院",
            "9月7日大道",
            "玫瑰宫",
            "欧洲风格联排建筑",
            "马黛茶",
            "宽幅林荫大道",
        ],
    },
    {
        "en": 'Los Angeles', "zh": '洛杉矶', "country": 'United States',
        "lat": 34.04922, "lon": -118.23199,
        "keywords": [
            "好莱坞星光大道的星星",
            "比弗利山庄的豪华住宅",
            "棕榈树成行的街道",
            "TCL中国剧院",
            "加州阳光下的复古汽车",
            "墨西哥风味街头小吃摊",
            "格里菲斯天文台观景台",
        ],
    },
    {
        "en": 'Karachi', "zh": '卡拉奇', "country": 'Pakistan',
        "lat": 24.87194, "lon": 66.98806,
        "keywords": [
            "Clifton Beach",
            "沿海棕榈树街道",
            "低层殖民风格建筑",
            "Karachi Port港口",
            "Biryani街头小吃摊",
            "热带沿海潮湿街景",
            "三轮车沿海行驶",
        ],
    },
    {
        "en": 'Cairo', "zh": '开罗', "country": 'Egypt',
        "lat": 30.05191, "lon": 31.24802,
        "keywords": [
            "吉萨金字塔群",
            "尼罗河沿岸",
            "穆罕默德·阿里清真寺",
            "伊斯兰尖塔",
            "沙漠边缘景观",
            "骆驼",
            "尼罗河船只",
            "马木路克风格建筑",
        ],
    },
    {
        "en": 'Rio de Janeiro', "zh": '里约热内卢', "country": 'Brazil',
        "lat": -22.90731, "lon": -43.21212,
        "keywords": [
            "基督像",
            "科帕卡巴纳海滩",
            "热带棕榈树",
            "桑巴舞者",
            "瓜纳巴拉湾",
            "殖民风格石砌建筑",
        ],
    },
    {
        "en": 'Ōsaka', "zh": 'Ōsaka', "country": 'Japan',
        "lat": 34.69109, "lon": 135.50375,
        "keywords": [
            "道顿堀鳗鱼烧招牌",
            "心斋桥拱门",
            "大阪城天守阁",
            "章鱼烧摊位",
            "道顿堀红色霓虹",
            "大阪的木造拱廊街",
        ],
    },
    {
        "en": 'Manila', "zh": '马尼拉', "country": 'Philippines',
        "lat": 14.6061, "lon": 120.98027,
        "keywords": [
            "马尼拉大教堂",
            "马尼拉湾",
            "halo-halo",
            "西班牙殖民风格建筑",
            "罗哈斯大道",
            "三轮车",
            "热带植被中的椰子树",
        ],
    },
    {
        "en": 'Moscow', "zh": '莫斯科', "country": 'Russia',
        "lat": 55.75411, "lon": 37.61358,
        "keywords": [
            "克里姆林宫",
            "圣瓦西里大教堂",
            "莫斯科河",
            "红场",
            "克里姆林宫城墙",
            "红砖建筑",
            "冬季积雪覆盖的克里姆林宫",
        ],
    },
    {
        "en": 'Istanbul', "zh": '伊斯坦布尔', "country": 'Turkey',
        "lat": 41.0176, "lon": 28.97428,
        "keywords": [
            "博斯普鲁斯海峡",
            "加拉塔塔",
            "圣索菲亚大教堂",
            "蓝色清真寺",
            "托普卡帕宫",
            "金角湾",
            "奥斯曼风格宣礼塔",
            "狭窄奥斯曼街道",
        ],
    },
    {
        "en": 'Paris', "zh": '巴黎', "country": 'France',
        "lat": 48.85809, "lon": 2.35299,
        "keywords": [
            "埃菲尔铁塔",
            "塞纳河",
            "卢浮宫",
            "巴黎圣母院",
            "香榭丽舍大街",
            "法棍",
            "可颂",
        ],
    },
    {
        "en": 'Seoul', "zh": '首尔', "country": 'South Korea',
        "lat": 37.56829, "lon": 126.99778,
        "keywords": [
            "首尔塔",
            "景福宫",
            "北村韩屋村",
            "明洞",
            "汉江",
            "韩文地铁标识",
            "地铁入口",
            "梨花女子大学",
        ],
    },
    {
        "en": 'Lagos', "zh": '拉各斯', "country": 'Nigeria',
        "lat": 6.44521, "lon": 3.38958,
        "keywords": [
            "维多利亚岛",
            "基基车",
            "沿海高层建筑群",
            "热带棕榈树",
            "街头小贩摊位",
            "沿海街道",
            "殖民时期遗留建筑",
        ],
    },
    {
        "en": 'Jakarta', "zh": '雅加达', "country": 'Indonesia',
        "lat": -6.17247, "lon": 106.82749,
        "keywords": [
            "独立纪念碑（Monas）",
            "荷兰殖民风格红砖建筑",
            "摩托车流",
            "热带棕榈树",
            "梭罗河沿岸",
            "印尼炒饭",
        ],
    },
    {
        "en": 'Chicago', "zh": '芝加哥', "country": 'United States',
        "lat": 41.84796, "lon": -87.63524,
        "keywords": [
            "Willis Tower",
            "Chicago River",
            "Navy Pier",
            "Magnificent Mile",
            "Wrigley Field",
            "Michigan Lake Shoreline",
            "Chicago School of Architecture",
        ],
    },
    {
        "en": 'London', "zh": '伦敦', "country": 'United Kingdom',
        "lat": 51.50194, "lon": -0.11867,
        "keywords": [
            "大本钟",
            "红色双层巴士",
            "泰晤士河",
            "黑色出租车",
            "伦敦眼",
            "红色电话亭",
            "圣保罗大教堂",
            "碎片大厦",
        ],
    },
    {
        "en": 'Lima', "zh": '利马', "country": 'Peru',
        "lat": -12.04607, "lon": -77.05201,
        "keywords": [
            "圣弗朗西斯科教堂",
            "殖民时期石砌建筑",
            "狭窄石板街道",
            "拱形门廊",
            "红瓦屋顶",
            "老城区石拱门",
            "西班牙殖民风格建筑",
        ],
    },
    {
        "en": 'Tehran', "zh": '德黑兰', "country": 'Iran',
        "lat": 35.67389, "lon": 51.4224,
        "keywords": [
            "阿扎迪广场",
            "自由塔",
            "伊斯兰圆顶清真寺",
            "德黑兰出租车",
            "Farsi文字标识",
            "干燥街道与稀疏植被",
            "拱券与尖塔建筑",
        ],
    },
    {
        "en": 'Kinshasa', "zh": '金沙萨', "country": 'Congo (Kinshasa)',
        "lat": -4.32778, "lon": 15.31303,
        "keywords": [
            "刚果河",
            "沿河主干道",
            "热带河岸植被",
            "大型公交枢纽",
            "简易木结构住宅",
            "刚果河渡轮",
            "密集的非洲城市中心市场",
        ],
    },
    {
        "en": 'Bogota', "zh": '波哥大', "country": 'Colombia',
        "lat": 4.59837, "lon": -74.08529,
        "keywords": [
            "圣特蕾莎大教堂",
            "安第斯山脉环绕的山城",
            "殖民时期石砌建筑群",
            "狭窄鹅卵石街道",
            "哥伦比亚咖啡摊",
            "国家博物馆",
            "高海拔凉爽气候",
            "彩色陶瓷手工艺品",
        ],
    },
    {
        "en": 'Chennai', "zh": '金奈', "country": 'India',
        "lat": 13.09193, "lon": 80.27805,
        "keywords": [
            "圣托马斯山观景台",
            "维鲁帕克沙岩石纪念塔",
            "Marina Beach",
            "泰米尔文字招牌",
            "热带棕榈树街道",
            "街头Idli小吃摊",
            "红砖殖民老建筑",
            "海滨渔船",
        ],
    },
    {
        "en": 'Bengaluru', "zh": '班加罗尔', "country": 'India',
        "lat": 12.97194, "lon": 77.55806,
        "keywords": [
            "电子城",
            "热带常绿树",
            "现代科技园区建筑",
            "卡纳达文标识",
            "热带季风气候下的湿润街道",
            "街头小吃摊",
            "现代宽幅道路",
            "科技公司总部聚集区",
        ],
    },
    {
        "en": 'Bangkok', "zh": '曼谷', "country": 'Thailand',
        "lat": 13.75194, "lon": 100.5147,
        "keywords": [
            "大皇宫",
            "卧佛寺大佛",
            "湄南河",
            "热带棕榈树",
            "冬阴功汤",
            "金色佛塔",
            "狭窄街道与摩托车",
            "泰文标识",
        ],
    },
    {
        "en": 'Lahore', "zh": '拉合尔', "country": 'Pakistan',
        "lat": 31.56192, "lon": 74.34808,
        "keywords": [
            "巴德夏希清真寺",
            "夏利玛花园",
            "拉合尔城墙内老城区",
            "莫卧儿风格拱门",
            "狭窄石板街道",
            "传统香料店",
            "乌尔都语标识",
            "夏利玛花园喷泉",
        ],
    },
    {
        "en": 'Hyderabad', "zh": '海得拉巴', "country": 'India',
        "lat": 17.40193, "lon": 78.47801,
        "keywords": [
            "Charminar",
            "Hyderabadi Biryani",
            "Indo-Islamic architecture",
            "Nizam-era palaces",
            "Four minarets of Charminar",
            "Street food stalls with biryani",
            "Telugu signage",
            "Traditional Hyderabad jewelry",
        ],
    },
    {
        "en": 'Amaravati', "zh": 'Amaravati', "country": 'India',
        "lat": 16.53366, "lon": 80.52432,
        "keywords": [
            "安得拉邦议会大厦（现代玻璃幕墙对称建筑）",
            "新首府网格状规划街道",
            "宽林荫主干道（热带树木成行）",
            "泰卢固文路牌（区域文字标识）",
            "安得拉邦街头烤鱼摊（特色饮食场景）",
            "对称式现代政府建筑群",
            "热带常绿植被街道景观",
        ],
    },
    {
        "en": 'Santiago', "zh": '圣地亚哥', "country": 'Chile',
        "lat": -33.4402, "lon": -70.6505,
        "keywords": [
            "圣地亚哥大教堂",
            "安第斯山脉余脉的山体轮廓",
            "西班牙殖民风格石砌建筑",
            "铜制装饰",
            "地中海气候干燥灌木",
            "殖民时期石板路",
            "智利国旗元素",
        ],
    },
    {
        "en": 'Miami', "zh": '迈阿密', "country": 'United States',
        "lat": 25.78956, "lon": -80.22605,
        "keywords": [
            "南海滩Art Deco建筑群",
            "热带棕榈树成行的海滩",
            "拉丁风情街区",
            "海马雕塑",
            "椰子树",
            "海滩冲浪场景",
            "Art Deco风格街道",
        ],
    },
    {
        "en": 'Belo Horizonte', "zh": '贝洛奥里藏特', "country": 'Brazil',
        "lat": -19.91308, "lon": -43.91695,
        "keywords": [
            "Pampulha现代主义建筑群",
            "Pampulha湖",
            "网格状规划城市布局",
            "圣弗朗西斯科大教堂（尼迈耶设计）",
            "城市环线道路系统",
            "热带草原气候下的城市绿化",
        ],
    },
    {
        "en": 'Madrid', "zh": '马德里', "country": 'Spain',
        "lat": 40.40197, "lon": -3.6853,
        "keywords": [
            "Puerta del Sol",
            "Palacio Real de Madrid",
            "Museo del Prado",
            "Plaza Mayor",
            "Arcaded streets",
            "Azulejo tiles",
            "Wide clock tower at Puerta del Sol",
        ],
    },
    {
        "en": 'Philadelphia', "zh": '费城', "country": 'United States',
        "lat": 39.94594, "lon": -75.17984,
        "keywords": [
            "独立宫",
            "自由钟",
            "特拉华河",
            "费城老城区砖石街道",
            "乔治亚风格历史建筑",
            "费城独立宫广场",
        ],
    },
    {
        "en": 'Ahmedabad', "zh": 'Ahmedabad', "country": 'India',
        "lat": 23.032, "lon": 72.57806,
        "keywords": [
            "萨巴马蒂河",
            "甘地纪念馆",
            "传统棉纺织博物馆",
            "手织棉布纹理",
            "西部印度穹顶建筑",
            "老城区石板街道",
            "三轮车（Auto）",
            "沿河步道",
        ],
    },
    {
        "en": 'Ho Chi Minh City', "zh": '胡志明市', "country": 'Vietnam',
        "lat": 10.76212, "lon": 106.70298,
        "keywords": [
            "统一宫",
            "法式骑楼",
            "西贡中央邮局",
            "胡志明市圣母大教堂",
            "摩托车密集街道",
            "越南语招牌",
        ],
    },
    {
        "en": 'Toronto', "zh": '多伦多', "country": 'Canada',
        "lat": 43.66465, "lon": -79.38946,
        "keywords": [
            "CN Tower",
            "安大略湖沿岸湖景",
            "多伦多天际线现代玻璃幕墙高层建筑",
            "约克街（Yonge Street）",
            "多伦多街头'Toronto'路牌",
            "多伦多地铁（TTC）标志",
        ],
    },
    {
        "en": 'Singapore', "zh": '新加坡', "country": 'Singapore',
        "lat": 1.29498, "lon": 103.85388,
        "keywords": [
            "鱼尾狮雕像",
            "滨海湾金沙酒店",
            "组屋（HDB住宅）",
            "中英文双语路牌",
            "热带植被环绕的高楼",
            "新加坡河沿岸景观",
        ],
    },
    {
        "en": 'Luanda', "zh": 'Luanda', "country": 'Angola',
        "lat": -8.83634, "lon": 13.23248,
        "keywords": [
            "沿海殖民风格红砖建筑群",
            "大西洋沿岸港口码头",
            "狭窄的殖民时期街道",
            "街头葡萄牙殖民时期路灯",
            "热带植被中的非洲紫檀树",
            "大西洋沿岸白色海滨建筑",
        ],
    },
    {
        "en": 'Baghdad', "zh": 'Baghdad', "country": 'Iraq',
        "lat": 33.34059, "lon": 44.39192,
        "keywords": [
            "阿拔斯宫殿遗址建筑",
            "狭窄的阿拉伯街巷",
            "伊斯兰教法学校拱形穹顶",
            "干旱沙漠环境",
            "伊拉克烤肉串",
            "阿拉伯文字标识",
            "传统市场卡萨巴",
        ],
    },
    {
        "en": 'Barcelona', "zh": '巴塞罗那', "country": 'Spain',
        "lat": 41.38524, "lon": 2.18142,
        "keywords": [
            "圣家堂",
            "米拉之家",
            "巴特罗之家",
            "兰布拉大道",
            "高迪建筑群",
            "地中海风格马赛克装饰",
            "巴塞罗那海滩",
        ],
    },
    {
        "en": 'Haora', "zh": 'Haora', "country": 'India',
        "lat": 22.5847, "lon": 88.31852,
        "keywords": [
            "豪拉大桥（Howrah Bridge）",
            "胡格利河（Hooghly River）",
            "豪拉火车站（Howrah Railway Station）",
            "殖民时期维多利亚风格建筑",
            "印度三轮车（Auto-rickshaw）",
            "胡格利河畔桥梁群",
        ],
    },
    {
        "en": 'Dallas', "zh": '达拉斯', "country": 'United States',
        "lat": 32.77196, "lon": -96.79469,
        "keywords": [
            "Reunion Tower",
            "Neiman Marcus",
            "AT&T Stadium",
            "Broad Central Expressway",
            "Southern single-family homes",
            "Palm trees with xerophytic shrubs",
            "Highland Park Village",
        ],
    },
    {
        "en": 'Khartoum', "zh": '喀土穆', "country": 'Sudan',
        "lat": 15.59002, "lon": 32.53223,
        "keywords": [
            "尼罗河三河交汇",
            "蓝尼罗河与青尼罗河汇流",
            "喀土穆大清真寺",
            "热带草原植被",
            "阿拉伯语路牌",
            "市场摊位上的库斯库斯",
            "混合殖民与现代风格的街道",
        ],
    },
    {
        "en": 'Pune', "zh": 'Pune', "country": 'India',
        "lat": 18.51639, "lon": 73.85189,
        "keywords": [
            "尚尼瓦拉堡",
            "殖民时期石板街道",
            "芒果树成林",
            "马拉地语标识",
            "传统木制手推车",
            "干燥季尘土路",
            "印度教寺庙群",
        ],
    },
    {
        "en": 'Sydney', "zh": '悉尼', "country": 'Australia',
        "lat": -33.87137, "lon": 151.21255,
        "keywords": [
            "悉尼歌剧院",
            "悉尼海港大桥",
            "邦迪海滩",
            "悉尼港",
            "沿海棕榈树街道",
            "澳式出租车",
        ],
    },
    {
        "en": 'St.  Petersburg', "zh": 'St.  Petersburg', "country": 'Russia',
        "lat": 59.94096, "lon": 30.31407,
        "keywords": [
            "冬宫",
            "涅瓦河",
            "喀山大教堂",
            "涅瓦大街",
            "圣以撒大教堂",
            "巴洛克风格建筑群",
        ],
    },
    {
        "en": 'Chattogram', "zh": 'Chattogram', "country": 'Bangladesh',
        "lat": 22.33194, "lon": 91.79802,
        "keywords": [
            "狭窄密集的热带街道",
            "孟加拉国最大港口的集装箱码头",
            "热带芒果树环绕的居民区",
            "三轮车（Rickshaw）与热带服饰行人",
            "沿海城市的热带植被",
            "港口起重机与集装箱堆场",
        ],
    },
    {
        "en": 'Atlanta', "zh": '亚特兰大', "country": 'United States',
        "lat": 33.73946, "lon": -84.36764,
        "keywords": [
            "可口可乐博物馆",
            "石山公园",
            "CNN总部",
            "佐治亚理工学院",
            "南方风格砖石建筑",
            "可口可乐广告牌",
        ],
    },
    {
        "en": 'Boston', "zh": '波士顿', "country": 'United States',
        "lat": 42.33191, "lon": -71.07196,
        "keywords": [
            "波士顿公共花园",
            "查尔斯河",
            "老北教堂尖顶",
            "Faneuil Hall钟楼",
            "波士顿大学建筑",
            "自由之路标志",
            "贝克街历史街区",
            "查尔斯河畔长木桥",
        ],
    },
    {
        "en": 'Riyadh', "zh": '利雅得', "country": 'Saudi Arabia',
        "lat": 24.6345, "lon": 46.72049,
        "keywords": [
            "王国中心大厦",
            "沙漠中的现代摩天大楼群",
            "阿拉伯风格圆顶清真寺",
            "金合欢树成行的沙漠街道",
            "宽阔的环形主干道",
            "阿拉伯文标识",
            "沙漠中的大型停车场",
        ],
    },
    {
        "en": 'Houston', "zh": '休斯顿', "country": 'United States',
        "lat": 29.74127, "lon": -95.34844,
        "keywords": [
            "约翰逊航天中心",
            "休斯顿港油轮",
            "METRORail轻轨",
            "棕榈树街道",
            "石油工业设施",
            "宽阔德克萨斯州商业街",
            "德州烤肉摊",
            "布拉索斯河",
        ],
    },
    {
        "en": 'Hanoi', "zh": '河内', "country": 'Vietnam',
        "lat": 21.03527, "lon": 105.84807,
        "keywords": [
            "龙边桥",
            "红河",
            "法式殖民红砖建筑",
            "越南文路牌",
            "河粉摊",
            "龙形装饰",
            "狭窄鹅卵石街道",
            "胡志明纪念堂",
        ],
    },
    {
        "en": 'Washington,  D.C.', "zh": 'Washington,  D.C.', "country": 'United States',
        "lat": 38.90149, "lon": -77.01136,
        "keywords": [
            "国会大厦",
            "华盛顿纪念碑",
            "林肯纪念堂",
            "宾夕法尼亚大道",
            "白宫",
            "国家广场",
            "杰斐逊纪念堂",
            "美国国旗",
        ],
    },
    {
        "en": 'Guadalajara', "zh": '瓜达拉哈拉', "country": 'Mexico',
        "lat": 20.67196, "lon": -103.33198,
        "keywords": [
            "瓜达拉哈拉大教堂",
            "西班牙殖民风格石板街道",
            "瓜达拉哈拉大学主楼",
            "墨西哥传统陶器摊位",
            "西班牙语街道标识",
            "高原气候下的仙人掌植被",
        ],
    },
    {
        "en": 'Melbourne', "zh": '墨尔本', "country": 'Australia',
        "lat": -37.81809, "lon": 144.97307,
        "keywords": [
            "弗林德斯街车站",
            "亚拉河",
            "联邦广场",
            "维多利亚式建筑群",
            "平白咖啡",
            "桉树成荫的街道",
        ],
    },
    {
        "en": 'Alexandria', "zh": '亚历山大', "country": 'Egypt',
        "lat": 31.20197, "lon": 29.94805,
        "keywords": [
            "法罗斯灯塔遗址",
            "亚历山大图书馆",
            "地中海沿岸希腊-罗马柱式建筑",
            "尼罗河入海口沿海街道",
            "地中海渔船",
            "窄巷殖民风格石板路",
        ],
    },
    {
        "en": 'Detroit', "zh": '底特律', "country": 'United States',
        "lat": 42.33356, "lon": -83.05133,
        "keywords": [
            "底特律河",
            "废弃汽车工厂",
            "福特世界总部大楼",
            "锈迹斑斑的工业厂房",
            "五大湖沿岸码头",
            "工业衰退后的破败街区",
        ],
    },
    {
        "en": 'Yangon', "zh": '仰光', "country": 'Myanmar',
        "lat": 16.7853, "lon": 96.16473,
        "keywords": [
            "大金塔",
            "殖民时期红砖建筑",
            "苏莱佛塔",
            "仰光河沿岸",
            "缅甸文字标识",
            "热带植被环绕的街道",
            "特色三轮车",
        ],
    },
    {
        "en": 'Porto Alegre', "zh": '阿雷格里港', "country": 'Brazil',
        "lat": -30.04807, "lon": -51.20196,
        "keywords": [
            "三权广场",
            "葡萄牙殖民石砌建筑",
            "伊塔佩马河沿岸步道",
            "红瓦屋顶",
            "葡萄牙语标识",
            "街头巴西烤肉摊",
            "欧洲风格复古街灯",
            "亚热带棕榈树",
        ],
    },
    {
        "en": 'Surat', "zh": 'Surat', "country": 'India',
        "lat": 21.20193, "lon": 72.83809,
        "keywords": [
            "Tapi河",
            "棉纺织作坊",
            "Khaman dhokla",
            "Swaminarayan Temple",
            "石板街道",
            "纺织工人",
            "椰枣树",
            "Tapi河畔桥梁",
        ],
    },
    {
        "en": 'Abidjan', "zh": 'Abidjan', "country": 'Ivory Coast',
        "lat": 5.32313, "lon": -4.02021,
        "keywords": [
            "埃布里耶湖沿岸",
            "热带油棕树",
            "法式殖民红砖建筑",
            "沿海集装箱码头",
            "街头木薯饼摊",
            "红土沥青路",
            "沿海防波堤",
        ],
    },
    {
        "en": 'Brasília', "zh": '巴西利亚', "country": 'Brazil',
        "lat": -15.78139, "lon": -47.918,
        "keywords": [
            "三权广场",
            "电视塔",
            "飞机形状的国会大厦",
            "放射状主干道",
            "现代主义几何建筑群",
            "飞机造型建筑",
        ],
    },
    {
        "en": 'Ankara', "zh": '安卡拉', "country": 'Turkey',
        "lat": 39.92918, "lon": 32.86245,
        "keywords": [
            "安卡拉城堡",
            "安纳托利亚文明博物馆",
            "奥斯曼风格拱门",
            "石板老街",
            "赫梯文物",
            "安纳托利亚高原植被",
        ],
    },
    {
        "en": 'Monterrey', "zh": '蒙特雷', "country": 'Mexico',
        "lat": 25.67194, "lon": -100.33193,
        "keywords": [
            "卡萨德拉雷亚尔城堡",
            "蒙特雷大教堂",
            "拉雷亚尔山",
            "西班牙殖民风格老城区街道",
            "工业遗产建筑群",
            "西班牙语路牌",
            "现代摩天大楼与老城区混合景观",
        ],
    },
    {
        "en": 'Yokohama', "zh": '横滨', "country": 'Japan',
        "lat": 35.43066, "lon": 139.60202,
        "keywords": [
            "横滨红砖仓库",
            "地标塔",
            "横滨港未来21",
            "海滨大道",
            "横滨港码头",
            "红砖仓库历史建筑群",
        ],
    },
    {
        "en": 'Montréal', "zh": 'Montréal', "country": 'Canada',
        "lat": 45.50194, "lon": -73.58524,
        "keywords": [
            "蒙特利尔圣母大教堂",
            "老港",
            "法语路牌",
            "欧式石砌老建筑",
            "蒙特利尔奶酪蛋糕",
            "冬季积雪街道",
            "魁北克街",
            "蒙特利尔塔",
        ],
    },
    {
        "en": 'Recife', "zh": '累西腓', "country": 'Brazil',
        "lat": -8.06053, "lon": -34.90877,
        "keywords": [
            "帕拉伊巴河沿岸殖民老城区",
            "圣奥古斯丁教堂",
            "殖民时期石板街道",
            "东北部狂欢节彩车",
            "传统木雕装饰建筑",
            "热带气候下的高脚殖民建筑",
            "巴西木雕工艺装饰",
            "烤肉串",
        ],
    },
    {
        "en": 'Fortaleza', "zh": '福塔莱萨', "country": 'Brazil',
        "lat": -3.74807, "lon": -38.58193,
        "keywords": [
            "太阳海岸海滩（Praia do Futuro）",
            "沿海高层建筑群",
            "热带棕榈树成行的沿海街道",
            "巴西东北部特色烤肉串",
            "当地特色编织篮",
            "沿海红砖步道",
            "热带水果摊",
            "狂欢节装饰",
        ],
    },
    {
        "en": 'Phoenix', "zh": '菲尼克斯', "country": 'United States',
        "lat": 33.44832, "lon": -112.06736,
        "keywords": [
            "萨瓜罗仙人掌",
            "干旱沙漠植被",
            "开阔的干旱街道",
            "热带沙漠气候特征",
            "沙漠中的大型仙人掌群",
            "美国西南部干旱景观",
        ],
    },
    {
        "en": 'Salvador', "zh": '萨尔瓦多', "country": 'Brazil',
        "lat": -12.96803, "lon": -38.48193,
        "keywords": [
            "Bonfim教堂",
            "殖民石板路",
            "红土路面",
            "色彩鲜艳的殖民建筑",
            "非洲裔文化装饰",
            "传统手工艺品摊位",
            "圣弗朗西斯科河沿岸",
        ],
    },
    {
        "en": 'Busan', "zh": '釜山', "country": 'South Korea',
        "lat": 35.097, "lon": 129.0081,
        "keywords": [
            "釜山塔",
            "广安里海水浴场",
            "甘川文化村",
            "渔船码头",
            "沿海步道",
            "韩式传统房屋",
        ],
    },
    {
        "en": 'San Francisco', "zh": '旧金山', "country": 'United States',
        "lat": 37.78426, "lon": -122.3996,
        "keywords": [
            "金门大桥",
            "缆车",
            "渔人码头",
            "科伊特塔",
            "海雾",
            "陡峭街道",
            "海狮聚集",
            "Lombard Street",
        ],
    },
    {
        "en": 'Johannesburg', "zh": '约翰内斯堡', "country": 'South Africa',
        "lat": -26.1681, "lon": 28.02806,
        "keywords": [
            "Nelson Mandela Square",
            "Soweto",
            "Gold mine tailings",
            "Bunny chow",
            "Mining safety helmets",
            "Grid-patterned township streets",
            "Apartheid-era residential architecture",
        ],
    },
    {
        "en": 'Berlin', "zh": '柏林', "country": 'Germany',
        "lat": 52.52376, "lon": 13.3996,
        "keywords": [
            "勃兰登堡门",
            "电视塔（Fernsehturm Berlin）",
            "东边画廊",
            "菩提树下大街",
            "施普雷河",
            "柏林墙遗址",
        ],
    },
    {
        "en": 'Algiers', "zh": '阿尔及尔', "country": 'Algeria',
        "lat": 36.76501, "lon": 3.04861,
        "keywords": [
            "卡斯巴老城区",
            "拱券殖民建筑",
            "狭窄石板街道",
            "奥斯曼拱顶清真寺",
            "混合风格历史建筑群",
            "地中海沿岸古老堡垒",
        ],
    },
    {
        "en": 'Rome', "zh": '罗马', "country": 'Italy',
        "lat": 41.8979, "lon": 12.48131,
        "keywords": [
            "斗兽场",
            "万神殿",
            "许愿池",
            "西班牙台阶",
            "古罗马拱门",
            "罗马喷泉",
            "古罗马遗迹",
        ],
    },
    {
        "en": 'Pyongyang', "zh": 'Pyongyang', "country": 'Korea, North',
        "lat": 39.02139, "lon": 125.75275,
        "keywords": [
            "宽幅林荫大道",
            "主体思想塔",
            "朝鲜式平顶建筑",
            "对称式街道布局",
            "宣传画/标语",
            "冬季积雪覆盖的街道",
            "特制路灯",
            "马路中央绿化带",
        ],
    },
    {
        "en": 'Medellín', "zh": '麦德林', "country": 'Colombia',
        "lat": 6.27695, "lon": -75.57696,
        "keywords": [
            "空中缆车系统",
            "安第斯山脉山体",
            "阶梯式彩色建筑",
            "街头咖啡店",
            "Botero博物馆雕塑",
            "阶梯式街道布局",
        ],
    },
    {
        "en": 'Kabul', "zh": 'Kabul', "country": 'Afghanistan',
        "lat": 34.51864, "lon": 69.18131,
        "keywords": [
            "独立纪念碑",
            "喀布尔王宫",
            "老城区拱形街巷",
            "干燥沙尘天气下的街道",
            "Chorsu Bazaar拱形市场",
            "铁门（Iron Gate）",
            "干枯灌木丛",
        ],
    },
    {
        "en": 'Athens', "zh": '雅典', "country": 'Greece',
        "lat": 37.98527, "lon": 23.73137,
        "keywords": [
            "帕特农神庙",
            "雅典卫城",
            "多立克柱式建筑",
            "古典石板街道",
            "橄榄树成行的道路",
            "希腊字母标识牌",
            "古罗马拱门遗迹",
        ],
    },
    {
        "en": 'Nagoya', "zh": '名古屋', "country": 'Japan',
        "lat": 35.15694, "lon": 136.91305,
        "keywords": [
            "名古屋城天守阁",
            "名古屋铁塔",
            "荣商业区高楼群",
            "日式传统木造建筑与现代玻璃幕墙混合街道",
            "名古屋拉面店铺",
            "名古屋城护城河",
        ],
    },
    {
        "en": 'Cape Town', "zh": '开普敦', "country": 'South Africa',
        "lat": -33.91806, "lon": 18.43304,
        "keywords": [
            "桌山",
            "博斯曼街彩色房屋",
            "信号山",
            "好望角灯塔",
            "大西洋沿岸悬崖",
            "桌山缆车",
        ],
    },
    {
        "en": 'Casablanca', "zh": '卡萨布兰卡', "country": 'Morocco',
        "lat": 33.60192, "lon": -7.61831,
        "keywords": [
            "哈桑二世清真寺",
            "摩洛哥王宫",
            "法式殖民建筑",
            "棕榈树环绕的狭窄街道",
            "柏柏尔风格拱门",
            "摩洛哥风格街灯",
            "干燥地中海植被",
        ],
    },
    {
        "en": 'Kanpur', "zh": 'Kanpur', "country": 'India',
        "lat": 26.46195, "lon": 80.31805,
        "keywords": [
            "亚穆纳河畔的工业仓库群",
            "甘蔗种植田",
            "工业蒸汽管道",
            "宽幅沥青路+殖民砖砌建筑",
            "中央市场",
            "印地语招牌显示'Kanpur'",
        ],
    },
    {
        "en": 'Kano', "zh": '卡诺', "country": 'Nigeria',
        "lat": 12.00192, "lon": 8.51809,
        "keywords": [
            "科诺中央市场",
            "苏丹宫殿",
            "豪萨语标识",
            "彩色纺织品摊位",
            "狭窄市场街道",
            "烤肉串摊位",
            "清真寺尖塔",
        ],
    },
    {
        "en": 'Tel Aviv', "zh": '特拉维夫', "country": 'Israel',
        "lat": 32.08194, "lon": 34.76807,
        "keywords": [
            "白色建筑群",
            "滨海沙滩",
            "棕榈树",
            "沙滩遮阳伞",
            "现代高层建筑与沙滩并存的街景",
            "圆形现代路灯",
        ],
    },
    {
        "en": 'Addis Ababa', "zh": '亚的斯亚贝巴', "country": 'Ethiopia',
        "lat": 9.03526, "lon": 38.69806,
        "keywords": [
            "圣乔治教堂",
            "非洲联盟总部",
            "injera 面饼",
            "埃塞俄比亚传统木门",
            "狭窄沥青街道",
            "高原绿色植被",
            "阿姆哈拉语文字",
            "咖啡文化",
        ],
    },
    {
        "en": 'Curitiba', "zh": '库里蒂巴', "country": 'Brazil',
        "lat": -25.41807, "lon": -49.32194,
        "keywords": [
            "自行车专用道",
            "BRT快速公交系统",
            "库里蒂巴植物园",
            "现代主义曲线建筑",
            "宽林荫道",
            "公交车站遮阳棚",
            "热带雨林植被",
        ],
    },
    {
        "en": 'Seattle', "zh": '西雅图', "country": 'United States',
        "lat": 47.60042, "lon": -122.31532,
        "keywords": [
            "太空针塔",
            "常绿针叶林",
            "坡度较大的街道",
            "星巴克总部",
            "阴雨天气",
            "木质结构老建筑",
        ],
    },
    {
        "en": 'Jeddah', "zh": '吉达', "country": 'Saudi Arabia',
        "lat": 21.51883, "lon": 39.21725,
        "keywords": [
            "红海海滨长廊",
            "吉达塔",
            "沙漠与红海交界景观",
            "Al-Balad老城区石砌建筑",
            "沙尘天气下的街道",
            "阿拉伯风格尖塔清真寺",
            "海滨现代建筑群",
            "稀疏棕榈树",
        ],
    },
    {
        "en": 'Irvine', "zh": 'Irvine', "country": 'United States',
        "lat": 33.68041, "lon": -117.82995,
        "keywords": [
            "UCI校园",
            "规划网格街道",
            "Irvine Spectrum Center",
            "棕榈树与地中海植被",
            "现代低密度住宅区",
            "科技园区",
            "社区规划公园",
        ],
    },
    {
        "en": 'Nairobi', "zh": '内罗毕', "country": 'Kenya',
        "lat": -1.2814, "lon": 36.81471,
        "keywords": [
            "肯尼亚国家博物馆",
            "长颈鹿公园",
            "红土路",
            "热带草原植被",
            "肯尼亚咖啡",
            "斯瓦希里语路牌",
            "长颈鹿雕塑",
        ],
    },
    {
        "en": 'Benoni', "zh": 'Benoni', "country": 'South Africa',
        "lat": -26.14764, "lon": 28.32799,
        "keywords": [
            "矿工纪念碑",
            "红砖多层公寓",
            "街边braai烧烤摊",
            "金合欢树成行的街道",
            "市政厅前的圆形广场",
            "约翰内斯堡大都市圈郊区街道",
        ],
    },
    {
        "en": 'Caracas', "zh": 'Caracas', "country": 'Venezuela',
        "lat": 10.50294, "lon": -66.91898,
        "keywords": [
            "国会大厦（El Capitolio）的穹顶建筑",
            "玻利瓦尔广场的纪念碑",
            "坡度陡峭的盘山街道",
            "街头玉米饼（Arepa）摊位",
            "热带棕榈树与高密度建筑的混合景观",
            "西班牙语路牌上的“Caracas”字样",
            "街头手推车卖热带水果",
            "玻利瓦尔雕像",
        ],
    },
    {
        "en": 'Milan', "zh": '米兰', "country": 'Italy',
        "lat": 45.47192, "lon": 9.20306,
        "keywords": [
            "米兰大教堂",
            "维托里奥·埃马努埃莱二世拱廊",
            "哥特式尖顶建筑群",
            "拱廊街的玻璃穹顶",
            "米兰大教堂玫瑰窗",
            "街道上的时尚品牌店",
            "历史建筑群",
        ],
    },
    {
        "en": 'Stuttgart', "zh": '斯图加特', "country": 'Germany',
        "lat": 48.77998, "lon": 9.2,
        "keywords": [
            "施瓦本门",
            "新王宫",
            "奔驰博物馆",
            "布尔什维茨喷泉",
            "奶酪土豆面团",
            "巴洛克风格建筑群",
            "汽车主题街道",
            "老城区石板路",
        ],
    },
    {
        "en": 'Dar es Salaam', "zh": '达累斯萨拉姆', "country": 'Tanzania',
        "lat": -6.79807, "lon": 39.2664,
        "keywords": [
            "沿海港口",
            "红土色道路",
            "热带棕榈树",
            "当地水果摊位",
            "摩托车",
            "清真寺尖塔",
            "红色泥土路面",
            "香蕉树",
        ],
    },
    {
        "en": 'Jaipur', "zh": 'Jaipur', "country": 'India',
        "lat": 26.92308, "lon": 75.80804,
        "keywords": [
            "粉红城墙",
            "风之宫殿",
            "传统黄铜灯具",
            "拉贾普特风格尖顶建筑",
            "街头牛群",
            "干燥灌木丛",
            "粉色建筑群",
        ],
    },
    {
        "en": 'San Diego', "zh": '圣迭戈', "country": 'United States',
        "lat": 32.71891, "lon": -117.15088,
        "keywords": [
            "科罗纳多酒店",
            "西班牙殖民风格建筑",
            "海滨步道",
            "墨西哥风味餐厅",
            "科罗纳多大桥",
            "圣地亚哥动物园",
            "沿海别墅区",
            "棕榈树",
        ],
    },
    {
        "en": 'Frankfurt', "zh": '法兰克福', "country": 'Germany',
        "lat": 50.09998, "lon": 8.67502,
        "keywords": [
            "法兰克福大教堂",
            "美因河",
            "欧洲中央银行",
            "铁桥",
            "法兰克福香肠",
            "法兰克福金融区高楼",
            "美因河上的桥梁",
            "法兰克福老城区的罗马广场",
        ],
    },
    {
        "en": 'Surabaya', "zh": '泗水', "country": 'Indonesia',
        "lat": -7.24729, "lon": 112.74889,
        "keywords": [
            "泗水门",
            "荷兰殖民红砖建筑",
            "摩托车密集街道",
            "布兰塔斯河沿岸",
            "印尼烤肉串摊位",
            "热带植被环绕的殖民街区",
        ],
    },
    {
        "en": 'Lisbon', "zh": '里斯本', "country": 'Portugal',
        "lat": 38.72467, "lon": -9.14681,
        "keywords": [
            "贝伦塔",
            "圣胡斯塔升降机",
            "塔霍河沿岸",
            "葡式蛋挞",
            "蓝白瓷砖",
            "狭窄石板路",
            "四塔教堂",
        ],
    },
    {
        "en": 'Fukuoka', "zh": '福冈', "country": 'Japan',
        "lat": 33.59696, "lon": 130.40807,
        "keywords": [
            "福冈塔",
            "博多拉面",
            "太宰府天满宫",
            "博多运河城",
            "传统木造町屋",
            "亚热带绿树成荫街道",
            "博多布袋戏",
        ],
    },
    {
        "en": 'Campinas', "zh": 'Campinas', "country": 'Brazil',
        "lat": -22.9079, "lon": -47.05589,
        "keywords": [
            "圣若泽大教堂",
            "宽幅林荫大道",
            "热带阔叶树街道景观",
            "街头巴西烤肉摊位",
            "巴西咖啡豆包装袋",
            "足球海报装饰的街角",
        ],
    },
    {
        "en": 'Quezon City', "zh": '奎松城', "country": 'Philippines',
        "lat": 14.65043, "lon": 121.02997,
        "keywords": [
            "Quezon Memorial Circle",
            "混凝土阳台铁栅栏住宅群",
            "菲律宾三轮摩托车",
            "密集混凝土公寓楼",
            "菲律宾语路牌",
            "大都会区主干道（EDSA）",
            "街头小吃摊",
        ],
    },
    {
        "en": 'Katowice', "zh": 'Katowice', "country": 'Poland',
        "lat": 50.26038, "lon": 19.02002,
        "keywords": [
            "煤仓建筑群",
            "工业烟囱群",
            "上西里西亚工业遗产",
            "黑色城市",
            "煤矿工业厂房",
            "欧洲城市中心与工业遗产融合的街道",
        ],
    },
    {
        "en": 'Aleppo', "zh": 'Aleppo', "country": 'Syria',
        "lat": 36.23192, "lon": 37.16807,
        "keywords": [
            "大清真寺",
            "古城墙",
            "阿勒颇集市",
            "石砌拱券建筑",
            "狭窄石板街道",
            "传统铜器摊位",
        ],
    },
    {
        "en": 'Durban', "zh": '德班', "country": 'South Africa',
        "lat": -29.86066, "lon": 31.01094,
        "keywords": [
            "uShaka海洋世界",
            "印度洋海岸线",
            "热带棕榈树街道",
            "印度裔社区建筑",
            "Durban港码头",
            "街头香料摊位",
            "圣保罗大教堂",
        ],
    },
    {
        "en": 'Kyiv', "zh": '基辅', "country": 'Ukraine',
        "lat": 50.43531, "lon": 30.51468,
        "keywords": [
            "圣索菲亚大教堂",
            "第聂伯河",
            "佩切尔斯基修道院",
            "老城区石板路",
            "冬季结冰的第聂伯河",
            "拜占庭风格马赛克",
            "基辅地铁标志",
        ],
    },
    {
        "en": 'Lucknow', "zh": 'Lucknow', "country": 'India',
        "lat": 26.85699, "lon": 80.91305,
        "keywords": [
            "Bara Imambara",
            "Chota Imambara",
            "殖民时期红砖拱顶建筑",
            "带雕花铁艺的窗户",
            "街头香料摊",
            "芒果树成行的街道",
            "传统Chikankari刺绣装饰",
        ],
    },
    {
        "en": 'Giza', "zh": '吉萨', "country": 'Egypt',
        "lat": 30.00999, "lon": 31.19002,
        "keywords": [
            "胡夫金字塔",
            "狮身人面像",
            "尼罗河沿岸沙漠景观",
            "古埃及石质神庙遗址",
            "沙漠中的金字塔群",
            "石雕人面兽身像",
            "尼罗河三角洲边缘的沙漠地貌",
        ],
    },
    {
        "en": 'Ibadan', "zh": 'Ibadan', "country": 'Nigeria',
        "lat": 7.38197, "lon": 3.92804,
        "keywords": [
            "Oja Oba市场",
            "伊巴丹大学建筑",
            "热带乔木遮荫街道",
            "街头摊位售卖pounded yam",
            "非洲传统手工艺品摊位",
            "宽幅沥青街道与高大非洲楝树",
            "约鲁巴语标识",
        ],
    },
    {
        "en": 'Faisalabad', "zh": 'Faisalabad', "country": 'Pakistan',
        "lat": 31.41193, "lon": 73.10805,
        "keywords": [
            "纺织厂烟囱群",
            "传统纺织品市场摊位",
            "费萨拉巴德中央清真寺圆顶",
            "宽阔工业大道上的大型仓库",
            "街头烤肉串摊位",
            "三轮摩托车穿梭",
            "芒果树成行的热带街道",
            "旁遮普语标识牌",
        ],
    },
    {
        "en": 'Minneapolis', "zh": 'Minneapolis', "country": 'United States',
        "lat": 44.98192, "lon": -93.25373,
        "keywords": [
            "Spoonbridge and Cherry",
            "Hennepin Avenue Bridge",
            "Lake of the Isles",
            "Winter snow - covered streets",
            "Mill Ruins Park",
            "Lakes District",
        ],
    },
    {
        "en": 'Dakar', "zh": '达喀尔', "country": 'Senegal',
        "lat": 14.71778, "lon": -17.47508,
        "keywords": [
            "非洲大陆最西端海岸线",
            "殖民风格红砖建筑",
            "金合欢林环绕的街道",
            "街头鱼汤摊位（Thiébou Dienne）",
            "法语标识与非洲文字并存",
            "沿海渔船与码头",
            "茅草屋顶的传统民居",
            "干燥灌木丛植被",
        ],
    },
    {
        "en": 'İzmir', "zh": '伊兹密尔', "country": 'Turkey',
        "lat": 38.4381, "lon": 27.14985,
        "keywords": [
            "科纳克钟楼",
            "伊兹密尔海滨长廊",
            "奥斯曼拱廊街",
            "土耳其烤肉店招牌",
            "地中海柑橘树",
            "伊兹密尔老城奥斯曼建筑",
            "特色街灯",
        ],
    },
    {
        "en": 'Incheon', "zh": '仁川', "country": 'South Korea',
        "lat": 37.47809, "lon": 126.64029,
        "keywords": [
            "仁川国际机场",
            "仁川港",
            "仁川塔",
            "沿海集装箱码头",
            "韩式现代高层建筑群",
            "仁川湾沿海步道",
            "韩式海鲜市场",
            "温带海洋性气候下的沿海植被",
        ],
    },
    {
        "en": 'Sapporo', "zh": '札幌', "country": 'Japan',
        "lat": 43.07693, "lon": 141.3381,
        "keywords": [
            "札幌电视塔",
            "大通公园",
            "北海道拉面",
            "冬季雪覆盖街道",
            "札幌雪祭雪雕",
            "北海道冬季雪景",
            "大通通主干道",
            "拉面碗",
        ],
    },
    {
        "en": 'Guayaquil', "zh": '瓜亚基尔', "country": 'Ecuador',
        "lat": -2.21809, "lon": -79.92199,
        "keywords": [
            "海滨长廊2000",
            "瓜亚基尔河入海口",
            "沿海集装箱码头",
            "西班牙殖民风格建筑",
            "热带水果摊",
            "沿海热带植被",
        ],
    },
    {
        "en": 'George Town', "zh": 'George Town', "country": 'Malaysia',
        "lat": 5.41361, "lon": 100.32937,
        "keywords": [
            "乔治亚风格骑楼",
            "圣乔治大教堂",
            "槟城市政厅（维多利亚时期红砖建筑）",
            "骑楼连廊街道",
            "多元文化融合的殖民建筑群",
            "槟城特色叻沙小吃摊",
        ],
    },
    {
        "en": 'San Juan', "zh": 'San Juan', "country": 'United States',
        "lat": 18.44002, "lon": -66.12998,
        "keywords": [
            "圣胡安老城石墙建筑",
            "圣费利佩堡（Castillo San Felipe del Morro）",
            "西班牙殖民风格白色石砌房屋",
            "加勒比海沿岸海滨石墙街道",
            "殖民时期教堂尖顶",
            "热带棕榈树环绕的殖民建筑群",
        ],
    },
    {
        "en": 'Mashhad', "zh": '马什哈德', "country": 'Iran',
        "lat": 36.27197, "lon": 59.56805,
        "keywords": [
            "伊玛目·赖兹圣陵",
            "伊斯兰圆顶建筑",
            "狭窄拱形街道",
            "波斯文字路牌",
            "干旱灌木植被",
            "宗教尖塔装饰",
        ],
    },
    {
        "en": 'Damascus', "zh": 'Damascus', "country": 'Syria',
        "lat": 33.50198, "lon": 36.29805,
        "keywords": [
            "倭马亚清真寺",
            "老城石板街",
            "阿拉伯烤肉串",
            "老城拱形门廊",
            "阿拉伯文字标识",
            "传统铜制水壶",
            "老城庭院式建筑",
        ],
    },
    {
        "en": 'Daegu', "zh": '大邱', "country": 'South Korea',
        "lat": 35.86874, "lon": 128.60503,
        "keywords": [
            "大邱塔",
            "大邱冷面",
            "大邱东门市场",
            "韩式传统街巷",
            "街边米糕摊",
            "庆北大学建筑群",
        ],
    },
    {
        "en": 'Nagpur', "zh": 'Nagpur', "country": 'India',
        "lat": 21.17191, "lon": 79.08805,
        "keywords": [
            "中央监狱",
            "铁路枢纽",
            "提拉克纪念馆",
            "芒果树",
            "咖喱鸡",
            "殖民时期建筑",
        ],
    },
    {
        "en": 'Tunis', "zh": '突尼斯市', "country": 'Tunisia',
        "lat": 36.80278, "lon": 10.17968,
        "keywords": [
            "突尼斯老城",
            "棕榈树街道",
            "阿拉伯风格拱门",
            "狭窄石板路",
            "阿拉伯语标识",
            "街边铜制水壶",
            "地中海气候植被",
        ],
    },
    {
        "en": 'Vienna', "zh": '维也纳', "country": 'Austria',
        "lat": 48.20196, "lon": 16.36469,
        "keywords": [
            "圣斯蒂芬大教堂绿色圆顶",
            "美泉宫巴洛克建筑群",
            "多瑙河沿岸景观",
            "维也纳经典咖啡馆木质桌椅",
            "霍夫堡宫古典建筑",
            "欧式巴洛克风格立面",
            "圣斯蒂芬大教堂彩色瓷砖马赛克",
        ],
    },
    {
        "en": 'Omdurman', "zh": 'Omdurman', "country": 'Sudan',
        "lat": 15.61668, "lon": 32.48002,
        "keywords": [
            "清真寺尖塔群",
            "尼罗河沿岸街道",
            "狭窄石板街道",
            "传统市场摊位",
            "金属制传统灯具",
            "白色建筑群",
            "阿拉伯文招牌",
            "骆驼纪念雕塑",
        ],
    },
    {
        "en": 'Bandung', "zh": '万隆', "country": 'Indonesia',
        "lat": -6.94808, "lon": 107.56807,
        "keywords": [
            "独立广场",
            "荷兰殖民风格钟楼建筑",
            "山城狭窄石板街道",
            "热带阔叶树街道景观",
            "印尼传统手工艺品摊位",
            "Bandung大学标志性建筑",
            "热带水果街边摊",
            "欧洲风格殖民建筑群",
        ],
    },
    {
        "en": 'Bekasi', "zh": 'Bekasi', "country": 'Indonesia',
        "lat": -6.21726, "lon": 106.97232,
        "keywords": [
            "雅加达-贝卡西轻轨轨道",
            "贝卡西大清真寺尖塔",
            "热带植被中的低层现代住宅区",
            "印尼摩托车密集行驶",
            "街边warung小餐馆",
            "狭窄沥青路与现代公寓混合",
            "热带雨林边缘的城市道路",
        ],
    },
    {
        "en": 'Mannheim', "zh": 'Mannheim', "country": 'Germany',
        "lat": 49.50037, "lon": 8.47002,
        "keywords": [
            "多瑙河畔的曼海姆老城",
            "曼海姆歌剧院",
            "巴洛克风格老建筑群",
            "多瑙河河畔街道",
            "曼海姆老城广场",
            "欧洲古典街灯",
            "多瑙河",
        ],
    },
    {
        "en": 'Tampa', "zh": 'Tampa', "country": 'United States',
        "lat": 27.94893, "lon": -82.46057,
        "keywords": [
            "坦帕湾",
            "Ybor City西班牙殖民风格建筑",
            "Clearwater Beach",
            "棕榈树成行的海滨街道",
            "热带植被",
            "海滨码头",
            "南部风味烧烤店",
        ],
    },
    {
        "en": 'Vancouver', "zh": '温哥华', "country": 'Canada',
        "lat": 49.27536, "lon": -123.12359,
        "keywords": [
            "斯坦利公园",
            "煤气镇石板路",
            "渔人码头",
            "巨型红杉林",
            "海滨高层建筑群",
            "北岸山脉",
            "温哥华常绿针叶林",
        ],
    },
    {
        "en": 'Denver', "zh": '丹佛', "country": 'United States',
        "lat": 39.74113, "lon": -104.98596,
        "keywords": [
            "科罗拉多州议会大厦",
            "落基山脉",
            "金色圆顶议会大厦",
            "丹佛国际机场",
            "红岩露天剧场",
            "山景街道",
        ],
    },
    {
        "en": 'Birmingham', "zh": '伯明翰', "country": 'United Kingdom',
        "lat": 52.47692, "lon": -1.92194,
        "keywords": [
            "伯明翰中国城",
            "维多利亚广场",
            "红砖工业建筑",
            "博洛尼亚香肠",
            "伯明翰大学主楼",
            "网格状街道与维多利亚时期建筑",
            "工业革命博物馆",
        ],
    },
    {
        "en": 'Baltimore', "zh": 'Baltimore', "country": 'United States',
        "lat": 39.28152, "lon": -76.61458,
        "keywords": [
            "内港摩天轮",
            "麦克亨利堡",
            "Fells Point运河",
            "维多利亚风格历史建筑",
            "美国国家水族馆",
            "红砖墙老建筑",
        ],
    },
    {
        "en": 'Cali', "zh": '卡利', "country": 'Colombia',
        "lat": 3.40191, "lon": -76.50191,
        "keywords": [
            "Cerro Popa",
            "Bandeja Paisa",
            "Cali Carnival",
            "Colonial church with bell tower",
            "Tropical palm trees",
            "Empanadas street stalls",
            "Coffee plantations",
        ],
    },
    {
        "en": 'Sendai', "zh": 'Sendai', "country": 'Japan',
        "lat": 38.26844, "lon": 140.86967,
        "keywords": [
            "仙台城",
            "广濑川沿岸街道",
            "青叶通商店街",
            "仙台拉面店",
            "仙台传统木造建筑群",
            "仙台站现代化建筑",
        ],
    },
    {
        "en": 'Naples', "zh": '那不勒斯', "country": 'Italy',
        "lat": 40.84197, "lon": 14.24307,
        "keywords": [
            "维苏威火山",
            "玛格丽特披萨",
            "马焦雷广场巴洛克拱廊",
            "石板老街",
            "那不勒斯彩陶",
            "圣卡洛剧院",
        ],
    },
    {
        "en": 'Manchester', "zh": '曼彻斯特', "country": 'United Kingdom',
        "lat": 53.47532, "lon": -2.24869,
        "keywords": [
            "老特拉福德球场",
            "维多利亚火车站",
            "曼彻斯特大学红砖建筑",
            "切瑟姆运河",
            "曼彻斯特维多利亚街",
            "红砖工业建筑群",
        ],
    },
    {
        "en": 'St. Louis', "zh": 'St. Louis', "country": 'United States',
        "lat": 38.63696, "lon": -90.24193,
        "keywords": [
            "Gateway Arch",
            "Mississippi River",
            "Laclede's Landing",
            "St. Louis-style pizza",
            "Old Courthouse",
            "Eads Bridge",
        ],
    },
    {
        "en": 'Puebla', "zh": '普埃布拉', "country": 'Mexico',
        "lat": 19.03259, "lon": -98.20374,
        "keywords": [
            "圣母升天大教堂",
            "西班牙殖民风格建筑群",
            "玉米粉圆",
            "蓝白瓷砖装饰墙面",
            "殖民时期石板街道",
            "圣奥古斯丁街",
            "玉米粉圆摊位",
        ],
    },
    {
        "en": 'Tripoli', "zh": 'Tripoli', "country": 'Libya',
        "lat": 32.8925, "lon": 13.18001,
        "keywords": [
            "意大利殖民风格建筑群",
            "迷宫式狭窄街道",
            "沙漠气候下的城市布局",
            "老城区的黎波里城堡",
            "阿拉伯-意大利混合建筑风格",
            "市场里的传统铜器摊位",
            "干旱环境中稀疏的绿植",
            "三轮摩托车",
        ],
    },
    {
        "en": 'Tashkent', "zh": 'Tashkent', "country": 'Uzbekistan',
        "lat": 41.30383, "lon": 69.26882,
        "keywords": [
            "塔什干电视塔",
            "库克尔德什麻扎",
            "查尔苏大巴扎",
            "苏联式红砖多层公寓楼群",
            "西里尔字母路牌",
            "中亚风格圆顶拱门建筑",
            "宽幅主干道对称布局",
        ],
    },
    {
        "en": 'Havana', "zh": '哈瓦那', "country": 'Cuba',
        "lat": 23.1339, "lon": -82.36613,
        "keywords": [
            "莫罗城堡",
            "美国经典老车",
            "棕榈树街道",
            "老城殖民建筑",
            "哈瓦那雪茄",
            "鹅卵石街道",
            "西班牙语路牌",
            "热带植被",
        ],
    },
    {
        "en": 'Belém', "zh": 'Belém', "country": 'Brazil',
        "lat": -1.44806, "lon": -48.48197,
        "keywords": [
            "亚马逊河入海口",
            "殖民时期石砌教堂",
            "红树林湿地景观",
            "热带雨林茂密树冠",
            "石板路殖民街道",
            "亚马逊河木筏运输",
        ],
    },
    {
        "en": 'Patna', "zh": 'Patna', "country": 'India',
        "lat": 25.62691, "lon": 85.12809,
        "keywords": [
            "Gyanvapi Mosque",
            "恒河河畔石阶",
            "Patna Museum",
            "旧城区砖石建筑",
            "街头牛群",
            "传统香料摊位",
            "恒河木制渡船",
        ],
    },
    {
        "en": 'Santo Domingo', "zh": '圣多明各', "country": 'Dominican Republic',
        "lat": 18.47075, "lon": -69.92974,
        "keywords": [
            "殖民时期石砌大教堂",
            "老城区狭窄石板街道",
            "西班牙殖民风格红瓦建筑",
            "多米尼加烤土豆片",
            "殖民时期城墙遗迹",
            "热带植被环绕历史街区",
        ],
    },
    {
        "en": 'Baku', "zh": '巴库', "country": 'Azerbaijan',
        "lat": 40.39722, "lon": 49.86027,
        "keywords": [
            "巴库古城墙",
            "波浪桥",
            "圆顶清真寺",
            "石板老街",
            "海上石油平台",
            "阿塞拜疆国旗",
            "Flame Towers",
            "古城门",
        ],
    },
    {
        "en": 'Accra', "zh": '阿克拉', "country": 'Ghana',
        "lat": 5.55198, "lon": -0.21866,
        "keywords": [
            "独立纪念碑",
            "波纹铁皮屋顶建筑",
            "金合欢树",
            "街头手推车",
            "狭窄沥青街道",
            "当地小吃摊位",
        ],
    },
    {
        "en": 'Medan', "zh": 'Medan', "country": 'Indonesia',
        "lat": 3.58192, "lon": 98.64809,
        "keywords": [
            "Great Mosque of Medan",
            "tropical palm trees",
            "Indonesian-language street signs",
            "oil palm trees",
            "Chinatown",
            "Lontong",
            "colonial-style red brick buildings",
        ],
    },
    {
        "en": 'Santa Cruz', "zh": 'Santa Cruz', "country": 'Bolivia',
        "lat": -17.75197, "lon": -63.22794,
        "keywords": [
            "圣克鲁斯大教堂",
            "热带草原稀树景观",
            "宽阔的西班牙殖民风格街道",
            "当地特色烤肉摊",
            "亚马孙盆地边缘的城市布局",
            "耐旱乔木（金合欢）街道绿化",
            "西班牙语标识中的'Santa Cruz'地名",
        ],
    },
    {
        "en": 'Maracaibo', "zh": 'Maracaibo', "country": 'Venezuela',
        "lat": 10.73192, "lon": -71.66192,
        "keywords": [
            "马拉开波湖",
            "热带棕榈树",
            "湖畔码头",
            "西班牙殖民建筑",
            "石油储罐",
            "宽幅湖畔街道",
            "热带水果摊",
        ],
    },
    {
        "en": 'Kuwait City', "zh": 'Kuwait City', "country": 'Kuwait',
        "lat": 29.37166, "lon": 47.97635,
        "keywords": [
            "科威特塔",
            "科威特中央清真寺",
            "沙漠中的现代高楼群",
            "阿拉伯文字标识",
            "棕榈树与沙漠景观",
            "石油管道设施",
            "宽阔的沙漠城市街道",
            "现代与阿拉伯融合的建筑风格",
        ],
    },
    {
        "en": 'Dammam', "zh": 'Dammam', "country": 'Saudi Arabia',
        "lat": 26.43014, "lon": 50.09772,
        "keywords": [
            "波斯湾沿岸的港口码头",
            "沙漠中的现代高层建筑群",
            "石油开采工业设施（钻井平台）",
            "沿海沙漠公路",
            "阿拉伯文字的“达曼”标识",
            "沿海防波堤",
        ],
    },
    {
        "en": 'Hiroshima', "zh": 'Hiroshima', "country": 'Japan',
        "lat": 34.38978, "lon": 132.44097,
        "keywords": [
            "原爆圆顶屋",
            "广岛和平纪念公园",
            "广岛烧",
            "广岛和平纪念大桥",
            "广岛和平纪念资料馆",
            "广岛市中心的复古街道",
        ],
    },
    {
        "en": 'Fort Lauderdale', "zh": 'Fort Lauderdale', "country": 'United States',
        "lat": 26.13606, "lon": -80.14178,
        "keywords": [
            "棕榈树环绕的海滩",
            "热带风格公寓楼",
            "沿海步道",
            "高大椰子树",
            "沙滩椅",
            "水上摩托艇",
            "热带灌木丛",
        ],
    },
    {
        "en": 'Long Beach', "zh": 'Long Beach', "country": 'United States',
        "lat": 33.77702, "lon": -118.20034,
        "keywords": [
            "集装箱码头",
            "海滨长廊",
            "棕榈树成行的海滨步道",
            "大型货轮停靠港",
            "石油化工储罐",
            "沿海弧形道路",
            "港口海鲜摊位",
        ],
    },
    {
        "en": 'Indore', "zh": 'Indore', "country": 'India',
        "lat": 22.71701, "lon": 75.86308,
        "keywords": [
            "Indore中央市场",
            "红色砂岩建筑",
            "印度教寺庙尖顶",
            "三轮车",
            "狭窄商铺街道",
            "传统手工艺品摊位",
            "热带绿树",
        ],
    },
    {
        "en": 'Goiânia', "zh": 'Goiânia', "country": 'Brazil',
        "lat": -16.71808, "lon": -49.30197,
        "keywords": [
            "戈亚尼亚大教堂",
            "放射状街道网格",
            "塞区中心广场",
            "塞拉多植被",
            "当地烤肉摊",
            "宽大林荫大道",
            "戈亚斯州政府宫",
        ],
    },
    {
        "en": 'Sanaa', "zh": 'Sanaa', "country": 'Yemen',
        "lat": 15.35668, "lon": 44.20465,
        "keywords": [
            "传统土坯建筑",
            "狭窄石板巷",
            "伊斯兰拱券圆顶",
            "多层悬挑民居",
            "骆驼饮水槽",
            "干枯灌木丛",
            "阿拉伯风格尖塔",
        ],
    },
    {
        "en": 'Port-au-Prince', "zh": 'Port-au-Prince', "country": 'Haiti',
        "lat": 18.54297, "lon": -72.33798,
        "keywords": [
            "破损的殖民风格石砌建筑",
            "铁皮屋顶密集民居",
            "地震后临时铁皮棚屋",
            "狭窄石板街道",
            "热带灌木丛中的混凝土结构",
            "街头手推车",
        ],
    },
    {
        "en": 'Haiphong', "zh": 'Haiphong', "country": 'Vietnam',
        "lat": 20.83195, "lon": 106.67815,
        "keywords": [
            "圣约瑟夫大教堂",
            "红河入海口",
            "棋盘式老城区街道",
            "法国殖民风格建筑",
            "海防港",
            "越南北部法式糕点店",
            "红河沿岸码头",
        ],
    },
    {
        "en": 'Bucharest', "zh": '布加勒斯特', "country": 'Romania',
        "lat": 44.43532, "lon": 26.098,
        "keywords": [
            "罗马尼亚议会宫",
            "多瑙河",
            "Calea Victoriei林荫大道",
            "新古典主义穹顶建筑",
            "街边mici摊位",
            "罗马尼亚语标识",
        ],
    },
    {
        "en": 'Douala', "zh": 'Douala', "country": 'Cameroon',
        "lat": 4.06236, "lon": 9.70805,
        "keywords": [
            "Wouri河上的桥梁",
            "大型集装箱码头",
            "街道两旁的高大棕榈树",
            "露天市场中的手推车",
            "红砖殖民建筑",
            "热带水果摊位",
            "雨天湿润的街道",
        ],
    },
    {
        "en": 'Cleveland', "zh": 'Cleveland', "country": 'United States',
        "lat": 41.47193, "lon": -81.69694,
        "keywords": [
            "Terminal Tower",
            "Rock and Roll Hall of Fame",
            "Cuyahoga River",
            "West Side Market",
            "Lake Erie",
            "Terminal Tower's clock tower",
        ],
    },
    {
        "en": 'Portland', "zh": '波特兰', "country": 'United States',
        "lat": 45.52197, "lon": -122.68194,
        "keywords": [
            "气垫船码头",
            "雨城",
            "气垫船连接机场",
            "气垫船交通",
            "波特兰的街道",
            "气垫船渡河",
        ],
    },
    {
        "en": 'Asunción', "zh": '亚松森', "country": 'Paraguay',
        "lat": -25.29067, "lon": -57.62583,
        "keywords": [
            "亚松森大教堂",
            "巴拉圭河",
            "棋盘式殖民街道",
            "金合欢树",
            "巴拉圭汤",
            "洛佩斯宫",
            "街头烤肉摊",
        ],
    },
    {
        "en": 'Saidu', "zh": 'Saidu', "country": 'Pakistan',
        "lat": 34.75003, "lon": 72.34999,
        "keywords": [
            "盘山公路与山体交错",
            "普什图族传统木屋",
            "开伯尔山脉景观",
            "山间河流（Swat河）",
            "普什图语路牌",
            "传统木制门廊",
            "山区松树林",
            "石砌道路与木制护栏",
        ],
    },
    {
        "en": 'Brisbane', "zh": '布里斯班', "country": 'Australia',
        "lat": -27.45309, "lon": 153.03315,
        "keywords": [
            "故事桥",
            "布里斯班河",
            "热带棕榈树",
            "南岸公园",
            "河上渡轮",
            "宽阔河畔步道",
            "亚热带植被",
        ],
    },
    {
        "en": 'Rawalpindi', "zh": 'Rawalpindi', "country": 'Pakistan',
        "lat": 33.591, "lon": 73.0675,
        "keywords": [
            "旁遮普大学主楼",
            "殖民时期石板路",
            "英式殖民路灯",
            "干燥松树林",
            "Peshawari Naan",
            "旁遮普文招牌",
            "拉瓦尔品第城堡",
            "传统手工艺品摊位",
        ],
    },
    {
        "en": 'Beirut', "zh": '贝鲁特', "country": 'Lebanon',
        "lat": 33.87392, "lon": 35.50776,
        "keywords": [
            "贝鲁特港",
            "贝鲁特中央清真寺",
            "地中海沿岸蓝色大海",
            "法式殖民建筑",
            "Corniche Beirut",
            "集装箱码头",
            "阿拉伯文字招牌",
            "橄榄树",
        ],
    },
    {
        "en": 'Pittsburgh', "zh": 'Pittsburgh', "country": 'United States',
        "lat": 40.43194, "lon": -80.00193,
        "keywords": [
            "三河交汇",
            "点公园喷泉",
            "三座跨河大桥",
            "钢铁厂工业遗迹",
            "煤铁工业烟囱",
            "Duquesne Incline",
        ],
    },
    {
        "en": 'Las Vegas', "zh": '拉斯维加斯', "country": 'United States',
        "lat": 36.16476, "lon": -115.15136,
        "keywords": [
            "贝拉吉奥喷泉",
            "拉斯维加斯大道",
            "霓虹灯招牌",
            "赌场",
            "沙漠植被",
            "拉斯维加斯大道的酒店群",
            "Fremont Street Experience",
        ],
    },
    {
        "en": 'Kyoto', "zh": '京都', "country": 'Japan',
        "lat": 35.03194, "lon": 135.74805,
        "keywords": [
            "金阁寺",
            "清水寺",
            "伏见稻荷千本鸟居",
            "传统木质町屋",
            "和服",
            "抹茶甜点",
            "石板街道",
            "日式纸灯笼",
        ],
    },
    {
        "en": 'Minsk', "zh": '明斯克', "country": 'Belarus',
        "lat": 53.90192, "lon": 27.56468,
        "keywords": [
            "圣灵大教堂",
            "明斯克中央市场",
            "苏联风格红砖公寓楼",
            "白俄罗斯国旗装饰",
            "宽阔林荫大道",
            "冬季积雪下的红砖建筑",
        ],
    },
    {
        "en": 'Barranquilla', "zh": 'Barranquilla', "country": 'Colombia',
        "lat": 10.96193, "lon": -74.80191,
        "keywords": [
            "和平塔",
            "加勒比海沿岸集装箱码头",
            "热带棕榈树街道",
            "街边empanada（玉米饼）摊位",
            "殖民风格红瓦屋顶建筑",
            "加勒比海货船",
            "街头“cholita”小贩",
        ],
    },
    {
        "en": 'Valencia', "zh": '瓦伦西亚', "country": 'Venezuela',
        "lat": 10.23193, "lon": -67.98197,
        "keywords": [
            "Lago de Valencia",
            "Spanish colonial architecture",
            "Colonial street layout",
            "Tropical palm trees",
            "Local arepa",
            "Sopa de mondongo",
            "Colorful market stalls",
            "Red brick facades",
        ],
    },
    {
        "en": 'Hamburg', "zh": '汉堡', "country": 'Germany',
        "lat": 53.55197, "lon": 9.99805,
        "keywords": [
            "圣米迦勒教堂",
            "汉堡港（易北河集装箱码头）",
            "易北河",
            "老城石板路",
            "汉堡啤酒馆",
            "海事博物馆",
            "汉堡市政厅",
        ],
    },
    {
        "en": 'Vadodara', "zh": 'Vadodara', "country": 'India',
        "lat": 22.31197, "lon": 73.17807,
        "keywords": [
            "拉克希米维拉斯宫",
            "殖民时期红砖建筑群",
            "古吉拉特香料市场",
            "干燥气候棕榈树街道",
            "印度传统牛车",
            "瓦多达尔市政厅",
        ],
    },
    {
        "en": 'Manaus', "zh": '马瑙斯', "country": 'Brazil',
        "lat": -3.09809, "lon": -60.00196,
        "keywords": [
            "亚马逊河畔",
            "热带雨林植被",
            "殖民风格教堂",
            "亚马逊河鱼料理",
            "木制独木舟",
            "河畔石板路",
            "桑巴舞表演",
            "红木",
        ],
    },
    {
        "en": 'Palembang', "zh": 'Palembang', "country": 'Indonesia',
        "lat": -2.97809, "lon": 104.74808,
        "keywords": [
            "跨河大桥（Ampera Bridge）",
            "默西河沿岸街景",
            "苏丹王宫（Keraton Sri Wedana）",
            "传统木船（prahu）",
            "热带植被中的高脚屋",
            "跨河桥梁的拱形结构",
        ],
    },
    {
        "en": 'San Bernardino', "zh": 'San Bernardino', "country": 'United States',
        "lat": 34.12233, "lon": -117.30198,
        "keywords": [
            "圣贝纳迪诺山脉",
            "内陆帝国商业街",
            "加州干燥灌木丛",
            "San Bernardino市政厅",
            "宽阔西部风格街道",
            "Inland Empire大型购物中心",
        ],
    },
    {
        "en": 'Brussels', "zh": '布鲁塞尔', "country": 'Belgium',
        "lat": 50.83526, "lon": 4.33137,
        "keywords": [
            "原子塔",
            "小尿童雕像",
            "比利时华夫饼",
            "艺术山",
            "布鲁塞尔市政厅",
            "欧洲古典街景",
        ],
    },
    {
        "en": 'Essen', "zh": 'Essen', "country": 'Germany',
        "lat": 51.45, "lon": 7.01661,
        "keywords": [
            "红点博物馆",
            "鲁尔区煤矿工业遗址",
            "工业风格老厂房改造建筑",
            "埃森大教堂",
            "鲁尔区钢铁厂遗迹",
            "工业遗产步道",
        ],
    },
    {
        "en": 'Bhopal', "zh": 'Bhopal', "country": 'India',
        "lat": 23.25193, "lon": 77.40805,
        "keywords": [
            "Bhopal湖",
            "沙普拉王宫",
            "热带植被中的棕榈树",
            "印度三轮车",
            "殖民时期建筑",
            "湖边步道",
        ],
    },
    {
        "en": 'Santos', "zh": 'Santos', "country": 'Brazil',
        "lat": -23.96184, "lon": -46.3285,
        "keywords": [
            "大型货轮停靠的港口",
            "沿海的棕榈树步道",
            "红色屋顶的殖民建筑",
            "港口起重机与集装箱堆场",
            "葡萄牙语标识",
            "大西洋沿岸的海岸线",
        ],
    },
    {
        "en": 'Warsaw', "zh": '华沙', "country": 'Poland',
        "lat": 52.23087, "lon": 21.00535,
        "keywords": [
            "华沙老城",
            "皇家城堡",
            "维斯瓦河",
            "华沙美人鱼雕像",
            "圣约翰主教座堂",
            "石板街道",
            "冬季积雪覆盖的老城区",
        ],
    },
    {
        "en": 'Rabat', "zh": '拉巴特', "country": 'Morocco',
        "lat": 34.02531, "lon": -6.83641,
        "keywords": [
            "摩洛哥王宫",
            "阿尤达清真寺",
            "狭窄鹅卵石街道",
            "阿拉伯文字标识",
            "沿海棕榈树成行道路",
            "手工编织皮革制品",
            "殖民时期拱形门廊建筑",
            "地中海气候干燥灌木丛",
        ],
    },
    {
        "en": 'Vitória', "zh": 'Vitória', "country": 'Brazil',
        "lat": -20.33204, "lon": -40.35394,
        "keywords": [
            "伊塔佩马卡乌阿岛",
            "圣弗朗西斯科大教堂",
            "悬崖海岸街道",
            "沿海岛屿城市",
            "殖民风格石砌建筑",
            "维多利亚港",
        ],
    },
    {
        "en": 'Quito', "zh": '基多', "country": 'Ecuador',
        "lat": -0.21304, "lon": -78.502,
        "keywords": [
            "老城区石板街道",
            "圣弗朗西斯科教堂",
            "安第斯山脉背景",
            "高海拔街景",
            "La Compañía教堂",
            "殖民时期巴洛克建筑",
            "老城区殖民建筑群",
        ],
    },
    {
        "en": 'Antananarivo', "zh": '塔那那利佛', "country": 'Madagascar',
        "lat": -18.91469, "lon": 47.51468,
        "keywords": [
            "安塔那那利佛王宫",
            "热带棕榈树街道",
            "手推车",
            "街头烤鱼串",
            "传统木制高脚建筑",
            "马达加斯加语标识",
        ],
    },
    {
        "en": 'Coimbatore', "zh": 'Coimbatore', "country": 'India',
        "lat": 11.00191, "lon": 76.94808,
        "keywords": [
            "纺织厂烟囱群",
            "Coimbatore中央市场",
            "热带榕树街道",
            "过滤咖啡摊位",
            "泰米尔语路牌",
            "工业区密集建筑",
            "棉纺原料堆场",
        ],
    },
    {
        "en": 'Budapest', "zh": '布达佩斯', "country": 'Hungary',
        "lat": 47.50195, "lon": 19.08138,
        "keywords": [
            "多瑙河",
            "链子桥",
            "布达城堡",
            "匈牙利国会大厦",
            "英雄广场",
            "布达山",
        ],
    },
    {
        "en": 'San Jose', "zh": '圣何塞', "country": 'United States',
        "lat": 37.33094, "lon": -121.88818,
        "keywords": [
            "硅谷科技园区玻璃幕墙建筑群",
            "地中海气候下的加州常绿灌木",
            "网格状街道与现代商业混合街区",
            "硅谷共享单车",
            "创业公司总部集中区",
            "现代科技园区地标性建筑",
        ],
    },
    {
        "en": 'Turin', "zh": '都灵', "country": 'Italy',
        "lat": 45.07233, "lon": 7.66801,
        "keywords": [
            "安托内利尖塔",
            "维托里奥·埃马努埃莱二世纪念堂",
            "马达马宫",
            "巴洛克风格石板街道",
            "都灵巧克力",
            "皇家广场（Piazza Castello）",
        ],
    },
    {
        "en": 'Ludhiana', "zh": 'Ludhiana', "country": 'India',
        "lat": 30.92971, "lon": 75.87031,
        "keywords": [
            "钟楼式钟楼",
            "纺织厂外立面",
            "铁门商铺",
            "旁遮普语招牌",
            "Chole Bhature街头小吃摊",
            "锡克教寺庙",
        ],
    },
    {
        "en": 'Kumasi', "zh": '库马西', "country": 'Ghana',
        "lat": 6.69194, "lon": -1.63196,
        "keywords": [
            "阿散蒂王宫",
            "Kente布",
            "Kejetia市场",
            "木制茅草屋",
            "传统木雕",
            "黄金饰品交易",
            "狭窄混合街道",
        ],
    },
    {
        "en": 'Cincinnati', "zh": 'Cincinnati', "country": 'United States',
        "lat": 39.16383, "lon": -84.45887,
        "keywords": [
            "俄亥俄河（Ohio River）",
            "联合车站（Cincinnati Union Terminal）",
            "大峡谷公园（Great American Ball Park）",
            "装饰艺术风格建筑（Art Deco）",
            "河畔步行道（Ohio River Promenade）",
            "网格状街道布局（Grid street layout）",
            "河畔桥梁（Ohio River Bridge）",
        ],
    },
    {
        "en": 'Isfahan', "zh": 'Isfahan', "country": 'Iran',
        "lat": 32.70195, "lon": 51.69809,
        "keywords": [
            "伊玛目清真寺",
            "四十柱宫",
            "波斯花园",
            "卡尤桥",
            "波斯拱廊街",
            "波斯地毯",
        ],
    },
    {
        "en": 'Yaoundé', "zh": '雅温得', "country": 'Cameroon',
        "lat": 3.86865, "lon": 11.5147,
        "keywords": [
            "带铁艺阳台的殖民风格建筑群",
            "热带稀树草原植被街道绿植",
            "法语路牌（如Rue de la Libération）",
            "街头售卖的Nkang（玉米面糊）摊位",
            "狭窄石板街道与现代混凝土建筑混合",
            "市中心共和国广场集会场景",
            "传统竹编市场篮",
        ],
    },
    {
        "en": 'Sacramento', "zh": 'Sacramento', "country": 'United States',
        "lat": 38.57697, "lon": -121.47198,
        "keywords": [
            "水稻田",
            "州议会大厦",
            "加州水道",
            "淘金热纪念雕塑",
            "网格状街道",
            "加州橡树",
        ],
    },
    {
        "en": 'Agra', "zh": 'Agra', "country": 'India',
        "lat": 27.17237, "lon": 78.01308,
        "keywords": [
            "泰姬陵",
            "阿格拉堡",
            "红砂岩建筑",
            "莫卧儿拱券",
            "白色大理石圆顶",
            "莫卧儿尖塔",
        ],
    },
    {
        "en": 'La Paz', "zh": 'La Paz', "country": 'Bolivia',
        "lat": -16.49603, "lon": -68.15193,
        "keywords": [
            "高海拔安第斯山脉城市",
            "拉巴斯缆车（高空缆车系统）",
            "陡峭山坡阶梯式街道",
            "玻利维亚高原稀薄空气下的建筑",
            "拉巴斯大教堂",
            "科拉山观景台",
        ],
    },
    {
        "en": 'Kalyan', "zh": 'Kalyan', "country": 'India',
        "lat": 19.25023, "lon": 73.16017,
        "keywords": [
            "铁路道口",
            "马拉地语路牌",
            "街头Bhelpuri",
            "传统木门",
            "芒果树街道",
            "铁路信号灯",
            "高密度砖房",
            "干燥棕榈树",
        ],
    },
    {
        "en": 'Abuja', "zh": '阿布贾', "country": 'Nigeria',
        "lat": 9.05462, "lon": 7.48951,
        "keywords": [
            "联邦三角区",
            "国家议会大厦",
            "宽阔林荫大道",
            "放射状主干道",
            "现代玻璃幕墙政府建筑",
            "金合欢树",
            "英语路牌",
            "公共艺术雕塑",
        ],
    },
    {
        "en": 'Harare', "zh": '哈拉雷', "country": 'Zimbabwe',
        "lat": -17.81584, "lon": 31.04276,
        "keywords": [
            "独立广场",
            "稀树草原景观",
            "英式殖民风格建筑",
            "宽阔的独立大道",
            "玉米粉（mealie meal）包装",
            "英语标识",
            "非洲传统木雕",
            "热带草原气候下的干燥草地",
        ],
    },
    {
        "en": 'Khulna', "zh": 'Khulna', "country": 'Bangladesh',
        "lat": 22.84193, "lon": 89.55805,
        "keywords": [
            "恒河三角洲河网",
            "竹编遮阳棚",
            "热带季风植被",
            "库尔纳港码头",
            "狭窄沥青路",
            "孟加拉语路牌",
            "当地鱼饼摊位",
            "高脚竹结构建筑",
        ],
    },
    {
        "en": 'Tijuana', "zh": '蒂华纳', "country": 'Mexico',
        "lat": 32.50196, "lon": -117.08194,
        "keywords": [
            "美墨边境墙",
            "蒂华纳河",
            "墨西哥风格低层密集住宅",
            "圣地亚哥-蒂华纳国际大桥",
            "边境市场",
            "双语街道标识（英语+西班牙语）",
        ],
    },
    {
        "en": 'Perth', "zh": '珀斯', "country": 'Australia',
        "lat": -31.95307, "lon": 115.83805,
        "keywords": [
            "天鹅河",
            "国王公园",
            "天鹅钟楼",
            "弗里曼特尔老监狱",
            "地中海气候下的干燥灌木丛",
            "袋鼠出没的街道",
        ],
    },
    {
        "en": 'Toluca', "zh": 'Toluca', "country": 'Mexico',
        "lat": 19.28931, "lon": -99.65318,
        "keywords": [
            "托卢卡大教堂",
            "州政府大楼",
            "Iztaccíhuatl火山",
            "石板街道",
            "高海拔建筑",
            "墨西哥州首府",
            "街头陶器摊",
            "干旱灌木植被",
        ],
    },
    {
        "en": 'Leeds', "zh": '利兹', "country": 'United Kingdom',
        "lat": 53.79002, "lon": -1.55135,
        "keywords": [
            "利兹市政厅",
            "维多利亚广场",
            "The Headrow",
            "英国铁路博物馆",
            "利兹大学",
            "维多利亚风格石砌建筑群",
        ],
    },
    {
        "en": 'Vishakhapatnam', "zh": 'Vishakhapatnam', "country": 'India',
        "lat": 17.6829, "lon": 83.21985,
        "keywords": [
            "圣乔治堡",
            "沿海渔船群",
            "红树林景观",
            "殖民时期石砌建筑",
            "港口巨型起重机",
            "热带沿海沙滩",
            "椰子树成行的沿海道路",
            "Vizag港标识",
        ],
    },
    {
        "en": 'Kōbe', "zh": 'Kōbe', "country": 'Japan',
        "lat": 34.67999, "lon": 135.16998,
        "keywords": [
            "神户港塔",
            "神户牛肉",
            "神户港红砖仓库",
            "神户的欧式风格街道",
            "神户的港口码头",
            "神户的‘神户’日文标识",
        ],
    },
    {
        "en": 'Multan', "zh": 'Multan', "country": 'Pakistan',
        "lat": 30.20192, "lon": 71.45306,
        "keywords": [
            "沙希德·阿里·汗清真寺",
            "红色砂岩建筑",
            "清真寺圆顶",
            "清真寺尖塔",
            "当地传统市场",
            "圣墓（沙·贾汗墓）",
        ],
    },
    {
        "en": 'Kochi', "zh": 'Kochi', "country": 'India',
        "lat": 10.01695, "lon": 76.22197,
        "keywords": [
            "中国渔网",
            "阿拉伯海港口",
            "殖民时期红砖建筑",
            "椰林成行的沿海街道",
            "传统木制渔船",
            "马拉巴尔咖喱鱼头",
        ],
    },
    {
        "en": 'Gujranwala', "zh": 'Gujranwala', "country": 'Pakistan',
        "lat": 32.16237, "lon": 74.18308,
        "keywords": [
            "古尔拉纳大清真寺",
            "旁遮普红砖民居",
            "街头Bhature小吃摊",
            "干燥混凝土街道",
            "三轮摩托车（Rickshaw）",
            "乌尔都语招牌",
            "路边水果摊",
        ],
    },
    {
        "en": 'Montevideo', "zh": '蒙得维的亚', "country": 'Uruguay',
        "lat": -34.90538, "lon": -56.18682,
        "keywords": [
            "普拉多公园",
            "拉普拉塔河沿岸殖民石砌建筑",
            "棋盘格状历史街区",
            "街头手推车咖啡摊",
            "传统石制拱廊",
            "干燥气候下的街道棕榈树",
        ],
    },
    {
        "en": 'Oakland', "zh": 'Oakland', "country": 'United States',
        "lat": 37.80472, "lon": -122.27804,
        "keywords": [
            "奥克兰港集装箱码头",
            "奥克兰湾大桥",
            "东奥克兰工业风街区",
            "旧金山湾铁路货运线",
            "加州大学伯克利分校校园",
            "湾区天际线",
        ],
    },
    {
        "en": 'Niterói', "zh": 'Niterói', "country": 'Brazil',
        "lat": -22.88253, "lon": -43.10583,
        "keywords": [
            "瓜纳巴拉湾大桥",
            "尼特罗伊市政厅（奥斯卡·尼迈耶设计）",
            "沿海悬崖街道",
            "里约-尼特罗伊跨海大桥",
            "现代主义建筑群",
            "热带沿海植被",
        ],
    },
    {
        "en": 'Florence', "zh": '佛罗伦萨', "country": 'Italy',
        "lat": 43.78, "lon": 11.25,
        "keywords": [
            "圣母百花大教堂",
            "老桥（Ponte Vecchio）",
            "阿诺河",
            "文艺复兴风格建筑",
            "狭窄石板街道",
            "老桥上的珠宝店",
        ],
    },
    {
        "en": 'Bamako', "zh": '巴马科', "country": 'Mali',
        "lat": 12.65196, "lon": -8.00198,
        "keywords": [
            "尼日尔河沿岸街道",
            "殖民时期红砖建筑",
            "法语路牌",
            "热带干旱植被",
            "露天市场摊位",
            "手推车",
            "狭窄沥青街道",
            "班巴拉语标识",
        ],
    },
    {
        "en": 'Conakry', "zh": '科纳克里', "country": 'Guinea',
        "lat": 9.53347, "lon": -13.68218,
        "keywords": [
            "国家议会大厦（Palais du Peuple）",
            "大西洋沿岸港口码头",
            "热带雨林植被环绕的街道",
            "非洲传统市场摊位",
            "沿海潮湿多雨的城市街道",
            "简易木结构民居",
            "非洲风格的路灯柱",
        ],
    },
    {
        "en": 'Bursa', "zh": '布尔萨', "country": 'Turkey',
        "lat": 40.20193, "lon": 29.06805,
        "keywords": [
            "绿色清真寺",
            "伊兹尼克彩绘陶器",
            "布尔萨橄榄树景观",
            "传统土耳其巴扎",
            "绿色山城地形",
            "绿色清真寺拱顶装饰",
            "伊兹尼克蓝白釉陶罐",
            "布尔萨历史城墙",
        ],
    },
    {
        "en": 'Virginia Beach', "zh": 'Virginia Beach', "country": 'United States',
        "lat": 36.85516, "lon": -75.98027,
        "keywords": [
            "弗吉尼亚海滩码头",
            "沿海步道",
            "棕榈树成行的海滨道路",
            "沙质海岸线",
            "海滨防波堤",
            "沙滩椅与遮阳伞",
        ],
    },
    {
        "en": 'León', "zh": 'León', "country": 'Mexico',
        "lat": 21.15193, "lon": -101.70198,
        "keywords": [
            "León大教堂",
            "皮革市场",
            "殖民时期广场",
            "瓜纳华托州首府",
            "传统皮革制品",
            "西班牙语标识牌",
        ],
    },
    {
        "en": 'Nasik', "zh": 'Nasik', "country": 'India',
        "lat": 20.00237, "lon": 73.77804,
        "keywords": [
            "卡尔拉姆神庙",
            "戈达瓦里河",
            "狭窄石板老街",
            "热带季风气候下的芒果树",
            "当地特色烤鱼摊",
            "马拉地语标识",
            "传统木制门廊建筑",
        ],
    },
    {
        "en": 'San Antonio', "zh": '圣安东尼奥', "country": 'United States',
        "lat": 29.41985, "lon": -98.49269,
        "keywords": [
            "阿拉莫",
            "圣安东尼奥河滨步道",
            "西班牙殖民传教所",
            "西班牙殖民建筑",
            "河滨步道拱桥",
            "红瓦屋顶",
        ],
    },
    {
        "en": 'Kansas City', "zh": 'Kansas City', "country": 'United States',
        "lat": 39.10903, "lon": -94.60604,
        "keywords": [
            "电光大楼",
            "密苏里河河岸",
            "Kansas City BBQ",
            "西城商业区",
            "网格状宽阔街道",
            "联合车站",
        ],
    },
    {
        "en": 'Daejeon', "zh": 'Daejeon', "country": 'South Korea',
        "lat": 36.33749, "lon": 127.42308,
        "keywords": [
            "大田科学园区",
            "大田中央图书馆",
            "大田世界贸易中心",
            "大田玻璃幕墙建筑群",
            "大田科学主题雕塑",
            "大田科学城标识牌",
        ],
    },
    {
        "en": 'Phnom Penh', "zh": '金边', "country": 'Cambodia',
        "lat": 11.55198, "lon": 104.91469,
        "keywords": [
            "金边皇宫",
            "湄公河沿岸",
            "法国殖民风格建筑",
            "红色琉璃瓦屋顶",
            "佛教寺庙（高棉风格）",
            "橘色砖墙",
            "湄公河上的船只",
        ],
    },
    {
        "en": 'Kharkiv', "zh": '哈尔科夫', "country": 'Ukraine',
        "lat": 50.00193, "lon": 36.24808,
        "keywords": [
            "哈尔科夫大学主楼",
            "苏联装配式混凝土板楼",
            "圣尼古拉大教堂洋葱顶",
            "哈尔科夫市中心红砖历史建筑",
            "苏联风格老式公交站牌",
            "乌克兰西里尔文字路牌（“Харків”）",
        ],
    },
    {
        "en": 'Lomé', "zh": '洛美', "country": 'Togo',
        "lat": 6.13388, "lon": 1.22081,
        "keywords": [
            "独立纪念碑",
            "沿海棕榈树步道",
            "法式殖民低层建筑",
            "街头摩托车",
            "热带茂密植被",
            "沿海防波堤",
            "非洲市场铁皮屋顶摊位",
            "独立广场",
        ],
    },
    {
        "en": 'Córdoba', "zh": '科尔多瓦', "country": 'Argentina',
        "lat": -31.39801, "lon": -64.18424,
        "keywords": [
            "科尔多瓦大教堂",
            "西班牙殖民风格建筑群",
            "圣弗朗西斯科修道院",
            "狭窄石板街道与拱廊",
            "阿根廷牛肉摊",
            "马黛茶壶",
            "科尔多瓦大学主楼",
        ],
    },
    {
        "en": 'Doha', "zh": 'Doha', "country": 'Qatar',
        "lat": 25.28656, "lon": 51.53297,
        "keywords": [
            "伊斯兰艺术博物馆",
            "卡塔尔国家清真寺",
            "多哈塔",
            "波斯湾海岸线",
            "沙漠与现代建筑融合的街道",
            "阿拉伯风格穹顶",
            "宽阔林荫大道",
        ],
    },
    {
        "en": 'Kuala Lumpur', "zh": '吉隆坡', "country": 'Malaysia',
        "lat": 3.1398, "lon": 101.6887,
        "keywords": [
            "吉隆坡双子塔",
            "独立广场",
            "国家清真寺",
            "吉隆坡塔",
            "街道上的KL标识",
            "热带雨林气候下的现代高楼群",
        ],
    },
    {
        "en": 'Maputo', "zh": '马普托', "country": 'Mozambique',
        "lat": -25.95333, "lon": 32.58722,
        "keywords": [
            "葡萄牙殖民红砖建筑",
            "沿海沙滩与港口",
            "葡萄牙语路牌",
            "三轮摩托车（mototaxi）",
            "圣彼得大教堂",
            "宽阔殖民街道",
            "热带棕榈树",
        ],
    },
    {
        "en": 'Kaduna', "zh": 'Kaduna', "country": 'Nigeria',
        "lat": 10.52196, "lon": 7.43805,
        "keywords": [
            "卡杜纳中央市场",
            "铁栅栏门",
            "手推车运输",
            "殖民时期砖石建筑",
            "热带植物遮阳棚",
            "豪萨语招牌",
            "密集商铺街道",
            "三轮摩托车",
        ],
    },
    {
        "en": 'Ft.  Worth', "zh": 'Ft.  Worth', "country": 'United States',
        "lat": 32.73998, "lon": -97.34004,
        "keywords": [
            "沃斯堡牲畜市场",
            "牛车游行",
            "老式西部火车站",
            "西进博物馆",
            "布法罗河",
            "西部牛仔文化元素",
        ],
    },
    {
        "en": 'Gwangju', "zh": 'Gwangju', "country": 'South Korea',
        "lat": 35.17291, "lon": 126.90849,
        "keywords": [
            "光州广域市厅",
            "光州世界杯体育场",
            "光州冷面",
            "韩式传统街区的石板路",
            "光州艺术殿堂",
            "光州市场",
        ],
    },
    {
        "en": 'Kawasaki', "zh": 'Kawasaki', "country": 'Japan',
        "lat": 35.52999, "lon": 139.705,
        "keywords": [
            "横滨湾大桥",
            "川崎港码头",
            "京急电铁川崎站",
            "川崎市立图书馆",
            "工业设施与住宅区混合的街道",
            "日式现代公寓楼",
            "沿海工业区的街景",
        ],
    },
    {
        "en": 'Indianapolis', "zh": '印第安纳波利斯', "country": 'United States',
        "lat": 39.75193, "lon": -86.17199,
        "keywords": [
            "印第安纳波利斯赛车场",
            "白河",
            "市中心环形广场",
            "印第安纳波利斯艺术博物馆",
            "网格状街道布局",
            "猪肋排卷饼",
        ],
    },
    {
        "en": 'San Salvador', "zh": 'San Salvador', "country": 'El Salvador',
        "lat": 13.70328, "lon": -89.21558,
        "keywords": [
            "圣萨尔瓦多大教堂",
            "国家宫",
            "狭窄殖民石板街道",
            "玉米饼摊",
            "拉美殖民建筑群",
            "火山岩石山坡",
            "街头手推车",
        ],
    },
    {
        "en": 'Karaj', "zh": 'Karaj', "country": 'Iran',
        "lat": 35.8023, "lon": 50.96806,
        "keywords": [
            "卡拉季河",
            "卡拉季中央清真寺",
            "波斯语路牌（显示Karaj）",
            "红色砖墙建筑",
            "宽大的主干道（德黑兰-卡拉季高速）",
            "街边烤肉串摊位",
            "棕榈树街道绿化",
        ],
    },
    {
        "en": 'Lyon', "zh": '里昂', "country": 'France',
        "lat": 45.77195, "lon": 4.82808,
        "keywords": [
            "富维耶圣母院",
            "索恩河",
            "里昂老城拱廊街",
            "富维耶山缆车",
            "里昂美食Bouchon",
            "索恩河畔石板路",
            "里昂公共广场喷泉",
        ],
    },
    {
        "en": 'Kampala', "zh": '坎帕拉', "country": 'Uganda',
        "lat": 0.31861, "lon": 32.58138,
        "keywords": [
            "乌干达独立纪念碑",
            "boda boda摩托车载客",
            "热带金合欢树",
            "马萨卡（绿香蕉菜肴）",
            "斯瓦希里语标识",
            "狭窄石板街道",
            "非洲市场摊位",
        ],
    },
    {
        "en": 'Tabriz', "zh": 'Tabriz', "country": 'Iran',
        "lat": 38.08824, "lon": 46.2993,
        "keywords": [
            "蓝清真寺",
            "波斯地毯",
            "Tabriz历史市场",
            "阿塞拜疆风格圆顶建筑",
            "街头烤肉串摊",
            "传统陶器店铺",
            "红砖老城区街道",
        ],
    },
    {
        "en": 'The Hague', "zh": '海牙', "country": 'Netherlands',
        "lat": 52.08004, "lon": 4.26996,
        "keywords": [
            "和平宫",
            "荷兰低矮红砖联排建筑",
            "狭窄鹅卵石街道",
            "自行车道",
            "库肯霍夫郁金香田",
            "市政厅（Binnenhof）钟楼",
        ],
    },
    {
        "en": 'Davao', "zh": 'Davao', "country": 'Philippines',
        "lat": 7.11196, "lon": 125.62805,
        "keywords": [
            "远处的阿波山",
            "茂密的热带雨林植被",
            "当地市场中的山竹/榴莲摊位",
            "热带气候下的棕榈树环绕街道",
            "菲律宾传统“Sari-sari store”",
            "当地摊位的“banana leaf”餐具",
            "当地特色烤肉摊（Sinugba）",
        ],
    },
    {
        "en": 'Marseille', "zh": '马赛', "country": 'France',
        "lat": 43.29192, "lon": 5.37306,
        "keywords": [
            "马赛老港",
            "红砖建筑",
            "普罗旺斯炖菜",
            "棕榈树街道",
            "圣维克多山",
            "地中海渔船",
            "石砌拱廊",
        ],
    },
    {
        "en": 'Meerut', "zh": 'Meerut', "country": 'India',
        "lat": 29.00236, "lon": 77.69805,
        "keywords": [
            "米尔特堡",
            "老城狭窄石板街道",
            "皮革制品摊位",
            "库拉马",
            "印度教寺庙",
            "三轮车",
            "芒果树",
        ],
    },
    {
        "en": 'Semarang', "zh": 'Semarang', "country": 'Indonesia',
        "lat": -6.96467, "lon": 110.41807,
        "keywords": [
            "红砖钟楼市政厅",
            "默拉皮火山",
            "荷兰殖民时期红砖建筑群",
            "狭窄的殖民街道",
            "Semarang河沿岸的荷兰风格码头",
            "Gudeg特色摊位",
        ],
    },
    {
        "en": 'Faridabad', "zh": 'Faridabad', "country": 'India',
        "lat": 28.43528, "lon": 77.31472,
        "keywords": [
            "大型工业区的集装箱堆场",
            "印度教寺庙的Chhatri凉亭",
            "密集的Auto Rickshaw与摩托车混行",
            "红砖住宅区街道",
            "Faridabad Industrial Area标识",
            "街头Gulab Jamun小吃摊",
            "Delhi-Faridabad高速公路路牌",
        ],
    },
    {
        "en": 'Novosibirsk', "zh": '新西伯利亚', "country": 'Russia',
        "lat": 55.03191, "lon": 82.9581,
        "keywords": [
            "新西伯利亚国立歌剧芭蕾舞剧院",
            "伊尔蒂什河",
            "苏联时期多层砖石公寓楼",
            "冬季积雪的西伯利亚街景",
            "跨伊尔蒂什河的大型桥梁",
            "城市中的大型圆形广场",
        ],
    },
    {
        "en": 'Milwaukee', "zh": 'Milwaukee', "country": 'United States',
        "lat": 43.02961, "lon": -87.91667,
        "keywords": [
            "密尔沃基艺术博物馆（Calatrava设计的翅膀状屋顶）",
            "密歇根湖沿岸街景",
            "翅膀状标志性建筑",
            "密尔沃基湖（密歇根湖）湖景",
            "湖边步道与建筑",
            "工业风格与湖景结合的街道",
        ],
    },
    {
        "en": 'Makkah', "zh": 'Makkah', "country": 'Saudi Arabia',
        "lat": 21.43197, "lon": 39.81809,
        "keywords": [
            "克尔白",
            "圣寺",
            "密集朝圣人群",
            "黑色立方体建筑",
            "阿拉伯风格尖塔",
            "沙漠街道",
            "朝圣路线",
        ],
    },
    {
        "en": 'Dubai', "zh": '迪拜', "country": 'United Arab Emirates',
        "lat": 25.21491, "lon": 55.28695,
        "keywords": [
            "布尔吉·哈利法",
            "棕榈岛",
            "迪拜购物中心",
            "沙漠景观",
            "现代摩天大楼群",
            "阿拉伯风格装饰",
            "沙漠中的高楼",
        ],
    },
    {
        "en": 'Auckland', "zh": '奥克兰', "country": 'New Zealand',
        "lat": -36.84806, "lon": 174.76303,
        "keywords": [
            "天空塔",
            "维多玛塔港",
            "沿海沙滩",
            "伊甸山",
            "亚热带常绿植被",
            "新西兰羊肉",
            "自行车共享系统",
            "温带海洋性气候",
        ],
    },
    {
        "en": 'Brazzaville', "zh": '布拉柴维尔', "country": 'Congo (Brazzaville)',
        "lat": -4.25724, "lon": 15.28274,
        "keywords": [
            "刚果河畔桥梁",
            "殖民风格大教堂",
            "热带雨林街道植被",
            "法语路牌标识",
            "刚果河鱼市场",
            "沿河滨河步道",
            "非洲传统木雕",
            "宽林荫大道",
        ],
    },
    {
        "en": 'Lubumbashi', "zh": 'Lubumbashi', "country": 'Congo (Kinshasa)',
        "lat": -11.67808, "lon": 27.47807,
        "keywords": [
            "欧式红砖殖民建筑群",
            "铜矿运输车辆",
            "Kabila广场",
            "热带阔叶树街道",
            "密集市场摊位",
            "铜矿公司标识",
        ],
    },
    {
        "en": 'Varanasi', "zh": 'Varanasi', "country": 'India',
        "lat": 25.33194, "lon": 82.99809,
        "keywords": [
            "恒河岸边石阶群",
            "恒河渡船",
            "古老寺庙建筑",
            "沿河沐浴人群",
            "圣河渡口",
            "河边小吃摊",
            "朝圣者聚集",
        ],
    },
    {
        "en": 'Orlando', "zh": 'Orlando', "country": 'United States',
        "lat": 28.51192, "lon": -81.38198,
        "keywords": [
            "华特迪士尼世界",
            "环球影城",
            "国际大道",
            "哈利波特的魔法世界",
            "棕榈树成行的街道",
            "迪士尼乐园标志",
            "侏罗纪公园主题区",
            "热带风情街景",
        ],
    },
    {
        "en": 'Ciudad Juárez', "zh": 'Ciudad Juárez', "country": 'Mexico',
        "lat": 31.69232, "lon": -106.49199,
        "keywords": [
            "美墨边境国际桥",
            "干燥灌木丛",
            "街头玉米饼摊",
            "西班牙语路牌",
            "宽幅边境主干道",
            "边境隔离栏",
            "干燥沙土路面",
            "墨西哥北部沙漠植被",
        ],
    },
    {
        "en": 'Ghaziabad', "zh": 'Ghaziabad', "country": 'India',
        "lat": 28.66233, "lon": 77.40645,
        "keywords": [
            "加济阿巴德中央市场玻璃顶棚",
            "德里-加济阿巴德高速公路高架桥",
            "老城区Haveli式建筑",
            "街道上的印度教神像雕塑",
            "Chowk传统集市摊位",
            "Ghats河岸阶梯",
            "干燥灌木丛街道",
            "Ghaziabad Biryani小吃摊",
        ],
    },
    {
        "en": 'Pretoria', "zh": '比勒陀利亚', "country": 'South Africa',
        "lat": -25.70498, "lon": 28.22748,
        "keywords": [
            "联合大厦",
            "布尔战争纪念碑",
            "英式殖民红砖建筑",
            "宽阔英式街道",
            "金合欢树",
            "殖民时期铸铁路灯",
            "行政首都标识",
            "南非国旗元素",
        ],
    },
    {
        "en": 'Porto', "zh": '波尔图', "country": 'Portugal',
        "lat": 41.15195, "lon": -8.62195,
        "keywords": [
            "杜罗河",
            "里亚托桥",
            "Ribeira老街石板路",
            "葡萄牙蛋挞",
            "沿河酒窖",
            "葡萄牙式陶瓦屋顶",
            "渡轮码头",
        ],
    },
    {
        "en": 'Lusaka', "zh": '卢萨卡', "country": 'Zambia',
        "lat": -15.4147, "lon": 28.28138,
        "keywords": [
            "金合欢树成行的街道",
            "非洲传统茅草屋顶建筑",
            "boda boda 三轮摩托车",
            "密集的非洲传统市场摊位",
            "干燥季节的尘土路面",
            "带有Bemba语文字的木制招牌",
            "红色砖砌的现代市政建筑",
            "新鲜热带水果摊位",
        ],
    },
    {
        "en": 'Asansol', "zh": 'Asansol', "country": 'India',
        "lat": 23.68528, "lon": 86.98139,
        "keywords": [
            "钢铁厂大型烟囱",
            "红砖工业厂房",
            "铁路轨道与城市街道交汇",
            "殖民时期砖石建筑",
            "钢铁厂机械设备",
            "西孟加拉邦风格民居",
        ],
    },
    {
        "en": 'Mosul', "zh": 'Mosul', "country": 'Iraq',
        "lat": 36.34695, "lon": 43.14306,
        "keywords": [
            "摩苏尔大清真寺尖塔",
            "狮子雕像",
            "狭窄石板街道",
            "阿拉伯式拱门",
            "阿拉伯文字标识",
            "干旱环境下的高耸清真寺",
        ],
    },
    {
        "en": 'Yekaterinburg', "zh": '叶卡捷琳堡', "country": 'Russia',
        "lat": 56.85198, "lon": 60.59801,
        "keywords": [
            "乌拉尔联邦大学主楼",
            "伊塞特河河岸",
            "苏联时期多层公寓楼",
            "冬季积雪覆盖的乌拉尔街道",
            "红十月工厂烟囱",
            "乌拉尔山脉余脉山体",
            "苏联式路灯",
        ],
    },
    {
        "en": 'Peshawar', "zh": 'Peshawar', "country": 'Pakistan',
        "lat": 34.00696, "lon": 71.53306,
        "keywords": [
            "巴扎的木质遮阳棚",
            "清真寺的宣礼塔",
            "手工编织的地毯摊位",
            "街头烤馕摊",
            "干燥灌木丛中的胡杨树",
            "狭窄的石板街道",
            "带有乌尔都语标识的招牌",
            "骆驼在巴扎入口处",
        ],
    },
    {
        "en": 'Mandalay', "zh": 'Mandalay', "country": 'Myanmar',
        "lat": 21.97193, "lon": 96.08308,
        "keywords": [
            "乌本桥",
            "曼德勒皇宫",
            "马哈穆尼佛寺",
            "柚木桥",
            "老城区木屋街道",
            "缅甸佛塔林",
        ],
    },
    {
        "en": 'Jamshedpur', "zh": 'Jamshedpur', "country": 'India',
        "lat": 22.78948, "lon": 86.19557,
        "keywords": [
            "钢铁厂烟囱群",
            "Tata Steel厂区建筑",
            "工业管道设施",
            "宽幅工业主干道",
            "钢铁厂机械起重机",
            "热带阔叶树与工业设施混合景观",
        ],
    },
    {
        "en": 'Mbuji-Mayi', "zh": 'Mbuji-Mayi', "country": 'Congo (Kinshasa)',
        "lat": -6.14808, "lon": 23.59805,
        "keywords": [
            "露天铜矿坑",
            "铜矿开采设备",
            "矿工居住区简易棚屋",
            "铜矿运输卡车",
            "法语路牌",
            "热带草原植被",
            "殖民时期砖石建筑",
        ],
    },
    {
        "en": 'Madurai', "zh": 'Madurai', "country": 'India',
        "lat": 9.92197, "lon": 78.11808,
        "keywords": [
            "梅纳克希神庙",
            "石板铺就的古老街道",
            "印度教神庙双塔",
            "彩色神庙招牌",
            "传统木制门廊",
            "热带植被环绕的神庙",
            "当地特色小吃摊",
        ],
    },
    {
        "en": 'Adana', "zh": '阿达纳', "country": 'Turkey',
        "lat": 36.99694, "lon": 35.31806,
        "keywords": [
            "塞伊汉河",
            "阿达纳烤肉串",
            "红砖工业建筑群",
            "地中海橄榄树景观",
            "阿达纳中央市场",
            "沿河码头",
            "特色街灯",
            "当地陶器",
        ],
    },
    {
        "en": 'Sheffield', "zh": 'Sheffield', "country": 'United Kingdom',
        "lat": 53.36668, "lon": -1.5,
        "keywords": [
            "维多利亚式铁艺建筑",
            "钢铁结构桥梁",
            "石板铺就街道",
            "工业革命铸铁厂房",
            "Sheffield Park花园",
            "哥特式大教堂",
            "工业遗产区",
            "钢铁工业标识",
        ],
    },
    {
        "en": 'Jabalpur', "zh": 'Jabalpur', "country": 'India',
        "lat": 23.177, "lon": 79.95311,
        "keywords": [
            "Bhedaghat 白色岩石峡谷",
            "Narmada River 纳尔默达河",
            "殖民时期砖石建筑",
            "Golgappa 街头小吃",
            "热带稀树草原植被",
            "印地语标识",
        ],
    },
    {
        "en": 'San José', "zh": '圣何塞', "country": 'Costa Rica',
        "lat": 9.93037, "lon": -84.07881,
        "keywords": [
            "国家剧院",
            "西班牙殖民风格建筑",
            "热带雨林植被",
            "街边咖啡店",
            "西班牙语路牌",
            "棕榈树成行的街道",
            "街头玉米饼摊",
        ],
    },
    {
        "en": 'Panama City', "zh": '巴拿马城', "country": 'Panama',
        "lat": 8.96996, "lon": -79.53498,
        "keywords": [
            "巴拿马运河",
            "美国区装饰艺术建筑",
            "老城区殖民教堂",
            "科隆岛",
            "热带植被环绕的运河沿岸",
            "老城区石板街道",
            "美式复古商店招牌",
            "巴拿马大教堂",
        ],
    },
    {
        "en": 'Nizhny Novgorod', "zh": '下诺夫哥罗德', "country": 'Russia',
        "lat": 56.33495, "lon": 43.99815,
        "keywords": [
            "克里姆林宫",
            "伏尔加河",
            "圣谢尔盖大教堂",
            "石砌历史街道",
            "东正教洋葱头圆顶",
            "伏尔加河畔石桥",
            "俄罗斯传统木构建筑",
            "历史克里姆林宫塔楼",
        ],
    },
    {
        "en": 'Providence', "zh": 'Providence', "country": 'United States',
        "lat": 41.82305, "lon": -71.41693,
        "keywords": [
            "普罗维登斯河滨公园",
            "布朗大学哥特式建筑",
            "维多利亚风格石板街道",
            "罗德岛州议会大厦圆顶",
            "冬季积雪覆盖的狭窄街道",
            "滨河步道的喷泉",
        ],
    },
    {
        "en": 'Duisburg', "zh": 'Duisburg', "country": 'Germany',
        "lat": 51.42997, "lon": 6.75002,
        "keywords": [
            "鲁尔河与莱茵河交汇处",
            "工业遗产建筑群",
            "窄巷老工业厂房",
            "鲁尔区铁锈色厂房",
            "港口集装箱码头",
            "工业风复古蒸汽管道",
        ],
    },
    {
        "en": 'Munich', "zh": '慕尼黑', "country": 'Germany',
        "lat": 48.13189, "lon": 11.57305,
        "keywords": [
            "玛丽亚广场的玛丽亚雕像",
            "新市政厅的钟楼",
            "德国博物馆",
            "奥林匹克公园",
            "霍夫布劳豪斯啤酒馆",
            "巴伐利亚传统服饰",
            "尖顶教堂",
        ],
    },
    {
        "en": 'Columbus', "zh": '哥伦布', "country": 'United States',
        "lat": 39.98192, "lon": -82.99196,
        "keywords": [
            "俄亥俄州议会大厦",
            "俄亥俄州立大学主图书馆",
            "橡子（buckeye）标志",
            "The Oval校园区域",
            "中西部网格街道与州政府建筑",
            "buckeye甜点摊位",
        ],
    },
    {
        "en": 'Stockholm', "zh": '斯德哥尔摩', "country": 'Sweden',
        "lat": 59.32413, "lon": 18.0663,
        "keywords": [
            "斯德哥尔摩老城红色木屋",
            "斯德哥尔摩王宫",
            "斯德哥尔摩运河",
            "大教堂尖顶（Storkyrkan）",
            "狭窄石板街道",
            "波罗的海沿岸岛屿城市",
            "诺贝尔博物馆",
        ],
    },
    {
        "en": 'Makassar', "zh": 'Makassar', "country": 'Indonesia',
        "lat": -5.13801, "lon": 119.43008,
        "keywords": [
            "曼古布米皇宫",
            "马卡萨钟楼",
            "传统Pinisi帆船",
            "椰子树环绕的热带街道",
            "混合殖民风格的欧式建筑",
            "印尼传统市场摊位",
            "热带植被中的高耸棕榈树",
            "绿豆粥摊位",
        ],
    },
    {
        "en": 'Rajkot', "zh": 'Rajkot', "country": 'India',
        "lat": 22.31197, "lon": 70.79806,
        "keywords": [
            "甘地出生地纪念堂（Kirti Mandir）",
            "古吉拉特红砂岩建筑",
            "Auto Rickshaw（印度三轮车）",
            "窄巷红砖街道",
            "古吉拉特语标识招牌",
            "热带棕榈树",
            "传统Gujarati小吃摊",
            "印度教纪念建筑",
        ],
    },
    {
        "en": 'West Palm Beach', "zh": 'West Palm Beach', "country": 'United States',
        "lat": 26.74502, "lon": -80.12362,
        "keywords": [
            "棕榈树成行的海滨街道",
            "热带滨海度假酒店",
            "阳光明媚的海滨步道",
            "椰子树点缀的街道",
            "低层海滨建筑群",
            "海滨沙滩椅与遮阳伞",
        ],
    },
    {
        "en": 'Taipei', "zh": '台北', "country": 'Taiwan',
        "lat": 25.033, "lon": 121.5654,
        "keywords": [
            "台北101",
            "西门町",
            "珍珠奶茶",
            "捷运",
            "龙山寺",
            "繁体中文招牌",
            "夜市",
            "阳明山",
        ],
    },
    {
        "en": 'New Taipei', "zh": '新北', "country": 'Taiwan',
        "lat": 25.0111, "lon": 121.4458,
        "keywords": [
            "淡水老街",
            "九份",
            "平溪天灯",
            "十分瀑布",
            "基隆河",
            "庙口夜市",
        ],
    },
    {
        "en": 'Kaohsiung', "zh": '高雄', "country": 'Taiwan',
        "lat": 22.6273, "lon": 120.3014,
        "keywords": [
            "高雄港",
            "爱河",
            "85大楼",
            "驳二艺术特区",
            "瑞丰夜市",
            "打狗英国领事馆",
        ],
    },
    {
        "en": 'Taichung', "zh": '台中', "country": 'Taiwan',
        "lat": 24.1477, "lon": 120.6736,
        "keywords": [
            "逢甲夜市",
            "彩虹眷村",
            "太阳饼",
            "台中公园",
            "高美湿地",
            "东海大学路思义教堂",
        ],
    },
    {
        "en": 'Tainan', "zh": '台南', "country": 'Taiwan',
        "lat": 22.9997, "lon": 120.227,
        "keywords": [
            "赤崁楼",
            "安平古堡",
            "花园夜市",
            "担仔面",
            "台南孔庙",
            "神农街",
        ],
    },
    {
        "en": 'Zhongli', "zh": '中坜', "country": 'Taiwan',
        "lat": 24.9652, "lon": 121.2252,
        "keywords": [
            "中坜夜市",
            "中原夜市",
            "桃园机场附近",
            "老街溪",
        ],
    },
]
